(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var t3=function(a){a.ea("cardstatechange",a.yh()&&a.pk()?1:0)},u3=function(a,b){var c=g.La(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},vOa=function(a){var b=g.Ql(a);
a=g.Wl(a);return new g.El(b.x,b.y,a.width,a.height)},wOa=function(a){return Math.pow(a,3)},xOa=function(a){return 3*a*a-2*a*a*a},x3=function(a){a=g.Oa(a);
delete v3[a];g.oc(v3)&&w3&&w3.stop()},zOa=function(){w3||(w3=new g.J(function(){yOa()},20));
var a=w3;a.isActive()||a.start()},yOa=function(){var a=g.Qa();
g.Zb(v3,function(b){AOa(b,a)});
g.oc(v3)||zOa()},y3=function(a,b,c,d){g.br.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.u=a;this.S=b;this.duration=c;this.I=d;this.coords=[];this.progress=this.K=0;this.D=null},AOa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.K=1E3/(b-a.D);a.D=b;BOa(a,a.progress);1==a.progress?(a.i=0,x3(a),a.onFinish(),a.Cw()):a.Dc()&&a.fC()},BOa=function(a,b){"function"===typeof a.I&&(b=a.I(b));
a.coords=Array(a.u.length);for(var c=0;c<a.u.length;c++)a.coords[c]=(a.S[c]-a.u[c])*b+a.u[c]},COa=function(a,b){g.ye.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.K;this.state=b.i},z3=function(a,b,c,d,e){y3.call(this,b,c,d,e);
this.element=a},A3=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
z3.call(this,a,b,c,d,e)},B3=function(a){g.H.call(this);
this.u=a||window;this.i=[]},C3=function(a){return a.baseUrl||null},D3=function(a,b){return g.Do(g.jm(a,b,void 0),function(c){return!!c})},DOa=function(a,b,c){function d(W){var ia,sa,Lb,zb=W.hovercardButton;
if(!zb)return null;zb=zb.subscribeButtonRenderer;if(!zb)return null;var Gc=f(zb.unsubscribedButtonText),Ld=f(zb.subscribedButtonText);if(zb.subscribed){var Ob=f(zb.subscriberCountWithUnsubscribeText);var Md=f(zb.subscriberCountText)}else Ob=f(zb.subscriberCountText),Md=f(zb.subscriberCountWithSubscribeText);var Sb=null;return W.signinEndpoint&&(Sb=u3(W,"signinEndpoint","webNavigationEndpointData","url"),Sb||(Sb=null===(Lb=null===(sa=null===(ia=zb.signInEndpoint)||void 0===ia?void 0:ia.commandMetadata)||
void 0===sa?void 0:sa.webCommandMetadata)||void 0===Lb?void 0:Lb.url),!Sb)?null:Gc&&(Ld||Sb)?{subscribed:zb.subscribed,subscribeText:Gc,subscribeCount:Ob,unsubscribeText:Ld,unsubscribeCount:Md,enabled:zb.enabled,signinUrl:Sb,classic:W.useClassicSubscribeButton}:null}
function e(W){if(W){var ia=[],sa=W.videoId;sa&&ia.push("v="+sa);(sa=W.playlistId)&&ia.push("list="+sa);(W=W.startTimeSeconds)&&ia.push("t="+W);return"/watch?"+ia.join("&")}}
function f(W){if(!W)return null;var ia=W.simpleText;return ia?ia:W.runs?g.jm(W.runs,function(sa){return sa.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=null,q=null,t=null,u=null,x=!1,y=null,z=null,G=null,E=null,C=null;if("VIDEO"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,q=f(b.videoDuration);else if("PLAYLIST"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,t=f(b.playlistLength);else if("CHANNEL"===h){if(x=u3(l,"browseEndpoint","browseId"))u=x,m="/channel/"+u;n=!1;p="new";(x=!!b.isSubscribe)?y=d(b):z=f(b.subscribersText)}else"WEBSITE"===
h?((G=u3(l,"urlEndpoint","url"))&&(m=G),n=!0,p="new",G=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(E=f(b.productPrice)),b.additionalFeesText&&(C=f(b.additionalFeesText)),(n=u3(l,"urlEndpoint","url"))&&(m=n),n=!0,p="new");a=u3(b,"title","accessibility","accessibilityData","label");var L=b.endpoint?b.endpoint.clickTrackingParams:null,S="";if(b.metadata){var K=f(b.metadata);K&&(S=K)}return{id:"element-"+c,type:h,title:f(b.title),metadata:S,callToAction:f(b.callToAction),UJ:b.image,
iconUrl:G,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:q,playlistLength:t,channelId:u,subscribeButton:y,subscribersText:z,isSubscribe:x,targetUrl:m||null,NS:n,sessionData:L?{itct:L}:null,wX:p,Gu:a?a:null,QS:b.isPlaceholder,impressionUrls:D3(b.impressionUrls||[],C3),ES:D3(b.hovercardShowUrls||[],C3),clickUrls:D3(l.loggingUrls||[],C3),visualElement:g.vy(b.trackingParams),
productPrice:E,additionalFeesText:C}},E3=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:D3(a.impressionUrls||[],C3),elements:D3(a.elements||[],function(d,e){return DOa(b,d,e)})};
a.trackingParams&&(c.visualElement=g.vy(a.trackingParams));return c},F3=function(a){g.ZM.call(this,a);
this.B=this.endscreen=null;this.i={};this.D={};this.C=this.u=null;this.K=[];this.X=!0;this.I=0;a=a.V();this.S=g.ZE(a)||g.cF(a);this.events=new g.qD(this);g.I(this,this.events);this.events.T(this.player,g.jA("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.kA("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.wb);this.events.T(window,"focus",this.yW);this.load();var b=g.Gg("STYLE");(g.sg("HEAD")[0]||document.body).appendChild(b);g.xe(this,function(){g.Kg(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},EOa=function(a){return a.player.getVideoData().D?"current":a.S?"new":"current"},G3=function(a){return"creator-endscreen-editor"===a.player.V().playerStyle},FOa=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.B&&a.B.abort();c={method:"POST",onFinish:function(e){var f=a.B=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=E3(f,EOa(a))));H3(a,f)},
urlParams:{v:c},withCredentials:!0};a.S&&(c.urlParams.ptype="embedded");var d=b.oq;d&&(c.postParams={ad_tracking:d});if(b=g.wpa(b))if(b=g.Af(b),b=g.wf(b))a.B=g.wt(b,c)},H3=function(a,b,c){c=void 0===c?!0:c;
a.player.Xe("creatorendscreen");a.u&&(a.u.dispose(),a.u=null,a.C.dispose(),a.C=null);for(var d=g.r(Object.values(a.i)),e=d.next();!e.done;e=d.next())e.value.dispose();a.i={};a.D={};0<a.K.length&&(a.K.forEach(function(l){l.dispose()}),a.K.length=0);
a.I=0;if((a.endscreen=b)&&b.elements){c&&GOa(a);c=[];d=new g.hA(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.V().isMobile||(a.u=new g.V({G:"div",L:"ytp-ce-shadow"}),g.MM(a.player,a.u.element,4),a.C=new g.vL(a.u,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=HOa(a,e);if(f){a.i[e.id]=f;a.D[e.id]=e;g.MM(a.player,f.element,4);var h=new g.hA(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);IOa(a,
f,e)}else g.Iy(new g.Yv("buildEndscreenElement null",e))}a.player.Ad(c);a.wb()}},GOa=function(a){var b=g.zy(),c=g.Ay();
c&&b&&a.endscreen.visualElement&&g.My(void 0,c,b,[a.endscreen.visualElement])},HOa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c=a.player.N("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];a={G:"div",Ga:["ytp-ce-element","ytp-ce-video"],W:{tabindex:"0","aria-label":b.Gu||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-covering-image",W:I3(b)},{G:"div",L:"ytp-ce-covering-shadow-top"},{G:"a",L:"ytp-ce-covering-overlay",W:{href:J3(a,b.targetUrl),tabindex:"-1"},U:[{G:"div",Ga:["ytp-ce-video-title"].concat(g.ma(c)),W:{dir:g.lr(b.title||
"")},xa:b.title},{G:"div",L:"ytp-ce-video-duration",xa:b.videoDuration||void 0}]}]};c=new g.V(a);break;case "PLAYLIST":c=a.player.N("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];a={G:"div",Ga:["ytp-ce-element","ytp-ce-playlist"],W:{tabindex:"0","aria-label":b.Gu||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-covering-image",W:I3(b)},{G:"div",L:"ytp-ce-covering-shadow-top"},{G:"a",L:"ytp-ce-covering-overlay",W:{href:J3(a,
b.targetUrl),tabindex:"-1"},U:[{G:"div",Ga:["ytp-ce-playlist-title"].concat(g.ma(c)),W:{dir:g.lr(b.title||"")},xa:b.title},{G:"div",L:"ytp-ce-playlist-count",U:[{G:"div",L:"ytp-ce-playlist-icon"},{G:"div",L:"ytp-ce-playlist-count-text",xa:b.playlistLength||void 0}]}]}]};c=new g.V(a);break;case "CHANNEL":c={G:"div",Ga:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],W:{tabindex:"0","aria-label":b.Gu||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},
{G:"div",L:"ytp-ce-expanding-overlay",U:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",U:[{G:"div",L:"ytp-ce-expanding-overlay-body",U:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",U:[{G:"a",Ga:["ytp-ce-channel-title","ytp-ce-link"],W:{href:J3(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.lr(b.title||"")},xa:b.title},b.subscribeButton?{G:"div",L:"ytp-ce-subscribe-container",U:[{G:"div",L:"ytp-ce-channel-subscribe"}]}:
"",b.subscribersText?{G:"div",L:"ytp-ce-channel-subscribers-text",xa:b.subscribersText}:"",b.metadata?{G:"div",Ga:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],xa:b.metadata}:""]}]}]}]},{G:"div",L:"ytp-ce-expanding-image",W:I3(b)}]};c=new g.V(c);var d=g.tg(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.M(d,"ytp-ce-subscribe-button");if(a.player.V().isMobile){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.bO(b.subscribeButton.subscribeText,
b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.K.push(e)}break;case "WEBSITE":a={G:"div",Ga:["ytp-ce-element","ytp-ce-website"],W:{tabindex:"0","aria-label":b.Gu||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-expanding-overlay",U:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},
{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",U:[{G:"div",L:"ytp-ce-expanding-overlay-body",U:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",U:[{G:"div",L:"ytp-ce-website-title",W:{dir:g.lr(b.title||"")},xa:b.title},{G:"div",L:"ytp-ce-website-metadata",xa:b.metadata},{G:"a",Ga:["ytp-ce-website-goto","ytp-ce-link"],W:{href:J3(a,b.targetUrl),target:"_blank",tabindex:"-1"},xa:b.callToAction}]}]}]}]},{G:"div",L:"ytp-ce-expanding-image",W:I3(b)},{G:"div",
L:"ytp-ce-expanding-icon",W:JOa(b.iconUrl)}]};c=new g.V(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={G:"div",L:"ytp-ce-merchandise-price-container",U:[{G:"div",L:"ytp-ce-merchandise-price",xa:b.productPrice}]},b.additionalFeesText&&c.U.push({G:"div",L:"ytp-ce-merchandise-additional-fees",xa:b.additionalFeesText})),a={G:"div",Ga:["ytp-ce-element","ytp-ce-merchandise"],W:{tabindex:"0","aria-label":b.Gu||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-expanding-overlay",
U:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",U:[{G:"div",L:"ytp-ce-expanding-overlay-body",U:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",U:[{G:"div",L:"ytp-ce-merchandise-title",W:{dir:g.lr(b.title||"")},xa:b.title},c,{G:"div",L:"ytp-ce-merchandise-metadata",xa:b.metadata},{G:"a",Ga:["ytp-ce-merchandise-goto","ytp-ce-link"],W:{href:J3(a,b.targetUrl),target:"_blank",tabindex:"-1"},xa:b.callToAction}]}]}]}]},
{G:"div",L:"ytp-ce-expanding-image",W:I3(b)},{G:"div",L:"ytp-ce-merchandise-invideo-cta-container",U:[{G:"div",L:"ytp-ce-merchandise-invideo-cta",xa:b.callToAction||void 0}]}]},c=new g.V(a)}b.QS&&g.M(c.element,"ytp-ce-placeholder");return c},I3=function(a){if(a.UJ)var b=a.UJ.thumbnails;
return JOa(b?b[b.length-1].url:null)},JOa=function(a){return a?{style:"background-image: url("+a+")"}:{}},IOa=function(a,b,c){function d(m){m&&(b.Ra("blur",function(){"none"!=m.style.display&&a.X&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",h))}
function e(m){a.I+=m;0<a.I?(g.M(b.element,"ytp-ce-force-expand"),K3(a,c.id,!0)):(g.Qq(b.element,"ytp-ce-force-expand"),g.Qq(b.element,"ytp-ce-element-hover"),K3(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Ra("mouseenter",function(){L3(a,b,c)});
b.Ra("mouseleave",function(){M3(a,b,c)});
a.player.V().isMobile||b.Ra("click",function(){g.M(b.element,"ytp-ce-element-hover")});
b.Ra("click",function(m){KOa(a,c,m)});
b.Ra("keypress",function(m){KOa(a,c,m)});
b.Ra("focus",function(){L3(a,b,c)});
b.Ra("blur",function(){M3(a,b,c)});
b.Ra("touchstart",function(){L3(a,b,c)});
var l=g.vg("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.Qq(b.element,"ytp-ce-element-hover");g.Qq(b.element,"ytp-ce-force-expand")});
b.Ra("keydown",function(m){a.X=9===m.keyCode&&!m.shiftKey});
d(g.vg("ytp-sb-subscribe",b.element));d(g.vg("ytp-sb-unsubscribe",b.element));b.Ra("focus",f);b.Ra("blur",h)},KOa=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.Oq(d,"ytp-ce-element");){g.Oq(d,"subscribe-label")&&N3(a,b);
if(g.Oq(d,"ytp-ce-channel-subscribe"))return;d=g.Lg(d)}if(!d||g.Oq(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.i[b.id])M3(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.wX)N3(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Af(J3(a,b.targetUrl)),c=g.wf(c),g.VL(c,void 0,b.sessionData);else{var e=a.player.getVideoData().D,f=function(){var h=J3(a,b.targetUrl),l=b.sessionData,m=g.Ks(h);e&&m&&(m.v||m.list)?a.player.Oj(m.v,l,m.list,!1):
g.UL(h,l)};
N3(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},J3=function(a,b){a=a.player.V();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.BF(a)+b}else return"";return b},L3=function(a,b,c){g.Oq(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.M(b.element,"ytp-ce-element-hover"):a.player.V().isMobile?(new g.J(function(){g.M(b.element,"ytp-ce-element-hover")},200)).start():g.M(b.element,"ytp-ce-element-hover"),O3(a,c.ES),K3(a,c.id,!0))},M3=function(a,b,c){g.Qq(b.element,"ytp-ce-element-hover");
g.Qq(b.element,"ytp-ce-force-expand");K3(a,c.id,!1)},K3=function(a,b,c){a.u&&(c?a.C.show():a.C.hide());
for(var d=g.r(Object.keys(a.i)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.N(a.i[e].element,"ytp-ce-element-shadow-show",c)},O3=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||G3(a))c&&c();else{b=LOa(a,b);var e=0,f=!1,h=new g.J(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.Vu(b[a],d)}},N3=function(a,b,c){O3(a,b.clickUrls,c);
(a=g.Ay())&&b.NS&&g.Sy(a,b.visualElement)},LOa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(MOa(b[d],c));return a},MOa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},NOa=function(a){return"string"===typeof a?a:""},P3=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},OOa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.i=d},Q3=function(a){return a.value?a.value:null},R3=function(a){if(!a)return null;
var b=g.Af(NOa(a.value));b=g.wf(b);if(!b)return null;var c=P3(a.target,POa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new OOa(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},QOa=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},TOa=function(a){if(!a)return null;
var b=P3(a.type,ROa),c=P3(a.trigger,SOa);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=R3(a?a:null);return b?new QOa(b,c,a):null},S3=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},UOa=function(a,b){return g.sb(a.action,b,void 0)},VOa=function(a,b){this.context=a;
this.i=b},U3=function(a){return a.customMessage?T3("div","iv-card-message",a.customMessage):""},V3=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{G:"div",L:"iv-card-image",W:{style:a},U:c}},W3=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.r(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(T3("li","",c.value));return{G:"ul",L:"iv-card-meta-info",U:b}},T3=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.lr(c);return{G:a,W:b,xa:c}},WOa=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.jy&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.jy+");");c.dir=g.lr(a.customMessage);var d=[{G:"span",xa:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({G:"span",L:"iv-card-link-icon"}));return{G:"div",Ga:b,W:c,U:d}},X3=function(a,b,c,d){if(d){b=g.r(b);
for(var e=b.next();!e.done;e=b.next())a.i(e.value,d,c.id,c.sessionData,c.tracking.click,5)}},XOa=function(a,b){this.merchant=a;
this.price=b},YOa=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},ZOa=function(a,b){return b?b:YOa(a)?"current":"new"},Y3=function(a,b){g.H.call(this);
var c=this;this.element=a;this.context=b;this.Za=!1;this.Pa=new Map;this.Va=new Map;this.context.J.addEventListener(g.jA("annotations_module"),function(d){(d=c.Pa.get(d))&&d.apply(c)});
this.context.J.addEventListener(g.kA("annotations_module"),function(d){(d=c.Va.get(d))&&d.apply(c)})},Z3=function(a,b,c,d,e,f,h){a.context.i.Ra(b,"click",function(l){a.gC(c,d,e,f||[],h||0,l)});
a.context.i.Ra(b,"touchstart",function(){a.Za=!1});
a.context.i.Ra(b,"touchmove",function(){a.Za=!0})},$Oa=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},$3=function(a,b,c){return{impression:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
fO:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
fB:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},c4=function(a,b,c){Y3.call(this,b,c);
var d=this;this.J=a;this.eventId=null;this.La=this.kb=this.B=this.Yd=!1;this.va=null;this.cards=[];this.ib=this.S=this.Ja=this.D=this.Ka=this.i=null;this.ma=[];this.K=this.Ce=this.Ba=null;this.I=0;this.Aa=new g.J(g.Ia,c.Y.qd?4E3:3E3);g.I(this,this.Aa);this.fb=new g.J(g.Ia);g.I(this,this.fb);this.Z=new VOa(c,function(e,f,h,l,m,n){Z3(d,e,f,h,l,m,n)});
this.X=new g.V({G:"div",L:"iv-drawer",W:{id:"iv-drawer"},U:[{G:"div",L:"iv-drawer-header",W:{"aria-role":"heading"},U:[{G:"span",L:"iv-drawer-header-text"},{G:"button",Ga:["iv-drawer-close-button","ytp-button"],W:{"aria-label":"Hide cards",tabindex:"0"}}]},{G:"div",L:"iv-drawer-content"}]});g.I(this,this.X);this.C=this.X.element;this.Wa=new g.vL(this.X,330);g.I(this,this.Wa);this.ob=g.vg("iv-drawer-header-text",this.C);this.u=g.vg("iv-drawer-content",this.C);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.kb&&a4(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.kb=d.B)&&b4(d)})},aPa=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){a4(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){b4(a)});
var c=b.headerText;g.Ng(a.ob,c);a.S&&a.S.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ba=g.vy(b.trackingParams);a.K=g.vy(b.closeTrackingParams);a.Ce=g.vy(b.iconTrackingParams)},bPa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.I;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.oA(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:d4(a,c,b,d),sponsored:!1,tracking:$3(d,e,d.command),Cl:d.trackingParams?g.vy(d.trackingParams):null,Oi:e.trackingParams?
g.vy(e.trackingParams):null,Ce:f&&f.trackingParams?g.vy(f.trackingParams):null,imageUrl:e4(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.oA(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,jy:null,title:d.title?g.oA(d.title):"",customMessage:d.callToAction?g.oA(d.callToAction):"",url:d.command.urlEndpoint.url?R3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.command.urlEndpoint.url}):null};f4(a,b)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"collaborator",teaserText:g.oA(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:d4(a,c,b,d),sponsored:!1,tracking:$3(d,e,d.endpoint),Cl:d.trackingParams?g.vy(d.trackingParams):null,Oi:e.trackingParams?g.vy(e.trackingParams):null,Ce:f&&f.trackingParams?
g.vy(f.trackingParams):null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.oA(d.customText):null,profileImageUrl:e4(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.oA(d.channelName):"",metaInfo:[d.subscriberCountText?g.oA(d.subscriberCountText):""],url:R3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};
f4(a,b)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"playlist",teaserText:g.oA(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:d4(a,c,b,d),sponsored:!1,tracking:$3(d,e,d.action),Cl:d.trackingParams?g.vy(d.trackingParams):
null,Oi:e.trackingParams?g.vy(e.trackingParams):null,Ce:f&&f.trackingParams?g.vy(f.trackingParams):null,yx:e4(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.oA(d.customMessage):null,playlistVideoCount:g.oA(d.playlistVideoCount),title:d.playlistTitle?g.oA(d.playlistTitle):"",metaInfo:[d.channelName?g.oA(d.channelName):"",d.videoCountText?g.oA(d.videoCountText):""],url:R3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:$Oa(d.action)})};f4(a,b)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.videoInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"video",teaserText:g.oA(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:d4(a,c,b,d),sponsored:!1,tracking:$3(d,e,d.action),Cl:d.trackingParams?g.vy(d.trackingParams):null,Oi:e.trackingParams?g.vy(e.trackingParams):null,Ce:f&&f.trackingParams?g.vy(f.trackingParams):
null,yx:e4(d.videoThumbnail.thumbnails,258).url,videoDuration:d.lengthString?g.oA(d.lengthString):null,customMessage:d.customMessage?g.oA(d.customMessage):null,title:d.videoTitle?g.oA(d.videoTitle):"",metaInfo:[d.channelName?g.oA(d.channelName):"",d.viewCountText?g.oA(d.viewCountText):""],isLiveNow:!!d.badge,url:R3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:$Oa(d.action)})};f4(a,b)}a.I++},e4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===
a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},d4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},dPa=function(a,b){if(b=cPa(a,b))b===a.i&&(a.i=null),a.J.removeCueRange(b.card.id),g.Kg(b.YC),g.Ab(a.cards,b),a.oy(),g4(a)},a4=function(a,b,c){if(!a.B){a.Wa.show();
a.Ka=new g.J(function(){g.M(a.context.J.getRootNode(),g.oT.IV_DRAWER_OPEN)},0);
a.Ka.start();a.va=g.vu(a.u,"mousewheel",function(h){a.Aa.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.u.scrollTop+=h});
a.B=!0;var d=g.Ay();d&&a.Ba&&a.K&&g.Qy(d,[a.Ba,a.K]);b={TRIGGER_TYPE:b};for(var e=g.r(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.HL||(f.HL=!0,ePa(a.context.logger,f.card.tracking.impression,b)),d&&g.Qy(d,[f.card.Cl]);t3(a.J);c&&(a.D=new g.J(function(){a.Ja=a.S;a.ib.focus()},330),a.D.start())}},b4=function(a){a.B&&(a.Wa.hide(),g.wu(a.va),a.va=null,g.Qq(a.context.J.getRootNode(),g.oT.IV_DRAWER_OPEN),a.B=!1,t3(a.J),a.D&&a.D.stop(),a.D=new g.J(function(){a.Ja&&(a.Ja.focus(),a.Ja=null)},330),a.D.start())},
gPa=function(a){g.Pq(a.element,[g.oT.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.MM(a.J,a.C,5);fPa(a);a.S=g.vg("ytp-cards-button",a.J.getRootNode());a.ib=g.vg("iv-drawer-close-button",a.C);a.Yd=!0},fPa=function(a){var b=g.vg("iv-drawer-close-button",a.C);
a.context.i.Ra(b,"click",a.sR,a);a.context.i.Ra(a.u,"touchend",function(){a.Aa.start()});
a.context.i.Ra(a.u,"scroll",a.ER,a);a.context.u.subscribe("onHideControls",function(){a.La=!0});
a.context.u.subscribe("onShowControls",function(){a.La=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.La=g.Oq(a.J.getRootNode(),"ytp-autohide")});
a.ma.push(g.bv("iv-button-shown",a.YS,a));a.ma.push(g.bv("iv-button-hidden",a.XS,a));a.ma.push(g.bv("iv-teaser-shown",a.YP,a));a.ma.push(g.bv("iv-teaser-hidden",a.ZS,a));a.ma.push(g.bv("iv-teaser-clicked",a.XP,a))},f4=function(a,b){a.Yd||gPa(a);
dPa(a,b.id);var c=hPa(a,b);if(c){var d={card:b,YC:c.element,HL:!1},e=iPa(a,d);g.Gb(a.cards,e,0,d);c.Ea(a.u,e);a.oy();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.B||(a.i=d,g4(a),jPa(a,d),a4(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.J.getCurrentTime(),5E3>c&&c>b.startMs&&kPa(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){kPa(a,d)}),g4(a))}},hPa=function(a,b){switch(b.type){case "simple":a=a.Z;
var c=b.displayDomain?{G:"div",L:"iv-card-image-text",xa:b.displayDomain}:void 0;var d=WOa(b);c={G:"div",Ga:["iv-card"],U:[{G:"a",L:"iv-click-target",W:{href:b.url?Q3(b.url)||"":""},U:[V3(b.imageUrl,c),{G:"div",L:"iv-card-content",U:[T3("h2",void 0,b.title),d]}]}]};c=new g.V(c);X3(a,g.ug("iv-click-target",c.element),b,b.url);return c;case "collaborator":return a=a.Z,c={G:"div",Ga:["iv-card","iv-card-channel"],U:[{G:"a",Ga:["iv-click-target"],W:{href:Q3(b.url)||"","data-ytid":b.channelId},U:[V3(b.profileImageUrl),
{G:"div",L:"iv-card-content",U:[U3(b),{G:"h2",L:"iv-card-primary-link",xa:b.title},W3(b)]}]}]},c=new g.V(c),X3(a,g.ug("iv-click-target",c.element),b,b.url),c;case "playlist":return a=a.Z,c={G:"div",Ga:["iv-card","iv-card-playlist"],U:[{G:"a",L:"iv-click-target",W:{href:Q3(b.url)||""},U:[V3(b.yx,{G:"div",L:"iv-card-image-overlay",U:[{G:"span",L:"iv-card-playlist-video-count",xa:b.playlistVideoCount}]}),{G:"div",L:"iv-card-content",U:[U3(b),T3("h2","iv-card-primary-link",b.title),W3(b)]}]}]},c=new g.V(c),
X3(a,g.ug("iv-click-target",c.element),b,b.url),c;case "productListing":a=a.Z;var e=!g.wb(b.offers);c=["iv-card"];d="";var f=WOa(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({G:"div",L:"iv-card-offer-price",xa:f.price}),f.merchant&&e.push({G:"div",L:"iv-card-offer-merchant",xa:f.merchant}),f={G:"div",U:e});e=b.url?Q3(b.url)||"":"";c={G:"div",Ga:c,W:{tabindex:"0"},U:[{G:"a",Ga:["iv-card-image","iv-click-target"],W:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{G:"div",L:"iv-card-content",U:[b.sponsored?{G:"div",L:"iv-card-sponsored",U:["Sponsored",{G:"div",L:"iv-ad-info-container",U:[{G:"div",L:"iv-ad-info",xa:"{{adInfo}}"},{G:"div",L:"iv-ad-info-icon-container",U:[{G:"div",L:"iv-ad-info-icon"},{G:"div",L:"iv-ad-info-callout"}]}]}]}:"",{G:"a",L:"iv-click-target",W:{href:e},U:[T3("h2",d,b.title),f]}]}]};c=new g.V(c);d=g.Gg("span");g.Ng(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.kd(d,"adInfo");X3(a,g.ug("iv-click-target",c.element),b,b.url);return c;case "video":return a=a.Z,d=b.videoDuration?{G:"span",L:"iv-card-video-duration",xa:b.videoDuration}:void 0,f=b.isLiveNow?{G:"span",Ga:["yt-badge","yt-badge-live"],xa:"LIVE NOW"}:null,e={G:"div",Ga:["iv-card","iv-card-video"],U:[{G:"a",L:"iv-click-target",W:{href:(null===(c=b.url)||void 0===c?void 0:Q3(c))||""},U:[V3(b.yx,d),{G:"div",L:"iv-card-content",U:[U3(b),T3("h2","iv-card-primary-link",b.title),W3(b),f]}]}]},c=new g.V(e),
X3(a,g.ug("iv-click-target",c.element),b,b.url),c;default:return null}},iPa=function(a,b){if(0===a.cards.length)return 0;
a=g.tb(a.cards,function(c){return b.card.startMs>c.card.startMs||b.card.startMs===c.card.startMs&&b.card.timestamp>=c.card.timestamp?!0:!1});
return-1===a?0:a+1},lPa=function(a){return a.i?"productListing"===a.i.card.type:g.km(a.cards,function(b){return"productListing"===b.card.type})},g4=function(a){g.N(a.J.getRootNode(),"ytp-cards-shopping-active",lPa(a))},kPa=function(a,b){if(!g.Oq(a.J.getRootNode(),"ytp-cards-teaser-shown")){if(a.i!==b){var c=g.Ay(),d=a.i?a.i.card.Ce:a.Ce;
c&&d&&g.Ry(c,[d]);a.i=b;g4(a)}if(c="none"!=a.element.style.display)a.context.J.V().N("html5_enable_single_video_vod_ivar_on_pacf")||2!==a.context.J.getPresentingPlayerType()?(c=a.context.J.getPlayerState(),d=0===c&&0===a.context.J.getCurrentTime(),c=1===c||3===c||d):c=1===a.context.J.getAdState();c&&b.card.teaserDurationMs&&a.J.qt(!0,{teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs});a.fb.isActive()||((!a.B||!a.Aa.isActive()&&a.La)&&jPa(a,b),a.fb.start(910+b.card.teaserDurationMs))}},
jPa=function(a,b){a.X.zb?(b=new y3([0,
a.u.scrollTop],[0,b.YC.offsetTop],600,xOa),a.context.B.Ra(b,"animate",function(c){a.u.scrollTop=c.y}),a.context.B.Ra(b,"finish",function(c){a.u.scrollTop=c.y}),b.play()):(g.MK(a.X,!0),a.u.scrollTop=b.YC.offsetTop,g.MK(a.X,!1))},h4=function(a){return a.i&&a.i.card?a.i.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},cPa=function(a,b){return g.sb(a.cards,function(c){return c.card.id===b})},i4=function(a,b,c){Y3.call(this,a,b);
this.annotation=c;this.isActive=!1},mPa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},j4=function(a,b,c){i4.call(this,a,b,c);
this.u=null;this.K=!1;this.B=null;this.C=!1;this.i=this.I=this.D=null},nPa=function(a,b){var c=void 0===c?0:c;
var d=vOa(b).width;g.Ol(b,d);c=new A3(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,wOa);g.I(a,c);a.context.B.Ra(c,"begin",function(){g.Xl(b,!0)});
c.play()},qPa=function(a,b){if(b.channel_name){var c=a.createElement({G:"div",
Ga:["iv-branding-context-name"],xa:b.channel_name}),d=a.createElement({G:"div",Ga:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.i=new g.bO(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signInUrl,a.context.J),a.i.Ea(d));var f=a.createElement({G:"div",Ga:["iv-branding-context-subscribe-caret"]}),h=a.createElement({G:"div",Ga:["branding-context-container-inner"]});
h.appendChild(f);h.appendChild(c);h.appendChild(d);g.Xl(h,!1);var l=a.createElement({G:"div",Ga:["branding-context-container-outer"]});l.appendChild(h);g.Hl(l,"right",b.image_width+"px");a.element.appendChild(l);a.B=new g.J(function(){oPa(a,h,l)},500);
g.I(a,a.B);a.context.i.Ra(a.element,"mouseover",function(){pPa(a,h,l,f,b.image_height)});
a.context.i.Ra(a.element,"mouseout",function(){a.B.start()})}},pPa=function(a,b,c,d,e){a.B.stop();
if(!a.C){var f=g.Wl(b);a.i||(b.style.width=g.Nl(f.width,!0),c.style.width=g.Nl(f.width,!0));g.Hl(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.Hl(d,"right","1px");a.C=!0;g.Xl(b,!0);a.D=new g.J(function(){g.M(this.element,"iv-branding-active")},0,a);
a.D.start()}},oPa=function(a,b,c){g.Qq(a.element,"iv-branding-active");
a.I=new g.J(function(){g.Xl(b,!1);a.i||(c.style.width=g.Nl(0,!0))},250);
a.I.start();a.C=!1},rPa=function(a,b,c,d,e,f,h){this.i=a;
this.B=b;this.Y=c;this.videoData=d;this.logger=e;this.J=f;this.u=h},k4=function(a,b,c){i4.call(this,a,b,c);
var d=this;this.S=this.isCollapsed=this.X=!1;this.I=5E3;this.u=this.B=this.i=this.C=null;this.K=this.createElement({G:"div",Ga:["iv-promo-contents"]});this.D=new g.J(function(){d.i.setAttribute("aria-hidden","true");g.Xl(d.B,!1);g.Xl(d.u,!0)},700,this);
g.I(this,this.D)},sPa=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.I=b.collapsedelay_ms||a.I;var d=["iv-promo","iv-promo-inactive"];a.element.setAttribute("aria-hidden","true");a.element.setAttribute("aria-label","Promotion");a.element.tabIndex=0;var e=a.annotation.Wd(),f=b.image_url;if(f){var h=a.createElement({G:"div",Ga:["iv-promo-img","iv-click-target"]});f=a.createElement({G:"img",W:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&
!b.is_live?(f=a.createElement({G:"span",L:"iv-promo-video-duration",xa:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({G:"span",L:"iv-promo-playlist-length",xa:b.playlist_length.toString()}),h.appendChild(f));e&&Z3(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({G:"a",L:"iv-promo-txt"}),g.Uf(f,Q3(e)),a.i=f):a.i=a.createElement({G:"div",L:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({G:"p",U:[{G:"strong",
xa:b.text_line_1}]});var m=a.createElement({G:"p",U:[{G:"span",L:"iv-promo-link",xa:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({G:"button",Ga:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({G:"button",Ga:["iv-button","iv-promo-button"],U:[{G:"span",L:"iv-button-content",xa:f}]});var p=a.createElement({G:"div",L:"iv-promo-button-container"});p.appendChild(f);e&&Z3(a,a.element,e,a.annotation.id,b.session_data,void 0,c)}g.M(a.i,
"iv-click-target");e&&Z3(a,a.i,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({G:"p",U:[{G:"span",xa:b.text_line_1}]}),m=a.createElement({G:"p",U:[{G:"strong",xa:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({G:"span",Ga:["yt-badge","iv-promo-badge-live"],xa:"LIVE NOW"})),g.M(a.i,"iv-click-target"),e&&Z3(a,a.i,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.i.appendChild(l);m&&a.i.appendChild(m);a.K.appendChild(a.i);p&&
a.K.appendChild(p);c=a.createElement({G:"div",L:"iv-promo-actions"});a.u=a.createElement({G:"button",Ga:["iv-promo-expand","ytp-button"]});a.u.title="Expand";a.context.i.Ra(a.u,"click",function(q){l4(a,5E3,q)});
c.appendChild(a.u);g.Xl(a.u,!1);a.context.i.Ra(a.element,"mouseover",a.kS,a);a.context.i.Ra(a.element,"mouseout",a.jS,a);a.context.i.Ra(a.element,"touchend",function(q){l4(a,5E3,q)});
a.B=a.createElement({G:"button",Ga:["iv-promo-close","ytp-button"]});a.B.title="Close";a.context.i.Ra(a.B,"click","cta"===a.annotation.style&&b.text_line_3?a.fS:a.eS,a);c.appendChild(a.B);g.Pq(a.element,d);h&&(a.element.appendChild(h),n&&h.appendChild(n));a.element.appendChild(a.K);a.element.appendChild(c)},l4=function(a,b,c){c.stopPropagation();
tPa(a);uPa(a,b);a.i.focus()},vPa=function(a){a.isCollapsed||a.S||a.C||(g.M(a.element,"iv-promo-collapsed"),a.isCollapsed=!0,a.D.start())},tPa=function(a){a.D.stop();
a.isCollapsed&&(g.Rq(a.element,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.i&&a.i.removeAttribute("aria-hidden"),g.Xl(a.u,!1),g.Xl(a.B,!0))},uPa=function(a,b){a.C||(a.C=g.th(function(){m4(this);
vPa(this)},b,a))},m4=function(a){a.C&&(g.B.clearTimeout(a.C),a.C=null)},wPa=function(a){this.J=a},ePa=function(a,b,c){b&&(c?n4(a,b.map(function(d){return g.yq(d,c)})):n4(a,b))},n4=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.r(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.Vu(m,f);d&&(e++,0!==d&&a.J.sendVideoStatsEngageEvent(d,f))},o4=function(a){g.ZM.call(this,a);
var b=this;this.X=!1;this.loadNumber=0;this.K={};this.logger=new wPa(this.player);this.D=new g.qD(this);this.I=this.B=null;this.events=new g.qD(this);this.S=this.i=null;this.ma=[];g.I(this,this.D);this.D.T(this.player,"onVideoAreaChange",function(){b.ea("onVideoAreaChange")});
this.D.T(this.player,"onHideControls",function(){b.ea("onHideControls")});
this.D.T(this.player,"onShowControls",function(){b.ea("onShowControls")});
this.D.T(this.player,"resize",function(d){b.ea("resize",d)});
this.D.T(this.player,"presentingplayerstatechange",function(d){b.ea("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.ZP,this);this.subscribe("resize",this.iA,this);this.player.V().S.subscribe("vast_info_card_add",this.WM,this);g.I(this,this.events);this.Z=this.createElement({G:"div",L:"video-custom-annotations"});this.u=new g.V({G:"div",Ga:["ytp-player-content","ytp-iv-player-content"]});g.I(this,this.u);g.MM(this.player,this.u.element,4);this.u.hide();this.C=new g.V({G:"div",Ga:["ytp-iv-video-content"]});g.I(this,this.C);a=this.createElement({G:"div",L:"video-annotations"});
a.appendChild(this.Z);this.C.element.appendChild(a);this.Cq()&&this.load();var c=this.createElement({G:"style"});(g.sg("HEAD")[0]||document.body).appendChild(c);g.xe(this,function(){g.Kg(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},xPa=function(a){a=a.createElement({G:"div",
Ga:["annotation","annotation-type-custom"]});g.Xl(a,!1);return a},yPa=function(a,b){b=!b.isCued()&&!g.U(b,1024);
g.MK(a.u,b);g.MK(a.C,b)},zPa=function(a,b,c){a.X=!0;
a.I=g.wt(b,c)},APa=function(a,b){for(var c={},d=g.r(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Ma(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(APa(a,e))}return c},DPa=function(a){var b=a.player.getVideoData();
if(b.Va){var c=a.player.V().S.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.Ws(h)&&h.responseXML?h.responseXML:null)&&p4(a,h)}};
g.Mu()&&(d.onFinish=BPa(a,d.onFinish));d.postParams={ic_only:"1"};CPa(d,c);a.X=!0;g.wt(b.Va,d)}}},CPa=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.Ru&&(a.postParams.ic_coll=b.Ru);b.vy&&(a.postParams.ic_xml=b.vy);b.Bx&&(a.postParams.ic_track=b.Bx)},EPa=function(a){var b=new g.V({G:"div"});
g.Xl(b.element,!1);var c=new c4(a.player,b.element,q4(a));g.I(c,b);b.Ea(a.u.element);c.hx();return c},q4=function(a){if(!a.S){var b=new B3(a);
g.I(a,b);var c=new g.Xj(a);g.I(a,c);a.S=new rPa(b,c,a.player.V(),a.player.getVideoData(),a.logger,a.player,a.le)}return a.S},p4=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.Ay();if(e){var f=g.zy();f&&g.My(void 0,e,f,[g.vy(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=APa(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=P3(f.type,FPa),p=P3(f.style,GPa),q=NOa(f.data),t=0!==q.length?JSON.parse(q):{};var u=f.action;f=TOa;if(null==u)var x=null;else if(g.La(u)){l=[];for(var y=g.r(u),z=y.next();!z.done;z=y.next()){var G=f(z.value);
G&&l.push(G)}x=l}else{var E=f(u);x=E?[E]:[]}e=m&&n?new S3(m,n,p,x,t):null}else e=null}catch(ia){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var C=xPa(f),L=null;switch(l.type){case "branding":if(f.player.V().Cb)break;f.u.element.appendChild(C);L=new j4(C,q4(f),l);break;case "promotion":g.MM(f.player,C,4),L=new k4(C,q4(f),l)}L&&L.hx();if(f=L)g.I(a,f),a.K[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.i||(a.i=EPa(a),g.I(a,a.i));if("card"===e.type){c=a.i;var S=e&&e.data&&e.data.card_type;
f=e.data;if(S)switch(l=f.tracking||{},l={impression:l.impression,click:l.click,close:l.close,fO:l.teaser_impression,fB:l.teaser_click},C=f.tracking_params||{},L=null,S){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Cl:C.card?g.vy(C.card):null,Oi:C.teaser?g.vy(C.teaser):null,Ce:C.icon?g.vy(C.icon):null,
channelId:f.channel_id,customMessage:f.custom_message?f.custom_message:null,profileImageUrl:f.image_url,title:f.title,metaInfo:f.meta_info,url:R3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};f4(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Cl:C.card?g.vy(C.card):
null,Oi:C.teaser?g.vy(C.teaser):null,Ce:C.icon?g.vy(C.icon):null,yx:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:R3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};f4(c,e);break;case "productListing":f.signin_url&&(L=R3({target:"current",value:f.signin_url}));S=[];for(var K=f.offers||[],W=0;W<K.length;W++)S.push(new XOa(g.ig(K[W].merchant),g.ig(K[W].price)));e={id:e.id,
timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Cl:C.card?g.vy(C.card):null,Oi:C.teaser?g.vy(C.teaser):null,Ce:C.icon?g.vy(C.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,jy:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:
null,url:R3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),Fba:L,Eba:f.signin_title?f.signin_title:void 0,Dba:f.signin_message?f.signin_message:void 0,offers:S};f4(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Cl:C.card?g.vy(C.card):null,Oi:C.teaser?g.vy(C.teaser):
null,Ce:C.icon?g.vy(C.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,jy:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:R3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};f4(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||
!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Cl:C.card?g.vy(C.card):null,Oi:C.teaser?g.vy(C.teaser):null,Ce:C.icon?g.vy(C.icon):null,yx:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:R3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})},f4(c,e)}}else aPa(a.i,e);c=!0}}c&&(t3(a.player),a.iA())},HPa=function(a,b){var c=!1;
a.i||(a.i=EPa(a),g.I(a,a.i));for(var d=g.r(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(bPa(a.i,e.cardRenderer),c=!0);c&&(c=a.i,d=b.headerText?g.oA(b.headerText):"",g.Ng(c.ob,d),c.S&&c.S.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ba=b.trackingParams?g.vy(b.trackingParams):null,c.K=b.closeButton.infoCardIconRenderer.trackingParams?g.vy(b.closeButton.infoCardIconRenderer.trackingParams):null,c.Ce=b.icon.infoCardIconRenderer.trackingParams?
g.vy(b.icon.infoCardIconRenderer.trackingParams):null,t3(a.player),a.iA())},IPa=function(a,b,c,d,e){if(!a.player.V().Cb){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new QOa("openUrl","click",new OOa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;var l;b=b.subscribeButton.subscribeButtonRenderer;var m,n;h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.oA(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.oA(b.subscriberCountText))):(b.subscriberCountText&&(e=g.oA(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.oA(b.subscriberCountWithSubscribeText)));var p=b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url?b.signInEndpoint.webNavigationEndpointData.url:(null===(n=null===(m=null===(l=b.signInEndpoint)||void 0===l?void 0:l.commandMetadata)||void 0===m?void 0:m.webCommandMetadata)||void 0===n?void 0:n.url)||"";l={subscribeText:g.oA(b.unsubscribedButtonText),subscribeCount:e||"",unsubscribeText:g.oA(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:p};d.standalone_subscribe_button_data=
l}f=new S3(c,"branding","branding",f,d);l=xPa(a);a.u.element.appendChild(l);f=new j4(l,q4(a),f);f.hx();g.I(f,f);a.K[c]=f}},BPa=function(a,b){return function(c){for(var d=[],e=0;e<arguments.length;++e)d[e-0]=arguments[e];
a.isDisposed()||a.ma.push(g.Su.Pf(function(){b.apply(null,g.ma(d))}))}},JPa=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.FM.prototype.qt=g.ca(17,function(a,b){var c=g.nN(this.vb());c&&c.qt(a,b)});
var v3={},w3=null;g.Ra(y3,g.br);g.k=y3.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.i)this.progress=0,this.coords=this.u;else if(this.Dc())return!1;x3(this);this.startTime=a=g.Qa();-1==this.i&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.fA();this.ni("play");-1==this.i&&this.ni("resume");this.i=1;var b=g.Oa(this);b in v3||(v3[b]=this);zOa();AOa(this,a);return!0};
g.k.stop=function(a){x3(this);this.i=0;a&&(this.progress=1);BOa(this,this.progress);this.ni("stop");this.Cw()};
g.k.pause=function(){this.Dc()&&(x3(this),this.i=-1,this.ni("pause"))};
g.k.ya=function(){0==this.i||this.stop(!1);this.ni("destroy");y3.je.ya.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.fC=function(){this.ni("animate")};
g.k.ni=function(a){this.dispatchEvent(new COa(a,this))};
g.Ra(COa,g.ye);g.Ra(z3,y3);z3.prototype.C=g.Ia;z3.prototype.fC=function(){this.C();z3.je.fC.call(this)};
z3.prototype.Cw=function(){this.C();z3.je.Cw.call(this)};
z3.prototype.fA=function(){this.C();z3.je.fA.call(this)};
g.Ra(A3,z3);A3.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.v(B3,g.H);B3.prototype.Ra=function(a,b,c,d){c=(0,g.D)(c,d||this.u);a=g.vu(a,b,c);this.i.push(a);return a};
B3.prototype.Mz=function(a,b,c,d){c=(0,g.D)(c,d||this.u);a=g.Eu(a,b,c);this.i.push(a);return a};
B3.prototype.hc=function(a){g.wu(a);g.Ab(this.i,a)};
B3.prototype.ya=function(){g.wu(this.i);this.i.length=0;g.H.prototype.ya.call(this)};g.v(F3,g.ZM);g.k=F3.prototype;g.k.load=function(){g.ZM.prototype.load.call(this);if(!G3(this)){var a=g.xpa(this.player.getVideoData());a?(a=E3(a,EOa(this)),H3(this,a,!1)):FOa(this)}};
g.k.unload=function(){H3(this,null);this.B&&(this.B.abort(),this.B=null);g.ZM.prototype.unload.call(this)};
g.k.jf=function(a,b){return G3(this)?"loadCustomEndscreenRenderer"===a?(a=E3(b,"new"),H3(this,a),!0):null:null};
g.k.getOptions=function(){return G3(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.wb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<KPa.length;f++){var h=Math.abs(b.width-KPa[f]);if(-1===e||d>=h)e=f,d=h}d=LPa[e];this.u&&g.Hl(this.u.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.i[f],
h=this.D[f],e&&h){var l=h.width*c/h.aspectRatio;f=Math.round(l*a.height);var m=a.left+Math.round(h.left*a.width),n=a.top+Math.round(h.top*a.height);g.Vl(e.element,Math.round(h.width*a.width),f);g.Ol(e.element,m,n);g.Rq(e.element,MPa);m=h.left+h.width/2;h=h.top+l/2;g.M(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Rq(e.element,LPa);g.M(e.element,d);(e=g.tg(document,"div","ytp-ce-expanding-overlay-body",
e.element)[0])&&g.Hl(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())O3(this,this.endscreen.impressionUrls),(a=g.Ay())&&this.endscreen.visualElement&&g.Ny(a,this.endscreen.visualElement,void 0);else{a=a.getId().substring(15);var b=this.i[a],c=this.D[a];g.M(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.M(b,"ytp-ce-shown");O3(this,c.impressionUrls);(b=g.Ay())&&g.Ny(b,c.visualElement,void 0);this.player.V().u&&this.player.Na("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.i[a];g.Qq(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.Qq(b,"ytp-ce-shown");this.player.V().u&&this.player.Na("endscreenelementhidden",a)}};
g.k.yW=function(a){var b=this;a.target===window&&(new g.J(function(){for(var c=g.r(Object.values(b.i)),d=c.next();!d.done;d=c.next())g.Rq(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var KPa=[346,426,470,506,570,640,853,1280,1920],LPa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),MPa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var POa={l1:"current",c7:"new"};var ROa={CLOSE:"close",v7:"openUrl",SUBSCRIBE:"subscribe"},SOa={xZ:"click",CLOSE:"close",O2:"hidden",U8:"rollOut",V8:"rollOver",K9:"shown"};S3.prototype.Wd=function(){var a=UOa(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var GPa={QY:"anchored",TO:"branding",CHANNEL:"channel",j1:"cta",R2:"highlightText",S3:"label",PLAYLIST:"playlist",n8:"popup",T9:"speech",SUBSCRIBE:"subscribe",l$:"title",VIDEO:"video",xaa:"website"},FPa={TO:"branding",kZ:"card",F1:"drawer",Q2:"highlight",v5:"marker",x8:"promotion",TEXT:"text",Daa:"widget"};g.v(Y3,g.H);g.k=Y3.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.hA(a,b,{id:c,namespace:"annotations_module"});d&&this.Pa.set(a,d);e&&this.Va.set(a,e);this.context.J.Ad([a])};
g.k.hx=function(){this.context.u.subscribe("resize",this.oy,this)};
g.k.gC=function(a,b,c,d,e,f){if(this.Za)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.Kg(this.element)};
g.k.oy=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=Q3(a);if(f){var h=ZOa(f,a.target),l=function(){a.i&&e.context.J.pauseVideo();var m=e.context.videoData.D||!1,n=g.Ks(f||"");m&&n&&(n.v||n.list)?e.context.J.Oj(n.v,b,n.list,!1):g.VL(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);n4(this.context.logger,c,l,d);YOa(f)||(c=g.Ay(),d=b.itct,c&&d&&g.Sy(c,g.vy(d)))}};
g.k.ya=function(){this.Pa.clear();this.Va.clear();g.H.prototype.ya.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.I(this,a);return a.element};g.v(c4,Y3);g.k=c4.prototype;g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.J.getRootNode())?(a=g.Wl(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.oy=function(){var a=this.isAvailable();g.Xl(this.element,a);g.N(this.context.J.getRootNode(),g.oT.IV_DRAWER_ENABLED,a);t3(this.J)};
g.k.destroy=function(){this.J.qt(!1);try{this.J.getRootNode().removeChild(this.C)}catch(a){}g.cv(this.ma);g.wu(this.va);this.Ka&&this.Ka.dispose();this.D&&this.D.dispose();Y3.prototype.destroy.call(this)};
g.k.sR=function(){if(this.B){n4(this.context.logger,h4(this).tracking.close);var a=g.Ay();a&&this.K&&g.Sy(a,this.K);b4(this)}};
g.k.ER=function(){g.N(this.C,"iv-drawer-scrolled",0<this.u.scrollTop)};
g.k.YS=function(){var a=g.Ay(),b=h4(this);b=b?b.Ce:this.Ce;a&&b&&g.Qy(a,[b])};
g.k.XS=function(){var a=g.Ay(),b=h4(this);b=b?b.Ce:this.Ce;a&&b&&g.Ry(a,[b])};
g.k.YP=function(){var a=h4(this);n4(this.context.logger,a.tracking.fO);var b=g.Ay();b&&a&&g.Qy(b,[a.Oi,a.Ce])};
g.k.ZS=function(){var a=g.Ay(),b=h4(this);a&&b&&g.Ry(a,[b.Oi])};
g.k.XP=function(a){var b=h4(this),c=g.Ay();this.i?a?(a=this.context.logger,n4(a,b.tracking.fB),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Oi&&g.Sy(c,b.Oi)):(a=this.context.logger,n4(a,b.tracking.fB),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Ce&&g.Sy(c,b.Ce)):(a=this.context.logger,n4(a,b.tracking.fB),a.J.sendVideoStatsEngageEvent(4,void 0),c&&this.Ce&&g.Sy(c,this.Ce))};g.v(i4,Y3);i4.prototype.hx=function(){Y3.prototype.hx.call(this);mPa(this)};
i4.prototype.show=function(){Y3.prototype.show.call(this);var a=g.Ay(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Qy(a,[g.vy(b.itct)])};
i4.prototype.hide=function(){Y3.prototype.hide.call(this);var a=g.Ay(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Ry(a,[g.vy(b.itct)])};g.v(j4,i4);
j4.prototype.show=function(){if(!this.isActive){i4.prototype.show.call(this);if(!this.K){g.M(this.element,"iv-branding");var a=this.annotation.data;this.u=this.createElement({G:"img",Ga:["branding-img","iv-click-target"],W:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.Xl(this.u,!1);var b=this.createElement({G:"div",Ga:["branding-img-container"]});b.appendChild(this.u);this.element.appendChild(b);(b=this.annotation.Wd())&&Z3(this,this.u,b,this.annotation.id,
a.session_data);qPa(this,a);this.K=!0}g.Xl(this.element,!0);this.isActive=!0;this.u&&nPa(this,this.u)}};
j4.prototype.hide=function(){this.isActive&&(i4.prototype.hide.call(this),g.Xl(this.element,!1),this.isActive=!1)};
j4.prototype.destroy=function(){this.i&&(this.i.dispose(),this.i=null);i4.prototype.destroy.call(this)};g.v(k4,i4);g.k=k4.prototype;g.k.show=function(){this.isActive||(i4.prototype.show.call(this),this.X||(sPa(this),this.X=!0),g.Xl(this.element,!0),g.th(function(){g.Qq(this.element,"iv-promo-inactive")},100,this),this.element.removeAttribute("aria-hidden"),this.isActive=!0,m4(this),tPa(this),uPa(this,this.I))};
g.k.hide=function(){this.isActive&&(g.M(this.element,"iv-promo-inactive"),this.isActive=!1,this.element.setAttribute("aria-hidden","true"))};
g.k.gC=function(a,b,c,d,e,f){return this.isCollapsed?!1:i4.prototype.gC.call(this,a,b,c,d,e,f)};
g.k.kS=function(a){this.S=!0;l4(this,500,a)};
g.k.jS=function(){this.S=!1;vPa(this)};
g.k.eS=function(a){a.stopPropagation();this.hide()};
g.k.fS=function(a){a.stopPropagation();m4(this);this.isCollapsed=!0;g.M(this.element,"iv-promo-collapsed-no-delay");this.D.start()};
g.k.destroy=function(){this.D.dispose();i4.prototype.destroy.call(this)};g.v(o4,g.ZM);g.k=o4.prototype;g.k.jf=function(a,b){if(!JPa(this.player.V().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.U1(b))&&p4(this,a),!0;case "removeCustomAnnotationById":return b&&this.i&&(dPa(this.i,b),t3(this.player)),!0}return null};
g.k.getOptions=function(){return JPa(this.player.V().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Cq=function(){var a=this.player.V(),b=this.player.getVideoData();return b.D&&a.pfpChazalUi?!1:1===(a.annotationsLoadPolicy||b.annotationsLoadPolicy)&&!b.QK||a.S.get(b.videoId)||g.NG(b)||g.OG(b)?!0:!1};
g.k.iA=function(){if(this.C){var a=this.player.bb().getVideoContentRect(!0);g.Vl(this.C.element,a.width,a.height);g.Ol(this.C.element,a.left,a.top)}if(this.i){var b=this.player.jj();a=this.i;b=b.width;g.N(a.C,"iv-drawer-small",426>=b);g.N(a.C,"iv-drawer-big",1280<=b)}};
g.k.ZP=function(a){yPa(this,a.state);g.U(a.state,2)&&(this.yh()&&this.pk()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.qt(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.I=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.Ws(h)&&h.responseXML?h.responseXML:null)&&(p4(b,h),g.M(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.ZM.prototype.load.call(this);yPa(this,this.player.xb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.Mu()&&(a=BPa(this,a));var e={format:"XML",onFinish:a,onError:function(){b.I=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.V().S.get(d);f&&CPa(e,f);f=f&&(f.vy||f.Ru);if(!c.Vo||f)c.Va?zPa(this,c.Va,e):(this.B=function(){b.onVideoDataChange(e)},this.player.addEventListener("videodatachange",this.B));
g.MM(this.player,this.C.element,4);this.iA();(f=g.NG(c))&&HPa(this,f);(f=g.OG(c))&&f.featuredChannel&&IPa(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Va&&(this.B&&(this.player.removeEventListener("videodatachange",this.B),this.B=null),zPa(this,b.Va,a))};
g.k.unload=function(){this.player.Xe("annotations_module");for(var a=g.r(Object.keys(this.K)),b=a.next();!b.done;b=a.next())this.K[b.value].destroy();this.S=null;this.i&&(this.i.destroy(),this.i=null,t3(this.player));this.X=!1;this.I&&(this.I.abort(),this.I=null);this.K={};this.u.hide();g.ZM.prototype.unload.call(this);this.C.detach();this.B&&(this.player.removeEventListener("videodatachange",this.B),this.B=null)};
g.k.WM=function(a){a===this.player.getVideoData().videoId&&(this.loaded?DPa(this):this.load())};
g.k.yh=function(){return!!this.i&&this.i.isAvailable()};
g.k.pk=function(){this.yh();return!!this.i&&this.i.B};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.yh();this.i&&(a?c?a4(this.i,c,b):a4(this.i,"YOUTUBE_DRAWER_AUTO_OPEN",b):b4(this.i))};
g.k.qt=function(a,b){this.player.ea(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.ya=function(){this.player.V().S.unsubscribe("vast_info_card_add",this.WM,this);g.Qq(this.player.getRootNode(),g.oT.IV_DRAWER_OPEN);for(var a=this.ma,b=0,c=a.length;b<c;b++)g.Su.gi(a[b]);this.ma.length=0;g.ZM.prototype.ya.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.I(this,a);return a.element};g.YM("annotations_module",o4);g.YM("creatorendscreen",F3);})(_yt_player);
