(function(g){var window=this;'use strict';var u4=function(a,b){return b?a.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},v4=function(a){return g.rF(a)&&a.N("web_player_i_see_captions_3")},NPa=function(a,b){return g.F(this,function d(){var e,f,h;
return g.A(d,function(l){if(1==l.i)return e=a+"|"+b,g.w(l,g.$w(),2);if(3!=l.i){f=l.u;if(!f)throw g.hw("gct");return g.w(l,(0,g.TF)(f),3)}h=l.u;return l.return(h.get("captions",e))})})},OPa=function(a,b){var c=new g.WF;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.kind=a.kind;c.isDefault=!1;c.i=a.i;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;return c},PPa=function(a,b,c){NPa(a,b).then(function(d){d&&c(d.trackData,new g.WF(d.metadata))})},w4=function(){this.segments=[]},QPa=function(a,b){var c=g.Jb(a.segments,b);
0<=c||0>c&&1===(-c-1)%2||(c=-c-1,0<c&&1===b-a.segments[c-1]&&c<a.segments.length&&1===a.segments[c]-b?(g.yb(a.segments,c),g.yb(a.segments,c-1)):0<c&&1===b-a.segments[c-1]?a.segments[c-1]=b:c<a.segments.length&&1===a.segments[c]-b?a.segments[c]=b:(g.Gb(a.segments,c,0,b),g.Gb(a.segments,c+1,0,b)))},x4=function(a,b,c,d,e,f){g.H.call(this);
this.policy=a;this.player=b;this.ma=c;this.S=d;this.D=e;this.X=f;this.Y=this.player.V();this.C=new w4;this.I=-1;this.B=this.u=this.i=null;this.K=new g.J(this.EL,1E3,this);this.events=new g.qD(this);g.I(this,this.K);g.I(this,this.events);this.events.T(b,"SEEK_COMPLETE",this.kA);this.kA();this.EL()},RPa=function(a){return a.i&&a.i.D?a.i.D+a.player.Tc()<a.player.getCurrentTime():!1},SPa=function(a,b){var c=g.GC(b,a.policy,{}).Wd(),d={format:"RAW",
withCredentials:!0};a.D&&(d.responseType="arraybuffer");a.B=g.kh(g.Ct(c,d,3,100).then(function(e){a:{e=e.xhr;a.isDisposed();if(a.u){var f=!(a.D?e.response:e.responseText)||400<=e.status,h=g.$la(e);if(h){e=g.GC(a.u,a.policy,{});a.u.mj(e,h);SPa(a,a.u);break a}f||(h=a.u.i[0].Ma,null!=a.S&&a.I!==h&&(f=a.u.i[0],a.D?a.S(e.response,1E3*(f.startTime+a.player.Tc())):a.S(e.responseText,1E3*(f.startTime+a.player.Tc())),a.I=h))}a.u=null;a.B=null}}),function(){a.u=null;
a.B=null;a.oa()});
a.u=b;QPa(a.C,a.u.i[0].Ma)},y4=function(a,b){g.bN.call(this,b.V());
this.i=a;this.J=b;this.B=null;this.D=!1;this.I=g.tF(this.J.V())&&!this.i.isManifestless},UPa=function(a,b){var c=[],d;
for(d in a.i.i)if(a.i.i.hasOwnProperty(d)){var e=a.i.i[d];if(g.dN(e,b||null)){var f=e.info.id,h=f,l="."+f,m="";if(e=e.info.captionTrack)f=e.languageCode,h=e.displayName,l=e.vssId,m=e.kind;else{e=f;var n=g.aOa.get(e);null==n&&(n=TPa[e]||TPa[e.replace(/-/g,"_")],g.aOa.set(e,n));h=n||h}c.push(new g.WF({id:d,languageCode:f,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},VPa=function(a,b){return null!=b&&b in a.i.i?a.i.i[b]:null},WPa=function(a,b,c){var d=
[],e;
for(e in a.i.i)if(a.i.i.hasOwnProperty(e)){var f=a.i.i[e];if(g.dN(f,c||null)){var h=f.info.captionTrack;h&&h.languageCode===b&&d.push(f)}}return d.length?d[0]:null},z4=function(a){if(!XPa.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(YPa,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.substr(1),16);return[a>>16,a>>8&255,a&255]},A4=function(a,b,c,d,e,f){var h={};
Object.assign(h,b);Object.assign(h,a.params);Object.assign(h,c);var l={};Object.assign(l,b.ld);a.params.ld&&Object.assign(l,a.params.ld);Object.assign(l,c.ld);h.ld=l;g.V.call(this,{G:"div",L:"caption-window",W:{id:"caption-window-"+a.id,dir:1===h.Kf?"rtl":"ltr",tabindex:"0",lang:h.lang},U:[{G:"span",L:"captions-text",W:{style:"word-wrap: normal; display: block;"}}]});this.D=[];this.va=!1;this.u=a;this.Ba=this.Aa=null;this.playerWidth=e;this.playerHeight=f;this.I=null;this.maxWidth=.96*e;this.Va=.96*
f;this.i=h;this.yb=c;this.Ja=b;this.C=this.Fa("captions-text");this.kb=""!==this.C.style.getPropertyValue("box-decoration-break")||""!==this.C.style.getPropertyValue("-webkit-box-decoration-break");this.La=d/360*16;this.type=0;this.Wa=this.La*ZPa(l);a=new g.my(this.element,!0);g.I(this,a);a.subscribe("dragstart",this.cQ,this);a.subscribe("dragmove",this.bQ,this);a.subscribe("dragend",this.aQ,this);this.ib=this.Za=0;b="";this.i.windowOpacity&&(a=z4(this.i.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+
","+this.i.windowOpacity+")");a={"background-color":b,display:!1===this.i.isVisible?"none":"","text-align":$Pa[this.i.textAlign]};this.kb&&(a["border-radius"]=b?this.Wa/8+"px":"");if(this.B=2===this.u.params.Kf||3===this.u.params.Kf)b=this.element,c="vertical-rl",1===this.i.EG&&(c="vertical-lr"),g.Tc&&(c="vertical-lr"===c?"tb-lr":"tb-rl"),g.Hl(b,"-o-writing-mode",c),g.Hl(b,"-webkit-writing-mode",c),g.Hl(b,"writing-mode",c),g.Hl(b,"text-orientation","upright"),g.M(b,"ytp-vertical-caption"),3===this.u.params.Kf&&
(g.Hl(b,"text-orientation",""),g.Hl(b,"transform","rotate(180deg)"));g.Hl(this.element,a);switch(this.i.di){case 0:case 1:case 2:g.M(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.M(this.element,"ytp-caption-window-bottom")}},ZPa=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0===a.offset||2===a.offset)b*=.8;return b},aQa=function(a,b){var c={},d=b.background?b.background:a.i.ld.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.i.ld.backgroundOpacity;d=z4(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.kb&&(c["box-decoration-break"]="clone",c["border-radius"]=a.Wa/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.La*ZPa(b)+"px";d=1;e=b.color||a.i.ld.color;if(b.color||null!=b.textOpacity)e=z4(e),d=null==b.textOpacity?a.i.ld.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=
e,c.fill=e;var f=b.charEdgeStyle;0===f&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var h="rgba(204, 204, 204, "+d+")";b.bD&&(h=e=b.bD);var l=a.La/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),q=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=q;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+h);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+n+"px "+
e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.Rt()?'"Carrois Gothic SC", sans-serif-smallcaps':
'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.i.ld.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7===b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.qj&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]="underline");
b.DS&&(c.visibility="hidden");1===b.RK&&a.B&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.xF||g.Si,3===a.u.params.Kf?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1===b.Jj||2===b.Jj||3===b.Jj||4===b.Jj||5===b.Jj)if(g.xF)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.Jj){case 4:case 3:c["text-emphasis-position"]="under left";
c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},bQa=function(a){a.I=g.Gg("SPAN");
g.Hl(a.I,{display:"block"});g.M(a.I,"caption-visual-line");a.C.appendChild(a.I)},cQa=function(a,b){var c=g.Gg("SPAN");
g.Hl(c,{display:"inline-block","white-space":"pre-wrap"});g.Hl(c,aQa(a,b));c.classList.add("ytp-caption-segment");a.I.appendChild(c);c.previousElementSibling&&(g.Hl(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.Hl(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},dQa=function(a,b,c){a.va=a.va||!!c;
var d={};Object.assign(d,a.i.ld);Object.assign(d,c||b.i);Object.assign(d,a.yb.ld);(c=!a.I)&&bQa(a);for(var e=a.Aa&&a.Ba&&g.rc(d,a.Ba)?a.Aa:cQa(a,d),f="string"===typeof b.text,h=f?b.text.split("\n"):[b.text],l=0;l<h.length;l++){var m=0<l||!b.append,n=h[l];m&&!c?(bQa(a),e=cQa(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.Hg(n):n),f||"RUBY"!==n.tagName||4!==n.childElementCount||g.xF||!g.Kl(n.children[2],"text-emphasis")||(m=a.B?"padding-right":"padding-top",g.Kl(n.children[2],"text-emphasis-position")&&(m=
a.B?"padding-left":"padding-bottom"),g.Bg?g.Hl(e,m,"1em"):g.Hl(e,m,"0.5em")))}a.Ba=d;a.Aa=e;a.D.push(b)},B4=function(a,b,c,d){g.bN.call(this,a);
this.videoData=b;this.audioTrack=c;this.Ta=d;this.C=b.CD},C4=function(a,b,c,d,e,f,h){A4.call(this,a,b,c,d,e,f,h);
this.type=1},D4=function(a,b,c,d,e,f,h){A4.call(this,a,b,c,d,e,f,h);
this.type=2;this.K=[];this.X=this.S=this.Ka=0;this.Z=NaN;this.ob=0;this.ub=null;this.Pa=new g.J(this.CV,433,this);g.M(this.element,"ytp-caption-window-rollup");g.I(this,this.Pa);g.Hl(this.element,"overflow","hidden")},eQa=function(a,b){if(!b)return"";
a.B&&1!==a.u.params.EG&&(b*=-1);return"translate"+(a.B?"X":"Y")+"("+b+"px)"},fQa=function(a){a.K=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.u.params.tm,c=0,d=0,e=a.K.length-1;c<b&&-1<e;){var f=a.K[e];d+=a.B?f.offsetWidth:f.offsetHeight;c++;e--}a.K.length<b&&(d*=b/a.K.length);a.S=d;b=Math;c=b.max;isNaN(a.Z)&&((d=a.i.Tm)?(e=g.Gg("SPAN"),g.Ng(e,"\u2013".repeat(d)),g.Hl(e,aQa(a,a.i.ld)),a.C.appendChild(e),a.Z=e.offsetWidth,a.C.removeChild(e)):a.Z=0);d=a.C;a.X=c.call(b,a.Z,a.ob,(a.B?d.offsetHeight:d.offsetWidth)+1)},gQa=function(a,b){fQa(a);
var c=a.K.reduce(function(e,f){return(a.B?f.offsetWidth:f.offsetHeight)+e},0);
c=a.S-c;if(c!==a.Ka){var d=0<c&&0===a.Ka;b||isNaN(c)||d||(g.M(a.element,"ytp-rollup-mode"),g.Hq(a.Pa));g.Hl(a.C,"transform",eQa(a,c));a.Ka=c}fQa(a)},E4=function(a,b,c,d,e,f,h){f=void 0===f?!1:f;
h=void 0===h?null:h;g.hA.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.i=h},F4=function(a,b,c,d,e){g.hA.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.i=[]},hQa=function(a){var b="_"+G4++;
return new F4(0,0x8000000000000,0,b,a)},jQa=function(a,b,c,d,e,f,h){var l=f[0],m=h[l.getAttribute("p")];
if(1===m.Zd){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");h=h[p.getAttribute("p")];l=iQa(l.textContent,n.textContent,p.textContent,f.textContent,h);return new E4(a,b,e,c,l,d,m)}switch(m.Zd){case 9:case 10:m.Jj=1;break;case 11:m.Jj=2;break;case 12:m.Jj=3;break;case 13:m.Jj=4;break;case 14:m.Jj=5}return new E4(a,b,e,c,l.textContent||"",d,m)},iQa=function(a,b,c,d,e){var f=g.Rt(),h=
f?g.Gg("DIV"):g.Gg("RUBY"),l=g.Gg("SPAN");
l.textContent=a;h.appendChild(l);a=f?g.Gg("DIV"):g.Gg("RP");a.textContent=b;h.appendChild(a);b=f?g.Gg("DIV"):g.Gg("RT");b.textContent=c;h.appendChild(b);c=e.Zd;if(10===c||11===c||12===c||13===c||14===c)if(g.Hl(b,"text-emphasis-style","filled circle"),g.Hl(b,"text-emphasis-color","currentcolor"),g.Hl(b,"webkit-text-emphasis","filled circle"),11===e.Zd||13===e.Zd)g.Hl(b,"webkit-text-emphasis-position","under left"),g.Hl(b,"text-emphasis-position","under left");c=!0;if(4===e.Zd||7===e.Zd||12===e.Zd||
14===e.Zd)g.Hl(h,"ruby-position","over"),g.Hl(h,"-webkit-ruby-position","before");else if(5===e.Zd||6===e.Zd||11===e.Zd||13===e.Zd)g.Hl(h,"ruby-position","under"),g.Hl(h,"-webkit-ruby-position","after"),c=!1;e=f?g.Gg("DIV"):g.Gg("RP");e.textContent=d;h.appendChild(e);f&&(d=c,g.Hl(h,{display:"inline-block",position:"relative"}),f=h.firstElementChild.nextElementSibling,g.Hl(f,"display","none"),f=f.nextElementSibling,g.Hl(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.Hl(h.lastElementChild,"display","none"),d?(g.Hl(h,"padding-top","0.6em"),g.Hl(f,"top","0")):(g.Hl(h,"padding-bottom","0.6em"),g.Hl(f,"bottom","0")));return h},H4=function(){g.H.apply(this,arguments)},I4=function(a){H4.call(this);
this.C=a;this.pens={};this.S={};this.X={};this.D="_"+G4++;this.K={};this.B=this.i=null;this.I=!0},J4=function(a,b){a=a.getAttribute(b);
if(null!=a)return Number(a)},K4=function(a,b){a=a.getAttribute(b);
if(null!=a)return"1"===a},L4=function(a,b){a=J4(a,b);
return void 0!==a?a:null},N4=function(a,b){a=a.getAttribute(b);
if(null!=a)return M4.test(a),a},kQa=function(a,b){var c={},d=b.getAttribute("ws");
Object.assign(c,d?a.X[d]:a.C);a=L4(b,"mh");null!=a&&(c.Os=a);a=L4(b,"ju");null!=a&&(c.textAlign=a);a=L4(b,"pd");null!=a&&(c.Kf=a);a=L4(b,"sd");null!=a&&(c.EG=a);a=N4(b,"wfc");null!=a&&(c.windowColor=a);b=J4(b,"wfo");void 0!==b&&(c.windowOpacity=b/255);return c},lQa=function(a,b){var c={},d=b.getAttribute("wp");
d&&Object.assign(c,a.S[d]);a=L4(b,"ap");null!=a&&(c.di=a);a=J4(b,"cc");null!=a&&(c.Tm=a);a=J4(b,"ah");null!=a&&(c.eh=a);a=J4(b,"rc");null!=a&&(c.tm=a);b=J4(b,"av");null!=b&&(c.Kj=b);return c},mQa=function(a,b,c,d){var e={};
Object.assign(e,lQa(a,b));Object.assign(e,kQa(a,b));d?g.rc(e,a.C)?(d=a.D,e=a.C):d="_"+G4++:d=b.getAttribute("id")||"_"+G4++;a=J4(b,"t")+c;b=J4(b,"d")||0x8000000000000;if(2===e.Kf||3===e.Kf)c=e.tm,e.tm=e.Tm,e.Tm=c;return new F4(a,b,0,d,e)},O4=function(a){H4.call(this);
this.I=a;this.i=new Map;this.C=new Map;this.D=new Map;this.B=new Map},P4=function(a){a=g.Xf(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},nQa=function(a,b,c,d,e){0===d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.C.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.D.get(b.wsWinStyleId));a=b.rcRowCount;void 0!==a&&(f.tm=a);b=b.ccColCount;void 0!==b&&(f.Tm=b);if(2===f.Kf||3===f.Kf)b=f.tm,f.tm=f.Tm,f.Tm=b;return new F4(c,d,0,e,f)},R4=function(){this.B=this.time=this.mode=this.u=0;
this.C=new Q4(this);this.D=new Q4(this);this.i=[];this.clear()},pQa=function(a,b,c){if(255===a&&255===b||!a&&!b)return{jp:a,
Pm:b,result:0};a=oQa[a];b=oQa[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.isValid()&&c.Pm===d;if(d)return{jp:a,Pm:b,result:1}}else if(b&128&&1<=a&&31>=a)return{jp:a,Pm:b,result:2};return{jp:a,Pm:b,result:3}},rQa=function(a,b,c,d){255===b&&255===c||!b&&!c?(45===++a.B&&a.reset(),a.C.u.clear(),a.D.u.clear()):(a.B=0,qQa(a.C,b,c,d))},sQa=function(a,b){a.i.sort(function(e,f){var h=e.time-f.time;
return 0===h?e.order-f.order:h});
for(var c=g.r(a.i),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,0===d.type?rQa(a,d.sJ,d.tJ,b):1===d.type&&a.u&496&&qQa(a.D,d.sJ,d.tJ,b);a.i.length=0},S4=function(){this.type=0},T4=function(){this.state=this.Pm=this.jp=0},tQa=function(){this.timestamp=this.i=0},U4=function(a){this.D=a;
this.B=[];this.i=this.u=this.row=0;this.style=new S4;for(a=this.C=0;15>=a;a++){this.B[a]=[];for(var b=0;32>=b;b++)this.B[a][b]=new tQa}},V4=function(a,b){if(3===a.style.type){for(var c=0,d=0,e=a.D.time+0,f="",h="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var q=a.B[m][p];
if(0!==q.i){0===c&&(c=m,d=p);n=String.fromCharCode(q.i);var t=q.timestamp;t<e&&(e=t);q.timestamp=l;h&&(f+=h,h="");f+=n;n=!0}if((0===q.i||32===p)&&n){h="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.D(c,d,e,l,f)}else for(d=c=0,f=e=a.D.time+0,h=1;15>=h;++h)for(l="",m=1;32>=m;++m)if(p=a.B[h][m],q=p.i,0!==q&&(0===c&&(c=h,d=m),n=String.fromCharCode(q),t=p.timestamp,t<=e&&(e=t),l+=n,p.reset()),32===m||0===q)l&&b.D(c,d,e,f,l),e=f,l="",d=c=0},yQa=function(a,b){switch(a){case 0:return uQa[(b&127)-32];
case 1:return vQa[b&15];case 2:return wQa[b&31];case 3:return xQa[b&31]}return 0},W4=function(a){return a.B[a.row][a.u]},X4=function(a,b,c){2<=b&&1<a.u&&(--a.u,W4(a).i=0);
var d=W4(a);d.timestamp=a.D.time+0;d.i=yQa(b,c);32>a.u&&a.u++},zQa=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++){var h=a.B[b+e][f],l=a.B[c+e][f];
h.i=l.i;h.timestamp=l.timestamp}},Y4=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.B[b+d][e].reset()},Z4=function(a){a.row=0<a.i?a.i:1;
a.u=1;Y4(a,0,15)},$4=function(a){this.B=a;
this.D=0;this.style=new S4;this.I=new U4(this.B);this.K=new U4(this.B);this.text=new U4(this.B);this.u=this.I;this.C=this.K;this.i=this.u},a5=function(a,b,c){var d=a.u,e=!1;
switch(a.style.get()){case 4:case 1:case 2:4===a.style.get()&&0<d.i||(V4(d,c),Z4(a.u),Z4(a.C),d.row=15,d.i=b,e=!0)}a.style.set(3);a.i=d;a.i.style=a.style;a.B.mode=1<<d.C;e?d.u=1:d.i!==b&&(d.i>b?(V4(d,c),Y4(d,d.row-d.i,b)):d.row<b&&(b=d.i),d.i=b)},AQa=function(a){a.style.set(1);
a.i=a.C;a.i.i=0;a.i.style=a.style;a.B.mode=1<<a.i.C},BQa=function(a){a.style.set(4);
a.i=a.text;a.i.style=a.style;a.B.mode=1<<a.i.C},Q4=function(a){this.i=a;
this.D=0;this.B=new $4(this.i);this.I=new $4(this.i);this.u=new T4;this.C=this.B},qQa=function(a,b,c,d){a.u.update();
b=pQa(b,c,a.u);switch(b.result){case 0:return;case 1:case 2:return}var e=b.jp;c=b.Pm;if(32<=e||!e)a.i.mode&a.i.u&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.C.i,b&96&&X4(a,0,b),c&96&&X4(a,0,c),0!==b&&0!==c&&3===a.style.type&&V4(a,d));else if(e&16)a:if(!a.u.matches(e,c)&&(b=a.u,b.jp=e,b.Pm=c,b.state=2,b=e&8?a.I:a.B,a.C=b,a.i.mode=1<<(a.D<<2)+(b.D<<1)+(4===b.style.type?1:0),(a.i.mode|1<<(a.D<<2)+(b.D<<1)+(4!==b.style.type?1:0))&a.i.u))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?4*((c&14)>>1):0;c=b.i;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.i&&(d=c.i,d===c.row))break;var f=1+c.row-c.i,h=1+d-c.i;zQa(c,h,f,c.i);b=f;e=c.i;h<f?(f=h+e-f,0<f&&(b+=f,e-=f)):(f=f+e-h,0<f&&(e-=f));Y4(c,b,e)}}c.row=d;c.u=a+1}else switch(e&7){case 1:switch(c&112){case 32:X4(b.i,0,32);break a;case 48:57===c?(d=b.i,W4(d).i=0,32>d.u&&d.u++):X4(b.i,1,c&15)}break;case 2:c&32&&X4(b.i,2,c&31);break;case 3:c&32&&X4(b.i,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:AQa(b);
break;case 33:d=b.i;1<d.u&&(--d.u,W4(d).i=0);break;case 36:d=b.i;b=W4(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.B[a][c]===b){for(;32>=c;c++)d.B[a][c].reset();break}break;case 37:a5(b,2,d);break;case 38:a5(b,3,d);break;case 39:a5(b,4,d);break;case 40:X4(b.i,0,32);break;case 41:b.style.set(2);b.i=b.u;b.i.i=0;b.i.style=b.style;b.B.mode=1<<b.i.C;break;case 42:d=b.text;d.i=15;d.style.set(4);Z4(d);BQa(b);break;case 43:BQa(b);break;case 44:a=b.u;switch(b.style.get()){case 1:case 2:case 3:V4(a,d)}Y4(a,
0,15);break;case 45:b:{a=b.i;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.u=1;break b}case 3:}2>a.i&&(a.i=2,a.row<a.i&&(a.row=a.i));b=a.row-a.i+1;V4(a,d);zQa(a,b,b+1,a.i-1);Y4(a,a.row,1)}break;case 46:Y4(b.C,0,15);break;case 47:V4(b.u,d),b.C.updateTime(b.B.time+0),d=b.C,b.C=b.u,b.u=d,AQa(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.i,32<(d.u+=c&3)&&(d.u=32)}}},CQa=function(){},b5=function(a,b,c){this.trackData=a;
this.K=c;this.version=this.I=this.C=this.i=0;this.u=new DataView(this.trackData);this.B=[]},c5=function(a){var b=a.i;
a.i+=1;return a.u.getUint8(b)},d5=function(a){var b=a.i;
a.i+=4;return a.u.getUint32(b)},e5=function(a,b){H4.call(this);
this.B=a;this.C=b;this.track="CC3"===this.C.languageName?4:0;this.i=new R4;this.i.u=1<<this.track},f5=function(a){if("string"===typeof a)return!1;
a=new b5(a,8,0);return DQa(a)},DQa=function(a){if(!(a.i<a.u.byteLength)||1380139777!==d5(a))return!1;
a.version=c5(a);if(1<a.version)return!1;c5(a);c5(a);c5(a);return!0},g5=function(){H4.call(this)},EQa=function(a,b,c,d,e,f,h,l,m){switch(h.tagName){case "b":l.bold=!0;
break;case "i":l.qj=!0;break;case "u":l.underline=!0}for(var n=0;n<h.childNodes.length;n++){var p=h.childNodes[n];if(3===p.nodeType)p=new E4(b,c,d,e.id,p.nodeValue,f||0<n,g.oc(l)?void 0:l),m.push(p),e.i.push(p);else{var q={};Object.assign(q,l);EQa(a,b,c,d,e,!0,p,q,m)}}},h5=function(a){var b=a.split(":");
a=0;b=g.r(b);for(var c=b.next();!c.done;c=b.next())a=60*a+Number(c.value);return 1E3*a},FQa=function(a,b,c,d){d=Object.assign({Os:0},d);
return new F4(a,b,c,"_"+G4++,d)},i5=function(a){g.H.call(this);
this.Y=a;this.i=null},LQa=function(a,b,c,d,e){d=d||0;
e=e||0;if(a.Y.N("enable_h5_ssdai_caption")&&b){var f=e,h=GQa(b,d),l=[];try{for(var m=g.r(h),n=m.next();!n.done;n=m.next()){var p=n.value,q=p.trackData,t=p.vG;l="string"!==typeof q?l.concat(HQa(a,c,q,t,f)):"WEBVTT"===q.substring(0,6)?l.concat(IQa(a,q,t)):l.concat(JQa(a,c,q,t))}var u=l}catch(x){g.Hy(x),a.clear(),u=[]}if(0!==u.length)return u}a.Y.N("html5_disable_rawcc_killswitch")?"string"!==typeof b&&(u=new DataView(b),8<=u.byteLength&&1718909296===u.getUint32(4)&&(u=g.MB(u,0,1835295092),b=a.Y.N("html5_fix_mdat_offset_killswitch")?
b.slice(u.dataOffset,u.dataOffset+u.size):b.slice(u.dataOffset,u.offset+u.size),f5(b)||(b=g.$a(new Uint8Array(b))))):b=KQa(a,b);if(!b)return[];try{return"string"!==typeof b?HQa(a,c,b,d,e):"WEBVTT"===b.substring(0,6)?IQa(a,b,d):JQa(a,c,b,d)}catch(x){return g.Hy(x),a.clear(),[]}},KQa=function(a,b){if("string"===typeof b||f5(b))return b;
var c=new DataView(b);if(8>=c.byteLength||1718909296!==c.getUint32(4))return"";c=g.MB(c,0,1835295092);if(!c||!c.size)return"";a=a.Y.N("html5_fix_mdat_offset_killswitch")?b.slice(c.dataOffset,c.dataOffset+c.size):b.slice(c.dataOffset,c.offset+c.size);return g.$a(new Uint8Array(a))},GQa=function(a,b){if("string"===typeof a||f5(a))return[{trackData:a,
vG:b}];var c=new DataView(a);if(8>=c.byteLength||1718909296!==c.getUint32(4))return[];var d=g.VB(c,1835295092);if(!d||!d.length||!d[0].size)return[];var e=[];d=g.r(d.entries());for(var f=d.next();!f.done;f=d.next()){var h=g.r(f.value);f=h.next().value;h=h.next().value;h=g.$a(new Uint8Array(a.slice(h.dataOffset,h.offset+h.size)));e.push({trackData:h,vG:b+1E3*f})}MQa(c,e,b);return e=e.filter(function(l){return!!l.trackData})},MQa=function(a,b,c){var d=g.MB(a,0,1836476516),e=9E4;
d&&(e=g.NB(d)||9E4);d=0;var f=g.VB(a,1836019558);f=g.r(f.entries());for(var h=f.next();!h.done;h=f.next()){var l=g.r(h.value);h=l.next().value;l=l.next().value;h<b.length&&(l=g.MB(a,l.dataOffset,1953653094))&&(l=g.MB(a,l.dataOffset,1952867444))&&(l=g.TB(l)/e*1E3,0===h&&(d=l),b[h].vG=l-d+c||c*h*1E3)}},HQa=function(a,b,c,d,e){if(!f5(c))throw Error("Invalid binary caption track data");
a.i||(a.i=new e5(e,b));return a.i.u(c,d)},IQa=function(a,b,c){a.i||(a.i=new g5);
a=a.i.u(b,c);.01>Math.random()&&g.Iy(Error("Deprecated subtitles format in web player: WebVTT"));return a},JQa=function(a,b,c,d){if("{"===c[0])try{return a.i||(a.i=new O4(NQa(b))),a.i.u(c,d)}catch(f){return g.Hy(f),[]}var e=g.U1(c);
if(!e||!e.firstChild)throw a=Error("Invalid caption track data"),a.params=c,a;if("timedtext"===e.firstChild.tagName){if(3===Number(e.firstChild.getAttribute("format")))return a.i||(a.i=new I4(NQa(b),a.Y)),a.i.u(e,d);a=Error("Unsupported subtitles format in web player (Format2)");a.params=c;throw a;}if("transcript"===e.firstChild.tagName)throw a=Error("Unsupported subtitles format in web player (Format1)"),a.params=c,a;a=Error("Invalid caption track data");a.params=c;throw a;},NQa=function(a){var b=
{};
if(a=g.ZF(a))b.lang=a,g.BMa.test(a)&&(b.Kf=1);return b},l5=function(a){g.ZM.call(this,a);
var b=this;this.J=a;this.Y=this.J.V();this.videoData=this.J.getVideoData();this.ib=this.J.bb();this.C={ld:{}};this.D={ld:{}};this.va=[];this.S={};this.La={};this.ma=!1;this.ub=g.WG(this.videoData);this.Wa=g.Zua(this.videoData,this.J);this.kb=!!this.videoData.captionTracks.length;this.yb=!!this.videoData.Pb;this.Ka="3"===this.Y.controlsType;this.u=this.I=this.K=this.Ja=this.fb=null;this.Pa=new i5(this.Y);this.i=null;this.Z=new g.qD(this);this.Va=new g.V({G:"div",L:"ytp-caption-window-container",W:{id:"ytp-caption-window-container"}});
var c=null,d=g.Ir("yt-html5-player-modules::subtitlesModuleData");d&&(c=new g.sr(d));this.storage=c;c=a.hd();this.Za=!(null===c||void 0===c||!c.vx());this.B=OQa(this);this.X=!this.B&&this.Ka&&this.Za&&this.Wa;g.I(this,this.Pa);this.B?this.Ba=this.Aa=null:(this.Aa=new g.Dq(this.WG,void 0,this),g.I(this,this.Aa),this.Ba=new g.J(this.RW,2E3,this),g.I(this,this.Ba));g.I(this,this.Z);this.Y.N("caption_window_container_killswitch")||g.MM(this.player,this.Va.element,4);g.I(this,this.Va);this.B||this.Z.T(a,
"resize",this.YG);(this.ob=!g.cy()&&!this.J.isFullscreen()&&!this.B&&!this.X&&!this.Y.N("switch_captions_to_track_tag_when_fullscreen_api_unavailable_killswitch"))&&this.Z.T(a,"resize",this.KU);this.Z.T(a,"onPlaybackAudioChange",this.ST);this.Z.T(a,g.jA("captions"),function(e){b.onCueRangeEnter(e)});
this.Z.T(a,g.kA("captions"),function(e){b.onCueRangeExit(e)});
j5(this,k5(this,"display-settings")||{})},QQa=function(a){if(1===a.Y.Pa||1===a.videoData.Au||"alwayson"===g.FG(a.videoData,"yt:cc"))return!0;
if(2===a.Y.Pa){var b;g.vF(a.Y)?b=PQa(a):b=k5(a,"module-enabled");if(null!=b)return!!b}if(a.videoData.captionTracks.length)var c=a.player.getAudioTrack().u;b=u4(a.player.getAudioTrack(),v4(a.Y));var d=g.FG(a.videoData,"yt:cc");if(void 0===m5(a)){if("CAPTIONS_INITIAL_STATE_ON_RECOMMENDED"===b)return d?"on"===d:!0;if("CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED"===b)return"on"===d}else return"on"===d;return"ON"===c||"on"===g.FG(a.videoData,"yt:cc")},n5=function(a,b){if(a.i&&(void 0===b||!b)||!a.videoData.captionTracks.length)return!1;
a=a.player.getAudioTrack();return!!a.i||"FORCED_ON"===a.u},m5=function(a){var b=void 0,c=g.Ev(g.Cv.getInstance(),65);
if(g.vF(a.Y)&&null!=c){if(null!=PQa(a))return!1;b=!c}return b},RQa=function(a){var b;
a.ub?b=new B4(a.Y,a.videoData,a.player.getAudioTrack(),a.player):a.Wa?b=new y4(a.videoData.i,a.player):a.kb?b=new g.cN(a.Y,a.videoData,a.player.getAudioTrack()):b=new g.eN(a.Y,a.videoData.Pb,a.videoData.videoId,g.Cpa(a.videoData),a.videoData.Xi);return b},p5=function(a,b){if(a.u){if(a.I&&a.I.C)return a.I.C;
b||(b=a.yb?!1:a.kb?!1:!0);b=g.$M(a.u.u,b);for(var c=[a.videoData.captionsLanguagePreference,a.Y.captionsLanguagePreference,g.FG(a.videoData,"yt:cc_default_lang")],d=0;d<c.length;d++)for(var e=0;e<b.length;e++)if(g.ZF(b[e])===c[d])return b[e];return a.I&&a.I.B?a.I.B:(c=b.find(function(f){return f.isDefault}))?c:b[0]||o5(a)}return null},o5=function(a){return a.I&&a.I.i},q5=function(a){var b=o5(a);
return!!b&&a.i===b},SQa=function(a){var b=u4(a.player.getAudioTrack(),v4(a.Y)),c;
"CAPTIONS_INITIAL_STATE_UNKNOWN"===b?m5(a)||a.ma||QQa(a)?c=p5(a,a.ma):n5(a)&&(c=o5(a)):"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===b?c=p5(a,a.ma):"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===b&&n5(a)&&(c=o5(a));if(a.B||a.X){var d=g.$M(a.u.u,!0);b=[];for(var e=0;e<d.length;e++){var f=d[e],h=g.Gg("TRACK");h.setAttribute("kind","subtitles");h.setAttribute("label",g.XF(f));h.setAttribute("srclang",g.ZF(f));h.setAttribute("id",f.toString());a.X||h.setAttribute("src",a.u.Kp(f,"vtt"));f===c&&h.setAttribute("default",
"1");b.push(h)}c=a.J.hd();c.Ju(b);c=c.Oe();a.Za&&a.Z.T(c.textTracks,"change",a.kW)}else!a.i&&c&&r5(a,c),a.player.Na("onCaptionsTrackListChanged"),a.player.Na("onApiChange")},TQa=function(a,b){var c=a.J.hd().Oe().textTracks;
a=a.i.toString();for(var d=0;d<c.length;d++){var e=c[d];e.id===a&&(b?"showing"!==e.mode&&(e.mode="showing"):"showing"===e.mode&&(e.mode="disabled"))}},r5=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.ma=c,a.ma&&(g.vF(a.Y)?s5(a,!!b):t5(a,"module-enabled",!!b)));a.i=b;n5(a)&&(a.i=o5(a));a.load()},UQa=function(a,b){a.Y.N("caption_window_container_killswitch")?g.MM(a.player,b,4):a.Va.element.appendChild(b)},VQa=function(a,b){var c=a.ib.getVideoContentRect(!0).height;
if(!c)return null;var d=a.i?g.ZF(a.i):null;d&&g.BMa.test(d)&&(b.params.Kf=1);d=a.ib.getPlayerSize();switch(null!=b.params.Os?b.params.Os:1<b.i.length?1:0){case 1:return new C4(b,a.C,a.D,c,d.width,d.height,a.Y.experiments);case 2:return new D4(b,a.C,a.D,c,d.width,d.height,a.Y.experiments);default:return new A4(b,a.C,a.D,c,d.width,d.height,a.Y.experiments)}},j5=function(a,b,c){c=void 0===c?!1:c;
var d=u5.ld;a.C={};Object.assign(a.C,u5);a.C.ld={};Object.assign(a.C.ld,d);a.D={ld:{}};var e=b.backgroundOverride?a.D:a.C,f=b.background||d.background;M4.test(f);e.ld.background=f;e=b.colorOverride?a.D:a.C;f=b.color||d.color;M4.test(f);e.ld.color=f;e=b.windowColorOverride?a.D:a.C;f=b.windowColor||u5.windowColor;M4.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.D:a.C;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.ld.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.D:a.C;f=b.fontSizeIncrement;
null==f&&(f=d.fontSizeIncrement);e.ld.fontSizeIncrement=f;f=b.fontStyleOverride?a.D:a.C;e=b.fontStyle;null==e&&(e=d.bold&&d.qj?3:d.bold?1:d.qj?2:0);f=f.ld;switch(e){case 1:f.bold=!0;delete f.qj;break;case 2:delete f.bold;f.qj=!0;break;case 3:f.bold=!0;f.qj=!0;break;default:delete f.bold,delete f.qj}e=b.textOpacityOverride?a.D:a.C;f=b.textOpacity;null==f&&(f=d.textOpacity);e.ld.textOpacity=f;e=b.windowOpacityOverride?a.D:a.C;f=b.windowOpacity;null==f&&(f=u5.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?
a.D:a.C;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.ld.charEdgeStyle=f;e=b.fontFamilyOverride?a.D:a.C;f=b.fontFamily;null==f&&(f=d.fontFamily);e.ld.fontFamily=f;a.loaded&&a.YG();c&&t5(a,"display-settings",b)},v5=function(a,b,c){b&&!a.K?(b=hQa({Kf:0,
lang:"en"}),a.K=[b,new E4(b.start,b.end-b.start,0,b.id,null!==c&&void 0!==c?c:"Captions look like this")],a.player.Ad(a.K)):!b&&a.K&&(WQa(a,a.K),a.K=null)},WQa=function(a,b){a.player.Hf(b);
g.Rb(b,function(c){g.Ab(this.va,c)},a);
g.Eq(a.Aa)},k5=function(a,b){if(!a.storage)return null;
try{var c=a.storage.get(b)}catch(d){a.storage.remove(b)}return c},t5=function(a,b,c){if(a.storage)try{a.storage.set(b,c)}catch(d){}},s5=function(a,b){a.J.isInline()||g.Gz("yt-player-sticky-caption",b,2592E3)},PQa=function(a){if(!a.J.isInline())return g.Hz("yt-player-sticky-caption")},OQa=function(a){var b=a.J.hd();
b=!(null===b||void 0===b||!b.tx());return a.Ka&&b&&!a.Wa};
g.HS.prototype.Bv=g.ca(31,function(a){var b=2;this.va.has(a)?b=0:g.LAa(this,a)&&(b=1);return b});
g.PV.prototype.Bv=g.ca(30,function(a){return this.Fd.Bv(a)});
g.qN.prototype.Kr=g.ca(29,function(){this.oa();for(var a=g.tg(document,"track",void 0,this.i),b=0;b<a.length;b++)g.Kg(a[b])});
g.oS.prototype.Kr=g.ca(28,function(){this.ra.Kr()});
g.qN.prototype.vx=g.ca(27,function(){return!(!this.i.textTracks||!this.i.textTracks.addEventListener)});
g.oS.prototype.vx=g.ca(26,function(){return this.ra.vx()});
g.qN.prototype.tx=g.ca(25,function(){return!!this.i.textTracks});
g.oS.prototype.tx=g.ca(24,function(){return this.ra.tx()});
g.qN.prototype.Ju=g.ca(23,function(a){this.oa();for(var b=0;b<a.length;b++)this.i.appendChild(a[b])});
g.oS.prototype.Ju=g.ca(22,function(a){this.ra.Ju(a)});
g.bN.prototype.KF=g.ca(21,function(){return!1});
g.bN.prototype.Mn=g.ca(20,function(){});
g.cN.prototype.Mn=g.ca(19,function(a,b,c){var d=this;this.isDisposed();b=this.Kp(a,b);this.Dm();this.i=g.wt(b,{format:"RAW",onSuccess:function(e){d.i=null;c(e.responseText,a)},
withCredentials:!0})});
g.eN.prototype.Mn=g.ca(18,function(a,b,c){var d=this;this.isDisposed();b=this.Kp(a,b);this.Dm();this.i=g.wt(b,{format:"RAW",onSuccess:function(e){d.i=null;c(e.responseText,a)},
withCredentials:!0})});
g.zV.prototype.Ov=g.ca(6,function(){return this.K});
g.VX.prototype.Ov=g.ca(5,function(){var a;return(null===(a=g.OM(this))||void 0===a?void 0:a.Jv())||null});
g.FM.prototype.Jv=g.ca(4,function(){return this.app.Ov()});
g.yX.prototype.Jv=g.ca(3,function(){var a;return(null===(a=this.Ya)||void 0===a?void 0:a.Ov())||null});
var TPa={aa:"Afar",ab:"Abkhazian",ace:"Achinese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",ale:"Aleut",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",arp:"Arapaho",ars:"Najdi Arabic",arw:"Arawak",as:"Assamese",asa:"Asu",ast:"Asturian",av:"Avaric",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",
az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bas:"Basaa",bax:"Bamun",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bez:"Bena",bfd:"Bafut",bg:"Bulgarian",bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bkm:"Kom",bla:"Siksika",bm:"Bambara",bn:"Bangla",bo:"Tibetan",br:"Breton",bra:"Braj",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",
car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",ckb_Arab:"Central Kurdish (Arabic)",co:"Corsican",cop:"Coptic",cr:"Cree",crh:"Crimean Turkish",cs:"Czech",csb:"Kashubian",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",
de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",
es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fulah",ff_Adlm:"Fulah (Adlam)",ff_Latn:"Fulah (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",
gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",
iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kha:"Khasi",
kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Lahnda",lam:"Lamba",lb:"Luxembourgish",
lez:"Lezghian",lg:"Ganda",li:"Limburgish",lkt:"Lakota",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",
mi:"Maori",mic:"Mi'kmaq",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian (Moldova)",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",
ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",
pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",
sad:"Sandawe",sah:"Sakha",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",
sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",
syr:"Syriac",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",
umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vi:"Vietnamese",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",
za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};w4.prototype.contains=function(a){a=g.Jb(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
w4.prototype.length=function(){return this.segments.length/2};
g.v(x4,g.H);g.k=x4.prototype;g.k.ya=function(){g.H.prototype.ya.call(this);this.B&&this.B.cancel()};
g.k.kA=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(a){a-=this.player.Tc();var b=this.i;this.i=g.qb(this.ma.Pl(a).i);b!==this.i&&this.X&&this.X()};
g.k.reset=function(){this.C=new w4;this.I=-1;this.B&&(this.B.cancel(),this.B=null)};
g.k.EL=function(){var a;this.isDisposed();var b;if(b=null!=this.i)b=this.i,b=b.i.Im(b);if(b&&!this.B&&!(this.i&&30<this.i.startTime-this.player.getCurrentTime())){b=this.i;b=b.i.au(b);if(this.Y.N("enable_h5_ssdai_caption")&&(null===(a=this.player.getVideoData())||void 0===a?0:a.enableServerStitchedDai)){var c=this.player.Jv();if(c){var d=b.i[0].Ma,e=c.Yr(b.i[0].C,d,b.i[0].i.info.id,3);if(e)if(c=c.Bv(d),0===c)e&&(b.B=new g.qB(e));else if(2===c){this.K.start();RPa(this)&&this.seekTo(this.player.getCurrentTime());
return}}}b.i[0].duration?(this.C.contains(b.i[0].Ma)||SPa(this,b),this.i=g.qb(b.i)):!this.Y.N("force_caption_seek_for_live_killswitch")&&RPa(this)&&this.seekTo(this.player.getCurrentTime())}this.K.start()};
g.k.oa=function(){};
g.v(y4,g.bN);g.k=y4.prototype;g.k.Mn=function(a,b,c){var d=this;this.Dm();b=VPa(this,a.getId());b||(b=a.languageCode,b=this.i.isManifestless?WPa(this,b,"386"):WPa(this,b));if(b){var e=1E3*(b.index.getStartTimeInPeriod(b.index.getFirstSegmentNumber())-b.index.getStartTime(b.index.getFirstSegmentNumber())),f=new g.Xua(this.Y);this.B=new x4(f,this.J,b,function(h,l){c(h,a,l,e)},this.I||g.$C(b.info),function(){d.B&&d.B.reset();
d.D=!0})}};
g.k.KF=function(){var a=this.D;this.D=!1;return a};
g.k.Ls=function(a){var b=this.I?[new g.WF({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.WF({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:this.i.isManifestless?UPa(this,"386"):UPa(this);b=g.r(b);for(var c=b.next();!c.done;c=b.next())g.aN(this.u,c.value);a()};
g.k.Dm=function(){this.B&&(this.B.dispose(),this.B=null)};
g.k.Kp=function(){return""};
var M4=/^#(?:[0-9a-f]{3}){1,2}$/i,YPa=/#(.)(.)(.)/,XPa=/^#(?:[0-9a-f]{3}){1,2}$/i;var $Pa=["left","right","center","justify"];g.v(A4,g.V);g.k=A4.prototype;g.k.cQ=function(a,b){var c=g.Ul(this.element,this.element.parentElement);this.Za=a-c.x;this.ib=b-c.y;g.M(this.element,"ytp-dragging")};
g.k.bQ=function(a,b){var c=g.Wl(this.element);a=a-this.Za-.02*this.playerWidth;var d=b-this.ib-.02*this.playerHeight,e=(a+c.width/2)/this.maxWidth*3;e=Math.floor(g.Xf(e,0,2));var f=(d+c.height/2)/this.Va*3;f=Math.floor(g.Xf(f,0,2));b=e+3*f;a=(a+e/2*c.width)/this.maxWidth;a=100*g.Xf(a,0,1);c=(d+f/2*c.height)/this.Va;c=100*g.Xf(c,0,1);this.u.params.di=b;this.u.params.Kj=c;this.u.params.eh=a;this.i.di=b;this.i.Kj=c;this.i.eh=a;this.Ja.di=b;this.Ja.Kj=c;this.Ja.eh=a;this.EN()};
g.k.aQ=function(){g.Qq(this.element,"ytp-dragging")};
g.k.EN=function(){this.xt(this.D)};
g.k.getType=function(){return this.type};
g.k.xt=function(a){var b=Math.min(this.pK(),this.maxWidth),c=this.oK(),d="";3===this.u.params.Kf&&(d="rotate(180deg)");g.Hl(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.MC(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.i.eh+2;d=this.i.di;switch(d){case 0:case 3:case 6:(b=this.i.ld.fontSizeIncrement)&&0<b&&2!==this.i.Kf&&3!==
this.i.Kf&&(e=Math.max(e/(1+2*b),2));a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.C.offsetWidth;b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.i.Kj+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.Hl(this.element,
a)};
g.k.MC=function(a){var b;for(b=0;b<a.length&&a[b]===this.D[b];b++);if(this.va||this.D.length>b)b=0,this.va=!1,this.D=[],this.I=this.Ba=this.Aa=null,g.Ig(this.C);for(;b<a.length;b++)dQa(this,a[b])};
g.k.pK=function(){return 0};
g.k.oK=function(){return 0};
g.k.toString=function(){return g.V.prototype.toString.call(this)};g.v(B4,g.bN);B4.prototype.Mn=function(a,b,c){PPa(this.videoData.videoId,a.vssId,c)};
B4.prototype.Ls=function(a){if(this.audioTrack)for(var b=g.r(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())g.aN(this.u,c.value);a()};g.v(C4,A4);C4.prototype.MC=function(a){var b=this.u.i;A4.prototype.MC.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.i===e)var d=f;else{d={};Object.assign(d,c.i);Object.assign(d,XQa);var e=c.i;var f=d}dQa(this,c,d)}};
var XQa={DS:!0};g.v(D4,A4);g.k=D4.prototype;g.k.EN=function(){g.Iq(this.Pa)};
g.k.CV=function(){g.Qq(this.element,"ytp-rollup-mode");this.xt(this.ub,!0)};
g.k.oK=function(){return this.B?this.X:this.S};
g.k.pK=function(){return this.B?this.S:this.X};
g.k.xt=function(a,b){this.ub=a;if(this.u.params.tm){for(var c=0,d=0;d<this.D.length&&c<a.length;d++)this.D[d]===a[c]&&c++;0<c&&c<a.length&&(a=this.D.concat(a.slice(c)));this.ob=this.X;this.S=this.X=0;A4.prototype.xt.call(this,a);gQa(this,b)}A4.prototype.xt.call(this,a)};g.v(E4,g.hA);E4.prototype.toString=function(){return g.hA.prototype.toString.call(this)};g.v(F4,g.hA);F4.prototype.toString=function(){return g.hA.prototype.toString.call(this)};
var G4=0;g.v(H4,g.H);H4.prototype.u=function(){return[]};
H4.prototype.reset=function(){};g.v(I4,H4);I4.prototype.reset=function(){this.K={};this.B=this.i=null;this.I=!0};
I4.prototype.u=function(a,b){a=a.firstChild;a.getAttribute("format");b=b||0;Number.isFinite(b);a=Array.from(a.childNodes);a=g.r(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value,1===c.nodeType)switch(c.tagName){case "head":var d=c;break;case "body":var e=c}if(d)for(d=Array.from(d.childNodes),d=g.r(d),a=d.next();!a.done;a=d.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "pen":c=a.getAttribute("id");var f=this.pens,h={},l=a.getAttribute("p");l&&Object.assign(h,this.pens[l]);l=K4(a,"b");
null!=l&&(h.bold=l);l=K4(a,"i");null!=l&&(h.qj=l);l=K4(a,"u");null!=l&&(h.underline=l);l=L4(a,"et");null!=l&&(h.charEdgeStyle=l);l=L4(a,"of");null!=l&&(h.offset=l);l=N4(a,"bc");null!=l&&(h.background=l);l=N4(a,"ec");null!=l&&(h.bD=l);l=N4(a,"fc");null!=l&&(h.color=l);l=L4(a,"fs");null!=l&&0!==l&&(h.fontFamily=l);l=J4(a,"sz");void 0!==l&&(h.fontSizeIncrement=l/100-1);l=J4(a,"bo");void 0!==l&&(h.backgroundOpacity=l/255);l=J4(a,"fo");void 0!==l&&(h.textOpacity=l/255);l=L4(a,"rb");null!=l&&10!==l&&0!==
l&&(h.Zd=10<l?l-1:l);a=L4(a,"hg");null!=a&&(h.RK=a);f[c]=h;break;case "ws":c=a.getAttribute("id");this.X[c]=kQa(this,a);break;case "wp":c=a.getAttribute("id"),this.S[c]=lQa(this,a)}if(e){d=[];e=Array.from(e.childNodes);e=g.r(e);for(a=e.next();!a.done;a=e.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "w":this.i=mQa(this,a,b,!1);(a=this.K[this.i.id])&&a.end>this.i.start&&(a.end=this.i.start);this.K[this.i.id]=this.i;d.push(this.i);break;case "p":l=b;c=[];f=a.getAttribute("w")||this.D;h=
!!K4(a,"a");l=(J4(a,"t")||0)+l;var m=J4(a,"d")||5E3;h||(!this.I&&this.B&&this.B.windowId===f&&this.B.end>l&&(this.B.end=l),this.B&&"\n"===this.B.text&&(this.B.text=""));var n=h?6:5,p=a.getAttribute("p");p=p?this.pens[p]:null;var q=Array.from(a.childNodes);q.length&&(this.I=null!=a.getAttribute("d"));for(var t=0;t<q.length;t++){var u=q[t],x=void 0;0<t&&(h=!0);var y=void 0;1===u.nodeType&&(y=u);if(y&&"s"===y.tagName){if((u=(u=y.getAttribute("p"))?this.pens[u]:null)&&u.Zd&&(1===u.Zd?(u=q.slice(t,t+4),
4===u.length&&(x=jQa(l,m,f,h,n,u,this.pens),t+=3)):x=jQa(l,m,f,h,n,[y],this.pens)),!x){var z=y;x=l;y=m;u=f;var G=h,E=n,C=z.textContent?z.textContent:"",L=z.getAttribute("p");L=L?this.pens[L]:null;z=J4(z,"t")||0;x=new E4(x+z,y-z,E,u,C,G,L)}}else x=new E4(l,m,n,f,u.textContent||"",h,p);c.push(x);this.B=x}if(0<c.length)for(c[0].windowId===this.D&&(this.i=mQa(this,a,b,!0),d.push(this.i)),a=g.r(c),c=a.next();!c.done;c=a.next())c=c.value,c.windowId=this.i.id,this.i.i.push(c),d.push(c)}b=d}else b=[];return b};var YQa=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.v(O4,H4);O4.prototype.reset=function(){this.B.clear()};
O4.prototype.u=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens){a=0;for(var d=g.r(c.pens),e=d.next();!e.done;e=d.next()){e=e.value;var f={},h=e.pParentId;h&&Object.assign(f,this.i.get(h));e.bAttr&&(f.bold=!0);e.iAttr&&(f.qj=!0);e.uAttr&&(f.underline=!0);h=e.ofOffset;null!=h&&(f.offset=h);void 0!==e.szPenSize&&(f.fontSizeIncrement=e.szPenSize/100-1);h=e.etEdgeType;null!=h&&(f.charEdgeStyle=h);void 0!==e.ecEdgeColor&&(f.bD=P4(e.ecEdgeColor));h=e.fsFontStyle;null!=h&&0!==h&&(f.fontFamily=
h);void 0!==e.fcForeColor&&(f.color=P4(e.fcForeColor));void 0!==e.foForeAlpha&&(f.textOpacity=e.foForeAlpha/255);void 0!==e.bcBackColor&&(f.background=P4(e.bcBackColor));void 0!==e.boBackAlpha&&(f.backgroundOpacity=e.boBackAlpha/255);(h=e.rbRuby)&&10!==h&&(f.Zd=10<h?h-1:h,f.Jj=YQa.get(f.Zd));e.hgHorizGroup&&(f.RK=e.hgHorizGroup);this.i.set(a++,f)}}if(c.wsWinStyles)for(a=0,d=g.r(c.wsWinStyles),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wsParentId)?Object.assign(f,this.D.get(h)):Object.assign(f,
this.I),void 0!==e.mhModeHint&&(f.Os=e.mhModeHint),void 0!==e.juJustifCode&&(f.textAlign=e.juJustifCode),void 0!==e.pdPrintDir&&(f.Kf=e.pdPrintDir),void 0!==e.sdScrollDir&&(f.EG=e.sdScrollDir),void 0!==e.wfcWinFillColor&&(f.windowColor=P4(e.wfcWinFillColor)),void 0!==e.wfoWinFillAlpha&&(f.windowOpacity=e.wfoWinFillAlpha/255),this.D.set(a++,f);if(c.wpWinPositions)for(a=0,d=g.r(c.wpWinPositions),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wpParentId)&&Object.assign(f,this.C.get(h)),void 0!==e.ahHorPos&&
(f.eh=e.ahHorPos),void 0!==e.apPoint&&(f.di=e.apPoint),void 0!==e.avVerPos&&(f.Kj=e.avVerPos),void 0!==e.ccCols&&(f.Tm=e.ccCols),void 0!==e.rcRows&&(f.tm=e.rcRows),this.C.set(a++,f);if(c.events){a=[];c=g.r(c.events);for(d=c.next();!d.done;d=c.next()){var l=d.value;d=(l.tStartMs||0)+b;e=l.dDurationMs||0;if(l.id)f=String(l.id),d=nQa(this,l,d,e,f),a.push(d),this.B.set(f,d);else{l.wWinId?f=l.wWinId.toString():(f="_"+G4++,h=nQa(this,l,d,e,f),a.push(h),this.B.set(f,h));0===e&&(e=5E3);h=this.B.get(f);var m=
!!l.aAppend,n=m?6:5,p=l.segs,q=null;l.pPenId&&(q=this.i.get(l.pPenId));for(l=0;l<p.length;l++){var t=p[l],u=t.utf8;if(u){var x=t.tOffsetMs||0,y=null;t.pPenId&&(y=this.i.get(t.pPenId));if(2===(null!=h.params.Os?h.params.Os:1<h.i.length?1:0)&&m&&"\n"===u)continue;if(t=y&&1===y.Zd)if(t=l,t+3>=p.length||!p[t+1].pPenId||!p[t+2].pPenId||!p[t+3].pPenId)t=!1;else{var z=p[t+1].pPenId;(z=this.i.get(z))&&z.Zd&&2===z.Zd?(z=p[t+2].pPenId,z=this.i.get(z),!z||!z.Zd||3>z.Zd?t=!1:(z=p[t+3].pPenId,t=(z=this.i.get(z))&&
z.Zd&&2===z.Zd?!0:!1)):t=!1}if(t){x=p[l+1].utf8;t=p[l+3].utf8;z=p[l+2].utf8;var G=this.i.get(p[l+2].pPenId);u=iQa(u,x,z,t,G);m=new E4(d,e,n,f,u,m,y);l+=3}else m=new E4(d+x,e-x,n,h.id,u,m,y||q);m&&(a.push(m),h.i.push(m))}m=!0}}}b=a}else b=[];return b};R4.prototype.clear=function(){this.B=this.time=this.mode=0;this.i=[];this.reset()};
R4.prototype.reset=function(){this.mode=0;this.C.reset(0);this.D.reset(1)};
var oQa=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];S4.prototype.set=function(a){this.type=a};
S4.prototype.get=function(){return this.type};
T4.prototype.clear=function(){this.state=0};
T4.prototype.update=function(){this.state=2===this.state?1:0};
T4.prototype.isValid=function(){return 0!==this.state};
T4.prototype.matches=function(a,b){return this.isValid()&&a===this.jp&&b===this.Pm};
tQa.prototype.reset=function(){this.timestamp=this.i=0};
U4.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.B[b][c].timestamp=a};
U4.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.B[b][c];a=0===d.i?a+"_":a+String.fromCharCode(d.i)}a+="\n"}return a};
U4.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.B[b][c].reset();this.C=a;this.i=0;this.u=this.row=1};
var uQa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],vQa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],wQa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],xQa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];$4.prototype.reset=function(a,b){this.D=b;this.style.set(2);this.u=this.I;this.C=this.K;this.i=this.u;var c=(a<<2)+(b<<1);this.I.reset(c);this.K.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
Q4.prototype.reset=function(a){this.D=a;this.u.clear();this.C=this.B;this.B.reset(a,0);this.I.reset(a,1)};CQa.prototype.D=function(){};g.v(b5,CQa);b5.prototype.D=function(a,b,c,d,e){if(c<d){var f="_"+G4++;c=c/1E3-this.K;d=d/1E3-this.K;a=new F4(c,d-c,5,f,{textAlign:0,di:0,eh:2.5*b,Kj:5.33*a});e=new E4(c,d-c,5,f,e);this.B.push(a);this.B.push(e)}};
g.v(e5,H4);e5.prototype.u=function(a){a=new b5(a,a.byteLength,this.B);if(DQa(a)){for(;a.i<a.u.byteLength;)for(0===a.version?a.C=d5(a)*(1E3/45):1===a.version&&(a.C=4294967296*d5(a)+d5(a)),a.I=c5(a);0<a.I;a.I--){var b=c5(a),c=c5(a),d=c5(a);b&4&&(b&3)===this.track&&(0===this.track||1===this.track)&&(b=this.i,b.i.push({time:a.C,type:this.track,sJ:c,tJ:d,order:b.i.length}))}sQa(this.i,a);return a.B}return[]};
e5.prototype.reset=function(){this.i.clear()};g.v(g5,H4);
g5.prototype.u=function(a,b){var c=[];a=a.split(ZQa);for(var d=1;d<a.length;d++){var e=a[d],f=b;if(""!==e&&!$Qa.test(e)){var h=w5.exec(e);if(h&&4<=h.length){var l=h5(h[1]),m=h5(h[2])-l;l+=f;var n=(h=h[3])?h.split(" "):[];h={};var p=null;var q="";var t=null,u="";n=g.r(n);for(var x=n.next();!x.done;x=n.next())if(x=x.value.split(":"),2===x.length){var y=x[1];switch(x[0]){case "line":x=y.split(",");x[0].endsWith("%")&&(p=x[0],h.Kj=Number.parseInt(p,10),2===x.length&&(q=x[1].trim()));break;case "position":x=
y.split(",");t=x[0];h.eh=Number.parseInt(t,10);2===x.length&&(u=x[1].trim());break;case "align":switch(y){case "start":h.textAlign=0;break;case "middle":h.textAlign=2;break;case "end":h.textAlign=1}}}p||q||(q="end");if(!t)switch(h.textAlign){case 0:h.eh=0;break;case 1:h.eh=100;break;case 2:h.eh=50}if(null!=h.textAlign){p=0;switch(q){case "center":p+=3;break;case "end":p+=6;break;default:p+=0}switch(u){case "line-left":p+=0;break;case "center":p+=1;break;case "line-right":p+=2;break;default:switch(h.textAlign){case 0:p+=
0;break;case 2:p+=1;break;case 1:p+=2}}q=0>p||8<p?7:p;h.di=q}e=e.substring(w5.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");u=h;h=e;e={};if(0>h.indexOf("<")&&0>h.indexOf("&"))f=FQa(l,m,5,u),m=new E4(l,m,5,f.id,h,!1,g.oc(e)?void 0:e),c.push(f),c.push(m),f.i.push(m);else for(q=h.split(aRa),1===q.length?(h=5,u=FQa(l,m,h,u)):(p=h=6,u=Object.assign({Tm:32},u),u=new F4(l,m,p,"_"+G4++,u)),c.push(u),p=l,t=0;t<q.length;t++)n=q[t],0===t%2?(x=g.U1("<html>"+n+"</html>"),x.getElementsByTagName("parsererror").length?
(y=x.createElement("span"),y.appendChild(x.createTextNode(n))):y=x.firstChild,EQa(this,p,m-(p-l),h,u,0<t,y,e,c)):p=h5(n)+f}w5.lastIndex=0}}return c};
var $Qa=/^NOTE/,ZQa=/(?:\r\n|\r|\n){2,}/,w5=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),aRa=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.vS.Az(g5,{u:"wvppt"});g.v(i5,g.H);i5.prototype.clear=function(){this.i&&this.i.dispose();this.i=null};
i5.prototype.reset=function(){this.i&&this.i.reset()};
i5.prototype.ya=function(){g.H.prototype.ya.call(this);this.clear()};var u5={windowColor:"#080808",windowOpacity:0,textAlign:2,di:7,eh:50,Kj:100,ld:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.v(l5,g.ZM);g.k=l5.prototype;g.k.ya=function(){if(this.B||this.X){var a=this.J.hd();a&&!a.isDisposed()&&a.Kr()}else v5(this,!1);g.ZM.prototype.ya.call(this)};
g.k.Cq=function(){if(this.Ka)return this.B||this.X;var a=u4(this.player.getAudioTrack(),v4(this.Y));return"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===a?!0:"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===a?n5(this):m5(this)||n5(this)?!0:QQa(this)};
g.k.load=function(){var a=this;g.ZM.prototype.load.call(this);var b=!this.Y.N("web_player_captions_track_list_changed_killswitch");this.I=this.player.getAudioTrack();this.u?(this.i&&(this.Pa.clear(),this.B?TQa(this,!0):3!==this.player.getPresentingPlayerType()&&this.u.Mn(this.i,"json3",function(c,d,e,f){c&&(a.u.KF()&&(a.va=[],a.J.Xe("captions"),g.Eq(a.Aa),a.Pa.reset()),c=LQa(a.Pa,c,d,e,f),a.Y.N("tv_caption_performance_optimization")?a.player.Ad(c,void 0,a.Wa):a.player.Ad(c),!a.ma||a.X||q5(a)||g.hF(a.Y)||
g.aF(a.Y)||(g.Jq(a.Ba),c=hQa({di:0,eh:5,Kj:5,tm:2,textAlign:0,Kf:0,lang:"en"}),a.Ja=[c],d=["Click "," for settings"],a.fb||(e=new g.JK(g.ZK()),g.I(a,e),a.fb=e.element),e=c.end-c.start,(f=g.XF(a.i))&&a.Ja.push(new E4(c.start,e,0,c.id,f)),a.Ja.push(new E4(c.start,e,0,c.id,d[0]),new E4(c.start,e,0,c.id,a.fb,!0),new E4(c.start,e,0,c.id,d[1],!0)),a.player.Ad(a.Ja),g.Hq(a.Ba)),!a.ma||a.X||q5(a)||(g.vF(a.Y)?s5(a,!0):t5(a,"module-enabled",!0),a.I&&(a.I.C=a.i),a.player.Kq()),a.ma=!1)}),!b||this.B||this.X||
q5(this)||this.player.Na("captionschanged",g.YF(this.i))),b||(this.i&&!q5(this)?this.player.Na("captionschanged",g.YF(this.i)):this.player.Na("onCaptionsTrackListChanged"))):(this.u=RQa(this),g.I(this,this.u),this.u.Ls(function(){SQa(a)}))};
g.k.unload=function(){this.B&&this.i?TQa(this,!1):(this.Ba&&g.Jq(this.Ba),this.player.Xe("captions"),this.va=[],this.u&&this.u.Dm(),this.Pa.clear(),this.K&&this.player.Ad(this.K),this.YG());g.ZM.prototype.unload.call(this);this.player.Kq();this.player.Na("captionschanged",{})};
g.k.create=function(){this.Cq()&&this.load()};
g.k.kW=function(){for(var a=this.J.hd().Oe().textTracks,b=null,c=0;c<a.length;c++)if("showing"===a[c].mode)a:{b=a[c].id;var d=g.$M(this.u.u,!0);for(var e=0;e<d.length;e++)if(d[e].toString()===b){b=d[e];break a}b=null}(this.loaded?this.i:null)!==b&&r5(this,b,!0)};
g.k.LX=function(){!this.i&&this.B||this.unload()};
g.k.onCueRangeEnter=function(a){this.va.push(a);g.Eq(this.Aa)};
g.k.onCueRangeExit=function(a){g.Ab(this.va,a);this.u instanceof y4&&this.u.I&&this.player.Hf([a]);g.Eq(this.Aa)};
g.k.LW=function(a){if(a instanceof F4){var b=this.S[a.id];b&&b.u!==a&&(b.dispose(),delete this.S[a.id],b=null);b||(b=VQa(this,a))&&(this.S[a.id]=b)}else b=a.windowId,this.La[b]||(this.La[b]=[]),this.La[b].push(a)};
g.k.getCaptionWindowContainerId=function(){return this.Va.element.id};
g.k.RW=function(){WQa(this,this.Ja);this.Ja=null};
g.k.WG=function(){var a=this;if(!this.ob||!this.B){this.Aa.stop();g.pc(this.La);this.va.sort(g.iA);var b=this.va;if(this.K){var c=g.Do(b,function(d){return-1===this.K.indexOf(d)},this);
c.length&&(b=c)}g.Rb(b,this.LW,this);g.Zb(this.S,function(d,e){a.La[e]?(d.element.parentNode||(d instanceof D4||d instanceof C4||g.dc(a.S,function(f,h){h!==e&&f.u.params.di===d.u.params.di&&f.u.params.eh===d.u.params.eh&&f.u.params.Kj===d.u.params.Kj&&(f.dispose(),delete a.S[h]);return h===e},a),UQa(a,d.element)),d.xt(a.La[e])):(d.dispose(),delete a.S[e])},this)}};
g.k.WW=function(){j5(this,{},!0);this.Y.N("web_player_disable_publish_captions_settings_changed_on_reset")||this.player.Na("captionssettingschanged")};
g.k.bS=function(){var a=u5.ld;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.qj?3:a.bold?1:a.qj?2:0,textOpacity:a.textOpacity,windowColor:u5.windowColor,windowOpacity:u5.windowOpacity};var b=k5(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.k.FO=function(a,b){var c={};Object.assign(c,k5(this,"display-settings"));Object.assign(c,a);j5(this,c,b);this.player.Na("captionssettingschanged")};
g.k.YG=function(){!this.B&&this.loaded&&(g.Zb(this.S,function(a,b){a.dispose();delete this.S[b]},this),this.WG())};
g.k.jf=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.Xf(b,-2,4);this.FO({fontSizeIncrement:c});return c;case "reload":b&&!this.B&&r5(this,this.i,!0);break;case "stickyLoading":void 0!==b&&this.Y.u&&(g.vF(this.Y)?s5(this,!!b):t5(this,"module-enabled",!!b));break;case "track":if(!this.u)return{};if(b){if(this.B)break;if(!g.Ma(b))break;if(g.oc(b)){r5(this,null,!0);break}a=g.$M(this.u.u,!0);for(var d=0;d<a.length;d++){var e=a[d];e.languageCode!==b.languageCode||c&&e.languageName!==
b.languageName||(c=b.translationLanguage?OPa(e,b.translationLanguage):e)}!c||c===this.i&&this.loaded||(b=g.Lma(),a=g.ZF(c),b.length&&a===b[b.length-1]||(b.push(a),g.Gz("yt-player-caption-language-preferences",b)),r5(this,c,!0))}else return this.loaded&&this.i&&!q5(this)?g.YF(this.i):{};return"";case "tracklist":return this.u?g.jm(g.$M(this.u.u,!(!b||!b.includeAsr)),function(f){return g.YF(f)}):[];
case "translationLanguages":return this.u?this.u.C.map(function(f){return Object.assign({},f)}):[];
case "sampleSubtitles":this.B||void 0===b||v5(this,!!b);break;case "sampleSubtitlesCustomized":this.B||v5(this,!!b,b)}};
g.k.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.Y.u&&a.push("stickyLoading");return a};
g.k.YD=function(){var a=this.i;if(a){var b=a.vssId;a.translationLanguage&&b&&!this.Y.N("auto_translation_logging_killswitch")&&(b="t"+b+"."+g.ZF(a));return{cc:b}}return{}};
g.k.CX=function(){this.loaded&&this.i&&!q5(this)?(g.vF(this.Y)?s5(this,!1):t5(this,"module-enabled",!1),this.unload(),n5(this,!0)&&r5(this,o5(this),!1)):this.nO()};
g.k.nO=function(){this.loaded&&this.i&&!q5(this)||r5(this,q5(this)||!this.i?p5(this,!0):this.i,!0)};
g.k.ST=function(){var a=q5(this);n5(this,a)?r5(this,this.player.getAudioTrack().i,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.Cq()&&(a?r5(this,p5(this),!1):this.load()))};
g.k.KU=function(){var a=this.J.hd();a&&!a.isDisposed()&&a.Kr();this.J.isFullscreen()?(this.B=this.Ka=!0,this.loaded&&SQa(this)):(this.Ka="3"===this.Y.controlsType,this.B=OQa(this));r5(this,this.i)};
g.vS.Az(l5,{WG:"smucd"});g.YM("captions",l5);})(_yt_player);
