(function(g){var window=this;'use strict';var gRa=function(a,b){a.Na("onAutonavCoundownStarted",b)},K5=function(a,b,c){g.N(a.element,"ytp-suggestion-set",!!b.videoId);
var d=b.playlistId;c=b.Ke(c?c:"mqdefault.jpg");var e=null,f=null;b instanceof g.NF&&(b.lengthText?(e=b.lengthText||null,f=b.cq||null):b.lengthSeconds&&(e=g.JL(b.lengthSeconds),f=g.JL(b.lengthSeconds,!0)));var h=!!d;d=h&&"RD"===g.JF(d).type;var l=b instanceof g.NF?b.isLivePlayback:null,m=b instanceof g.NF?b.isUpcoming:null;c={title:b.title,author:b.author,author_and_views:b.shortViewCount?b.author+" \u2022 "+b.shortViewCount:b.author,aria_label:b.zl||g.qI("Watch $TITLE",{TITLE:b.title}),duration:e,
timestamp:f,url:b.Dk(),is_live:l,is_upcoming:m,is_list:h,is_mix:d,background:c?"background-image: url("+c+")":"",views_and_publish_time:b.shortViewCount?b.shortViewCount+" \u2022 "+b.publishedTimeText:b.publishedTimeText,autoplayAlternativeHeader:b.Om};b instanceof g.MF&&(c.playlist_length=b.playlistLength);a.update(c)},L5=function(a){var b=a.V(),c=b.i;
g.V.call(this,{G:"a",L:"ytp-autonav-suggestion-card",W:{href:"{{url}}",target:c?b.I:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},U:[{G:"div",Ga:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],W:{style:"{{background}}"},U:[{G:"div",W:{"aria-label":"{{timestamp}}"},Ga:["ytp-autonav-timestamp"],xa:"{{duration}}"},{G:"div",Ga:["ytp-autonav-live-stamp"],xa:"Live"},{G:"div",
Ga:["ytp-autonav-upcoming-stamp"],xa:"Upcoming"},{G:"div",L:"ytp-autonav-list-overlay",U:[{G:"div",L:"ytp-autonav-mix-text",xa:"Mix"},{G:"div",L:"ytp-autonav-mix-icon"}]}]},{G:"div",Ga:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],xa:"{{title}}"},{G:"div",Ga:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],xa:"{{author}}"},{G:"div",Ga:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],xa:"{{views_and_publish_time}}"}]});this.J=a;this.suggestion=
null;this.i=c;this.Ra("click",this.onClick);this.Ra("keypress",this.onKeyPress)},N5=function(a,b){b=void 0===b?!1:b;
g.V.call(this,{G:"div",L:"ytp-autonav-endscreen-countdown-container"});var c=this;this.I=b;this.D=void 0;this.u=0;b=a.V();var d=b.i;this.J=a;this.suggestion=null;this.onVideoDataChange("newdata",this.J.getVideoData());this.T(a,"videodatachange",this.onVideoDataChange);this.i=new g.V({G:"div",L:"ytp-autonav-endscreen-upnext-container",W:{"aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},U:[{G:"div",
L:"ytp-autonav-endscreen-upnext-header"},{G:"div",L:"ytp-autonav-endscreen-upnext-alternative-header",xa:"{{autoplayAlternativeHeader}}"},{G:"a",L:"ytp-autonav-endscreen-link-container",W:{href:"{{url}}",target:d?b.I:""},U:[{G:"div",L:"ytp-autonav-endscreen-upnext-thumbnail",W:{style:"{{background}}"},U:[{G:"div",W:{"aria-label":"{{timestamp}}"},Ga:["ytp-autonav-timestamp"],xa:"{{duration}}"},{G:"div",Ga:["ytp-autonav-live-stamp"],xa:"Live"},{G:"div",Ga:["ytp-autonav-upcoming-stamp"],xa:"Upcoming"}]},
{G:"div",L:"ytp-autonav-endscreen-video-info",U:[{G:"div",L:"ytp-autonav-endscreen-premium-badge"},{G:"div",L:"ytp-autonav-endscreen-upnext-title",xa:"{{title}}"},{G:"div",L:"ytp-autonav-endscreen-upnext-author",xa:"{{author}}"},{G:"div",L:"ytp-autonav-view-and-date",xa:"{{views_and_publish_time}}"},{G:"div",L:"ytp-autonav-author-and-view",xa:"{{author_and_views}}"}]}]}]});g.I(this,this.i);this.i.Ea(this.element);d||this.T(this.i.Fa("ytp-autonav-endscreen-link-container"),"click",this.aI);this.J.Qb(this.element,
this,115127);this.J.Qb(this.i.Fa("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.V({G:"div",L:"ytp-autonav-overlay"});g.I(this,this.overlay);this.overlay.Ea(this.element);this.B=new g.V({G:"div",L:"ytp-autonav-endscreen-button-container"});g.I(this,this.B);this.B.Ea(this.element);this.cancelButton=new g.V({G:"button",Ga:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button"],W:{"aria-label":"Cancel autoplay"},xa:"Cancel"});g.I(this,this.cancelButton);
this.cancelButton.Ea(this.B.element);this.cancelButton.Ra("click",this.hQ,this);this.J.Qb(this.cancelButton.element,this,115129);this.playButton=new g.V({G:"a",Ga:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button"],W:{href:"{{url}}",role:"button","aria-label":"Play next video"},xa:"Play Now"});g.I(this,this.playButton);this.playButton.Ea(this.B.element);this.playButton.Ra("click",this.aI,this);this.J.Qb(this.playButton.element,this,115130);this.C=new g.J(function(){M5(c)},
500);
g.I(this,this.C);this.ZH();this.T(a,"autonavvisibility",this.ZH)},Q5=function(a){var b=a.J.jj(!0,a.J.isFullscreen());
g.N(a.element,"ytp-autonav-endscreen-small-mode",a.tf(b));g.N(a.element,"ytp-autonav-endscreen-is-premium",!!a.suggestion&&!!a.suggestion.bB);g.N(a.J.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!a.J.Xd());g.N(a.J.getRootNode(),"countdown-running",a.Ih());g.N(a.element,"ytp-player-content",a.J.Xd());g.Hl(a.overlay.element,{width:b.width+"px"});if(!a.Ih()){a.J.Xd()?O5(a,Math.round(P5(a)/1E3)):O5(a);b=!!a.suggestion&&!!a.suggestion.Om;var c=a.J.Xd()||!b;g.N(a.element,"ytp-autonav-endscreen-upnext-alternative-header-only",
!c&&b);g.N(a.element,"ytp-autonav-endscreen-upnext-no-alternative-header",c&&!b);g.MK(a.B,a.J.Xd())}},M5=function(a){var b=P5(a),c=Math,d=c.min;
var e=a.u?Date.now()-a.u:0;c=d.call(c,e,b);O5(a,Math.ceil((b-c)/1E3));500>=b-c&&a.Ih()?a.select(!0):a.Ih()&&a.C.start()},P5=function(a){var b=a.J.Cp();
return 0<=b?b:g.nE(a.J.V().experiments,"autoplay_time")||1E4},O5=function(a,b){b=void 0===b?-1:b;
a=a.i.Fa("ytp-autonav-endscreen-upnext-header");g.Ig(a);if(0<=b){b=String(b);var c="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],d="Up next in $SECONDS".indexOf(c);if(0<=d){a.appendChild(g.Hg("Up next in $SECONDS".slice(0,d)));var e=g.Gg("span");g.Nq(e,"ytp-autonav-endscreen-upnext-header-countdown-number");g.Ng(e,b);a.appendChild(e);a.appendChild(g.Hg("Up next in $SECONDS".slice(d+c.length)));return}}g.Ng(a,"Up next")},R5=function(a,b){g.V.call(this,{G:"div",
Ga:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},S5=function(a){g.V.call(this,{G:"div",
Ga:["ytp-upnext","ytp-player-content"],W:{"aria-label":"{{aria_label}}"},U:[{G:"div",L:"ytp-cued-thumbnail-overlay-image",W:{style:"{{background}}"}},{G:"span",L:"ytp-upnext-top",U:[{G:"span",L:"ytp-upnext-header",xa:"Up Next"},{G:"span",L:"ytp-upnext-title",xa:"{{title}}"},{G:"span",L:"ytp-upnext-author",xa:"{{author}}"}]},{G:"a",L:"ytp-upnext-autoplay-icon",W:{role:"button",href:"{{url}}","aria-label":"Play next video"},U:[{G:"svg",W:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
U:[{G:"circle",L:"ytp-svg-autoplay-circle",W:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{G:"circle",L:"ytp-svg-autoplay-ring",W:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{G:"path",L:"ytp-svg-fill",W:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{G:"span",L:"ytp-upnext-bottom",U:[{G:"span",L:"ytp-upnext-cancel"},{G:"span",L:"ytp-upnext-paused",
xa:"Autoplay is paused"}]}]});this.api=a;this.cancelButton=null;this.D=this.Fa("ytp-svg-autoplay-ring");this.B=this.notification=this.i=this.suggestion=null;this.C=new g.J(this.zy,5E3,this);this.u=0;var b=this.Fa("ytp-upnext-cancel");this.cancelButton=new g.V({G:"button",Ga:["ytp-upnext-cancel-button","ytp-button"],W:{tabindex:"0","aria-label":"Cancel autoplay"},xa:"Cancel"});g.I(this,this.cancelButton);this.cancelButton.Ra("click",this.iQ,this);this.cancelButton.Ea(b);this.cancelButton&&this.api.Qb(this.cancelButton.element,
this,115129);g.I(this,this.C);this.api.Qb(this.element,this,18788);b=this.Fa("ytp-upnext-autoplay-icon");this.T(b,"click",this.jQ);this.api.Qb(b,this,115130);this.bI();this.T(a,"autonavvisibility",this.bI);this.T(a,"mdxnowautoplaying",this.MU);this.T(a,"mdxautoplaycanceled",this.NU);g.N(this.element,"ytp-upnext-mobile",this.api.V().isMobile)},hRa=function(a,b){return b?b:0<=a.api.Cp()?a.api.Cp():g.nE(a.api.V().experiments,"autoplay_time")||1E4},T5=function(a,b){b=hRa(a,b);
var c=Math,d=c.min;var e=(0,g.Q)()-a.u;c=d.call(c,e,b);b=0===b?1:Math.min(c/b,1);a.D.setAttribute("stroke-dashoffset",""+-211*(b+1));1<=b&&a.Ih()&&3!==a.api.getPresentingPlayerType()?a.select(!0):a.Ih()&&a.i.start()},U5=function(a){R5.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.V({G:"div",L:"ytp-suggestion-panel",U:[{G:"div",Ga:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],xa:"More videos"}]});this.K=new g.V({G:"div",L:"ytp-suggestions-container"});this.videos=[];this.B=null;this.D=this.I=!1;this.u=new N5(this.player);g.I(this,this.u);this.u.Ea(this.element);a.getVideoData().Bc?this.i=this.u:(this.i=new S5(a),g.MM(this.player,this.i.element,4),g.I(this,this.i));this.overlay=new g.V({G:"div",
L:"ytp-autonav-overlay-cancelled-state"});g.I(this,this.overlay);this.overlay.Ea(this.element);this.C=new g.qD(this);g.I(this,this.C);g.I(this,this.table);this.table.Ea(this.element);this.table.show();g.I(this,this.K);this.K.Ea(this.table.element);this.hide()},V5=function(a){var b=a.Xd();
b!==a.D&&(a.D=b,a.player.ea("autonavvisibility"),a.D?(a.u!==a.i&&a.u.hide(),a.table.hide()):(a.u!==a.i&&a.u.show(),a.table.show()))},W5=function(a){R5.call(this,a,"subscribecard-endscreen");
this.i=new g.V({G:"div",L:"ytp-subscribe-card",U:[{G:"img",L:"ytp-author-image",W:{src:"{{profilePicture}}"}},{G:"div",L:"ytp-subscribe-card-right",U:[{G:"div",L:"ytp-author-name",xa:"{{author}}"},{G:"div",L:"html5-subscribe-button-container"}]}]});g.I(this,this.i);this.i.Ea(this.element);var b=a.getVideoData();this.subscribeButton=new g.bO("Subscribe",null,"Unsubscribe",null,!0,!1,b.Si,b.subscribed,"trailer-endscreen",null,null,a);g.I(this,this.subscribeButton);this.subscribeButton.Ea(this.i.Fa("html5-subscribe-button-container"));
this.T(a,"videodatachange",this.Qa);this.Qa();this.hide()},X5=function(a){var b=a.V(),c=g.Qi||g.RE?{style:"will-change: opacity"}:void 0,d=b.i,e=["ytp-videowall-still"];
b.isMobile&&e.push("ytp-videowall-show-text");g.V.call(this,{G:"a",Ga:e,W:{href:"{{url}}",target:d?b.I:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},U:[{G:"div",L:"ytp-videowall-still-image",W:{style:"{{background}}"}},{G:"span",L:"ytp-videowall-still-info",U:[{G:"span",L:"ytp-videowall-still-info-bg",U:[{G:"span",L:"ytp-videowall-still-info-content",W:c,U:[{G:"span",L:"ytp-videowall-still-info-title",xa:"{{title}}"},{G:"span",
L:"ytp-videowall-still-info-author",xa:"{{author_and_views}}"},{G:"span",L:"ytp-videowall-still-info-live",xa:"Live"},{G:"span",L:"ytp-videowall-still-info-duration",xa:"{{duration}}"}]}]}]},{G:"span",Ga:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],U:[{G:"span",L:"ytp-videowall-still-listlabel-icon"},"Playlist",{G:"span",L:"ytp-videowall-still-listlabel-length",U:[" (",{G:"span",xa:"{{playlist_length}}"},")"]}]},{G:"span",Ga:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],
U:[{G:"span",L:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{G:"span",L:"ytp-videowall-still-listlabel-length",xa:" (50+)"}]}]});this.suggestion=null;this.u=d;this.api=a;this.i=new g.qD(this);g.I(this,this.i);this.Ra("click",this.onClick);this.Ra("keypress",this.onKeyPress);this.i.T(a,"videodatachange",this.onVideoDataChange);a.Qg(this.element,this);this.onVideoDataChange()},Y5=function(a){R5.call(this,a,"videowall-endscreen");
var b=this;this.J=a;this.B=0;this.stills=[];this.C=this.videoData=null;this.D=this.K=!1;this.S=null;this.u=new g.qD(this);g.I(this,this.u);this.I=new g.J(function(){g.M(b.element,"ytp-show-tiles")},0);
g.I(this,this.I);var c=new g.V({G:"button",Ga:["ytp-button","ytp-endscreen-previous"],W:{"aria-label":"Previous"},U:[g.RK()]});g.I(this,c);c.Ea(this.element);c.Ra("click",this.nQ,this);this.table=new g.JK({G:"div",L:"ytp-endscreen-content"});g.I(this,this.table);this.table.Ea(this.element);c=new g.V({G:"button",Ga:["ytp-button","ytp-endscreen-next"],W:{"aria-label":"Next"},U:[g.SK()]});g.I(this,c);c.Ea(this.element);c.Ra("click",this.mQ,this);a.getVideoData().Bc?this.i=new N5(a,!0):this.i=new S5(a);
g.I(this,this.i);g.MM(this.player,this.i.element,4);this.hide()},Z5=function(a){return g.NM(a.player)&&a.Lu()&&!a.C},$5=function(a){var b=a.Xd();
b!==a.K&&(a.K=b,a.player.ea("autonavvisibility"))},a6=function(a){g.ZM.call(this,a);
var b=this;this.endScreen=null;this.i=this.u=this.B=!1;this.listeners=new g.qD(this);g.I(this,this.listeners);this.env=a.V();iRa(a)?(this.B=!0,jRa(this),this.i?this.endScreen=new U5(a):this.endScreen=new Y5(this.player)):this.env.bd?this.endScreen=new W5(this.player):this.endScreen=new R5(this.player);g.I(this,this.endScreen);g.MM(this.player,this.endScreen.element,4);kRa(this);this.listeners.T(a,"videodatachange",this.onVideoDataChange,this);this.listeners.T(a,g.jA("endscreen"),function(c){b.onCueRangeEnter(c)});
this.listeners.T(a,g.kA("endscreen"),function(c){b.onCueRangeExit(c)})},jRa=function(a){var b=a.player.getVideoData();
if(!b||a.i===b.Qh&&a.u===b.Bc)return!1;a.i=b.Qh;a.u=b.Bc;return!0},iRa=function(a){a=a.V();
return a.yb&&!a.bd},kRa=function(a){a.player.Xe("endscreen");
var b=a.player.getVideoData();b=new g.hA(Math.max(1E3*(b.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.hA(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});a.player.Ad([b,c])};
g.FM.prototype.Cp=g.ca(2,function(){return this.app.Cp()});
g.VX.prototype.Cp=g.ca(1,function(){return this.getVideoData().ML});g.v(L5,g.V);L5.prototype.select=function(){(this.J.Oj(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.tv||void 0)||this.J.N("web_player_endscreen_double_log_fix_killswitch"))&&this.J.Fb(this.element)};
L5.prototype.onClick=function(a){g.vN(a,this.J,this.i,this.suggestion.sessionData||void 0)&&this.select()};
L5.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:g.Cu(a)||(this.select(),g.Bu(a))}};g.v(N5,g.V);g.k=N5.prototype;g.k.Tx=function(a){this.suggestion!==a&&(this.suggestion=a,K5(this.i,a),this.playButton.Sa("url",this.suggestion.Dk()),Q5(this))};
g.k.Ih=function(){return 0<this.u};
g.k.zt=function(){this.Ih()||(this.u=Date.now(),M5(this),gRa(this.J,P5(this)),g.N(this.J.getRootNode(),"countdown-running",this.Ih()))};
g.k.mq=function(){this.Bm();M5(this);var a=this.i.Fa("ytp-autonav-endscreen-upnext-header");a&&g.Ng(a,"Up next")};
g.k.Bm=function(){this.Ih()&&(this.C.stop(),this.u=0)};
g.k.select=function(a){this.J.nextVideo(!1,void 0===a?!1:a);this.Bm()};
g.k.aI=function(a){g.vN(a,this.J)&&(a.currentTarget===this.playButton.element?this.J.Fb(this.playButton.element):a.currentTarget===this.i.Fa("ytp-autonav-endscreen-link-container")&&(a=this.i.Fa("ytp-autonav-endscreen-link-container"),this.J.jb(a,!0),this.J.Fb(a)),this.select())};
g.k.hQ=function(){this.J.Fb(this.cancelButton.element);g.HM(this.J,!0);this.D&&this.J.Na("innertubeCommand",this.D)};
g.k.onVideoDataChange=function(a,b){a=b.XX;this.D=null===a||void 0===a?void 0:a.command};
g.k.ZH=function(){var a=this.J.Xd();this.I&&this.zb!==a&&g.MK(this,a);Q5(this);this.J.jb(this.element,a);this.J.jb(this.cancelButton.element,a);this.J.jb(this.i.Fa("ytp-autonav-endscreen-link-container"),a);this.J.jb(this.playButton.element,a)};
g.k.tf=function(a){return 400>a.width||459>a.height};g.v(R5,g.V);g.k=R5.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.Lu=function(){return!1};
g.k.Xd=function(){return!1};
g.k.oL=function(){return!1};g.v(S5,g.V);g.k=S5.prototype;g.k.zy=function(){this.notification&&(this.C.stop(),this.hc(this.B),this.B=null,this.notification.close(),this.notification=null)};
g.k.Tx=function(a){this.suggestion=a;K5(this,a,"hqdefault.jpg")};
g.k.bI=function(){g.MK(this,this.api.Xd());this.api.jb(this.element,this.api.Xd());this.api.jb(this.Fa("ytp-upnext-autoplay-icon"),this.api.Xd());this.cancelButton&&this.api.jb(this.cancelButton.element,this.api.Xd())};
g.k.VU=function(){window.focus();this.zy()};
g.k.zt=function(a){var b=this;this.Ih()||(g.dv("a11y-announce","Up Next "+this.suggestion.title),this.u=(0,g.Q)(),this.i=new g.J(function(){T5(b,a)},25),T5(this,a),gRa(this.api,hRa(this,a)));
g.Qq(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.V.prototype.hide.call(this)};
g.k.Ih=function(){return!!this.i};
g.k.mq=function(){this.Bm();this.u=(0,g.Q)();T5(this);g.M(this.element,"ytp-upnext-autoplay-paused")};
g.k.Bm=function(){this.Ih()&&(this.i.dispose(),this.i=null)};
g.k.select=function(a){a=void 0===a?!1:a;if(this.api.V().N("autonav_notifications")&&a&&window.Notification&&"function"===typeof document.hasFocus){var b=Notification.permission;"default"===b?Notification.requestPermission():"granted"!==b||document.hasFocus()||(this.zy(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.Ke()}),this.B=this.T(this.notification,"click",this.VU),this.C.start())}this.Bm();this.api.nextVideo(!1,a)};
g.k.jQ=function(a){!g.Mg(this.cancelButton.element,g.xu(a))&&g.vN(a,this.api)&&(this.api.Xd()&&this.api.Fb(this.Fa("ytp-upnext-autoplay-icon")),this.select())};
g.k.iQ=function(){this.api.Xd()&&this.cancelButton&&this.api.Fb(this.cancelButton.element);g.HM(this.api,!0)};
g.k.MU=function(a){this.api.getPresentingPlayerType();this.show();this.zt(a)};
g.k.NU=function(){this.api.getPresentingPlayerType();this.Bm();this.hide()};
g.k.ya=function(){this.Bm();this.zy();g.V.prototype.ya.call(this)};g.v(U5,R5);g.k=U5.prototype;g.k.create=function(){R5.prototype.create.call(this);this.C.T(this.player,"appresize",this.wu);this.C.T(this.player,"onVideoAreaChange",this.wu);this.C.T(this.player,"videodatachange",this.onVideoDataChange);this.C.T(this.player,"autonavchange",this.cI);this.C.T(this.player,"autonavcancel",this.kQ);this.onVideoDataChange()};
g.k.show=function(){R5.prototype.show.call(this);(this.I||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.HM(this.player,!1);g.NM(this.player)&&this.Lu()&&!this.B?(V5(this),2===this.videoData.autonavState?this.player.V().N("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.i.select(!0):this.i.zt():3===this.videoData.autonavState&&this.i.mq()):(g.HM(this.player,!0),V5(this));this.wu()};
g.k.hide=function(){R5.prototype.hide.call(this);this.i.mq();V5(this)};
g.k.wu=function(){var a=this.player.jj(!0,this.player.isFullscreen());V5(this);Q5(this.u);g.N(this.element,"ytp-autonav-cancelled-small-mode",this.tf(a));g.N(this.element,"ytp-autonav-cancelled-tiny-mode",this.Fz(a));g.N(this.element,"ytp-autonav-cancelled-mini-mode",400>=a.width||360>=a.height);this.overlay&&g.Hl(this.overlay.element,{width:a.width+"px"});if(!this.D){a=g.r(this.videos.entries());for(var b=a.next();!b.done;b=a.next()){var c=g.r(b.value);b=c.next().value;c=c.next().value;g.N(c.element,
"ytp-suggestion-card-with-margin",1===b%2)}}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((a=this.videoData.suggestions)&&a.length){this.i.Tx(a[0]);this.i!==this.u&&this.u.Tx(a[0]);for(var b=0;b<lRa.length;++b){var c=lRa[b];if(a&&a[c]){this.videos[b]=new L5(this.player);var d=this.videos[b];c=a[c];d.suggestion!==c&&(d.suggestion=c,K5(d,c));g.I(this,this.videos[b]);this.videos[b].Ea(this.K.element)}}}this.wu()}};
g.k.cI=function(a){1===a?(this.I=!1,this.B=this.videoData.clientPlaybackNonce,this.i.Bm(),this.zb&&this.wu()):(this.I=!0,this.Xd()&&(2===a?this.i.zt():3===a&&this.i.mq()))};
g.k.kQ=function(a){a?this.cI(1):(this.B=null,this.I=!1)};
g.k.Lu=function(){return 1!==this.videoData.autonavState};
g.k.tf=function(a){return(910>a.width||459>a.height)&&!this.Fz(a)&&!(400>=a.width||360>=a.height)};
g.k.Fz=function(a){return 800>a.width&&!(400>=a.width||360>=a.height)};
g.k.Xd=function(){return this.zb&&g.NM(this.player)&&this.Lu()&&!this.B};
var lRa=[1,3,2,4];g.v(W5,R5);W5.prototype.Qa=function(){var a=this.player.getVideoData();this.i.update({profilePicture:a.Ph,author:a.author});this.subscribeButton.channelId=a.Si;var b=this.subscribeButton;a.subscribed?b.u():b.B()};g.v(X5,g.V);X5.prototype.select=function(){(this.api.Oj(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.tv||void 0)||this.api.N("web_player_endscreen_double_log_fix_killswitch"))&&this.api.Fb(this.element)};
X5.prototype.onClick=function(a){g.vN(a,this.api,this.u,this.suggestion.sessionData||void 0)&&this.select()};
X5.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:g.Cu(a)||(this.select(),g.Bu(a))}};
X5.prototype.onVideoDataChange=function(){var a=this.api.getVideoData(),b=this.api.V();this.u=a.D?!1:b.i};g.v(Y5,R5);g.k=Y5.prototype;g.k.create=function(){R5.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.videoData=a);this.il();this.u.T(this.player,"appresize",this.il);this.u.T(this.player,"onVideoAreaChange",this.il);this.u.T(this.player,"videodatachange",this.onVideoDataChange);this.u.T(this.player,"autonavchange",this.hC);this.u.T(this.player,"autonavcancel",this.lQ);a=this.videoData.autonavState;a!==this.S&&this.hC(a);this.u.T(this.element,"transitionend",this.lW)};
g.k.destroy=function(){g.iy(this.u);(0,g.we)(this.stills);this.stills=[];R5.prototype.destroy.call(this);g.Qq(this.element,"ytp-show-tiles");this.I.stop();this.S=this.videoData.autonavState};
g.k.Lu=function(){return 1!==this.videoData.autonavState};
g.k.show=function(){R5.prototype.show.call(this);g.Qq(this.element,"ytp-show-tiles");this.player.V().isMobile?g.Iq(this.I):this.I.start();(this.D||this.C&&this.C!==this.videoData.clientPlaybackNonce)&&g.HM(this.player,!1);Z5(this)?($5(this),2===this.videoData.autonavState?this.player.V().N("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.i.select(!0):this.i.zt():3===this.videoData.autonavState&&this.i.mq()):(g.HM(this.player,!0),$5(this))};
g.k.hide=function(){R5.prototype.hide.call(this);this.i.mq();$5(this)};
g.k.lW=function(a){g.xu(a)===this.element&&this.il()};
g.k.il=function(){if(this.videoData&&this.videoData.suggestions&&this.videoData.suggestions.length){g.M(this.element,"ytp-endscreen-paginate");var a=this.J.jj(!0,this.J.isFullscreen()),b=g.CM(this.J);b&&(b=b.Te()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),h=Math.max(a.height/54,2),l=this.videoData.suggestions.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<h);){var p=b/2,q=e/2,t=b<=f-2&&n>=q*m,u=e<=h-2&&n>=p*m;if((p+
1)/q*d/c>c/(p/(q+1)*d)&&u)n-=p*m,e+=2;else if(t)n-=q*m,b+=2;else if(u)n-=p*m,e+=2;else break}d=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m=Math.floor(Math.min(a.width,m*c));n=Math.floor(Math.min(a.height,n*c));a=this.table.element;g.Vl(a,m,n);g.Hl(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});this.i.Tx(this.videoData.suggestions[0]);this.i instanceof N5&&Q5(this.i);g.N(this.element,"ytp-endscreen-takeover",Z5(this));$5(this);m+=4;n+=4;for(f=
c=0;f<b;f++)for(h=0;h<e;h++)if(p=c,q=0,d&&f>=b-2&&h>=e-2?q=1:0===h%2&&0===f%2&&(2>h&&2>f?0===h&&0===f&&(q=2):q=2),p=g.Yf(p+this.B,l),0!==q){t=this.stills[c];t||(t=new X5(this.player),this.stills[c]=t,a.appendChild(t.element));u=Math.floor(n*h/e);var x=Math.floor(m*f/b),y=Math.floor(n*(h+q)/e)-u-4,z=Math.floor(m*(f+q)/b)-x-4;g.Ol(t.element,x,u);g.Vl(t.element,z,y);g.Hl(t.element,"transitionDelay",(h+f)/20+"s");g.N(t.element,"ytp-videowall-still-mini",1===q);g.N(t.element,"ytp-videowall-still-large",
2<q);q=t;p=this.videoData.suggestions[p];q.suggestion!==p&&(q.suggestion=p,t=q.api.V(),u=g.Oq(q.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",K5(q,p,u),g.TE(t)&&(t=p.Dk(),t=g.ni(t,g.uM("emb_rel_end")),q.Sa("url",t)),(p=(p=p.sessionData)&&p.itct)&&q.api.zm(q.element,p));c++}g.N(this.element,"ytp-endscreen-paginate",c<l);for(b=this.stills.length-1;b>=c;b--)e=this.stills[b],g.Kg(e.element),(0,g.ve)(e);this.stills.length=c}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.B=0,this.videoData=a,this.il())};
g.k.mQ=function(){this.B+=this.stills.length;this.il()};
g.k.nQ=function(){this.B-=this.stills.length;this.il()};
g.k.oL=function(){return this.i.Ih()};
g.k.hC=function(a){1===a?(this.D=!1,this.C=this.videoData.clientPlaybackNonce,this.i.Bm(),this.zb&&this.il()):(this.D=!0,this.zb&&Z5(this)&&(2===a?this.i.zt():3===a&&this.i.mq()))};
g.k.lQ=function(a){if(a){for(a=0;a<this.stills.length;a++)this.J.jb(this.stills[a].element,!0);this.hC(1)}else this.C=null,this.D=!1;this.il()};
g.k.Xd=function(){return this.zb&&Z5(this)};g.v(a6,g.ZM);g.k=a6.prototype;g.k.Cq=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!iRa(this.player)||b;var c=a.Ye||g.dF(a.C),d=this.player.yv();a=a.mutedAutoplay;return b&&!c&&!d&&!a};
g.k.Xd=function(){return this.endScreen.Xd()};
g.k.LS=function(){return this.Xd()?this.endScreen.oL():!1};
g.k.ya=function(){this.player.Xe("endscreen");g.ZM.prototype.ya.call(this)};
g.k.load=function(){var a=this.player.getVideoData();var b=a.AK;if(b&&b.videoId){var c=this.player.vb().Ed.get("heartbeat");a&&a.suggestions&&a.suggestions.length&&b.videoId===a.suggestions[0].videoId&&!a.qI?a=!1:(this.player.Oj(b.videoId,void 0,void 0,!0,!0,b),c&&c.Oz("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0)}else a=!1;a||(g.ZM.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.ZM.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.onCueRangeEnter=function(a){this.Cq()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.k.onCueRangeExit=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.k.onVideoDataChange=function(){kRa(this);this.B&&jRa(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.i?this.endScreen=new U5(this.player):this.endScreen=new Y5(this.player),g.I(this,this.endScreen),g.MM(this.player,this.endScreen.element,4))};g.YM("endscreen",a6);})(_yt_player);
