(function(g){var window=this;'use strict';var bSa=function(a,b){return g.lc(a,b)},cSa=function(a,b){b=b instanceof g.vf?b:g.Bf(b,/^data:image\//i.test(b));
a.src=g.wf(b)},O6=function(a){g.Rj(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^g.Qa()).toString(36));
return a},P6=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.Wj(a.u,b,c)},dSa=function(a){if(a instanceof g.eo)return a;
if("function"==typeof a.Kg)return a.Kg(!1);if(g.La(a)){var b=0,c=new g.eo;c.vj=function(){for(;;){if(b>=a.length)throw g.Yq;if(b in a)return a[b++];b++}};
return c}throw Error("Not implemented");},eSa=function(a,b,c){if(g.La(a))try{g.Rb(a,b,c)}catch(d){if(d!==g.Yq)throw d;
}else{a=dSa(a);try{for(;;)b.call(c,a.vj(),void 0,a)}catch(d){if(d!==g.Yq)throw d;}}},fSa=function(a,b){var c=[];
eSa(b,function(d){try{var e=g.yr.prototype.u.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.xr(e)&&c.push(d)},a);
return c},gSa=function(a,b){fSa(a,b).forEach(function(c){g.yr.prototype.remove.call(this,c)},a)},hSa=function(a){if(a.va){if(a.va.locationOverrideToken)return{locationOverrideToken:a.va.locationOverrideToken};
if(null!=a.va.latitudeE7&&null!=a.va.longitudeE7)return{latitudeE7:a.va.latitudeE7,longitudeE7:a.va.longitudeE7}}return null},iSa=function(a,b){g.vb(a,b)||a.push(b)},Q6=function(a){var b=0,c;
for(c in a)b++;return b},jSa=function(a){try{return g.B.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},R6=function(a){if(g.B.JSON)try{return g.B.JSON.parse(a)}catch(b){}return jSa(a)},kSa=function(a,b,c,d){var e=new g.Jj(null,void 0);
a&&g.Kj(e,a);b&&g.Lj(e,b);c&&g.Mj(e,c);d&&(e.K=d);return e},S6=function(a,b){g.$u[a]=!0;
var c=g.Yu();c&&c.publish.apply(c,arguments);g.$u[a]=!1},T6=function(a){this.name=this.id="";
this.clientName="UNKNOWN_INTERFACE";this.app="";this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Zq;this.model=this.brand="";this.year=0;this.chipset=this.osVersion=this.os="";this.mdxDialServerType="MDX_DIAL_SERVER_TYPE_UNKNOWN";a&&(this.id=a.id||a.name,this.name=a.name,this.clientName=a.clientName?a.clientName.toUpperCase():"UNKNOWN_INTERFACE",this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=
a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",lSa(this,a.capabilities||""),mSa(this,a.experiments||""),this.brand=a.brand||"",this.model=a.model||"",this.year=a.year||0,this.os=a.os||"",this.osVersion=a.osVersion||"",this.chipset=a.chipset||"",this.mdxDialServerType=a.mdxDialServerType||"MDX_DIAL_SERVER_TYPE_UNKNOWN",a=a.deviceInfo)&&(a=JSON.parse(a),this.brand=a.brand||"",this.model=a.model||"",this.year=a.year||0,this.os=a.os||"",
this.osVersion=a.osVersion||"",this.chipset=a.chipset||"",this.clientName=a.clientName?a.clientName.toUpperCase():"UNKNOWN_INTERFACE",this.mdxDialServerType=a.mdxDialServerType||"MDX_DIAL_SERVER_TYPE_UNKNOWN")},lSa=function(a,b){a.capabilities.clear();
g.Do(b.split(","),g.Pa(bSa,nSa)).forEach(function(c){a.capabilities.add(c)})},mSa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},U6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||"";this.idType=a.screenIdType||"normal"},V6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},oSa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid,screenIdType:a.idType}},pSa=function(a){return new U6(a)},qSa=function(a){return Array.isArray(a)?g.jm(a,pSa):[]},W6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+((a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+",idType:"+a.idType+"}"):"null"},X6=function(a){return Array.isArray(a)?"["+g.jm(a,W6).join(",")+"]":"null"},Y6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,
function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},rSa=function(a){return g.jm(a,function(b){return{key:b.id,
name:b.name}})},Z6=function(a,b){return g.sb(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},$6=function(a,b){return g.sb(a,function(c){return V6(c,b)})},sSa=function(){var a=(0,g.Ez)();
a&&gSa(a,a.i.Kg(!0))},a7=function(){var a=g.Hz("yt-remote-connected-devices")||[];
g.Nb(a);return a},tSa=function(a){if(g.wb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return g.jm(a,function(d,e){return 0==e?d:d.substring(c.length)})},uSa=function(a){g.Gz("yt-remote-connected-devices",a,86400)},c7=function(){if(b7)return b7;
var a=g.Hz("yt-remote-device-id");a||(a=Y6(),g.Gz("yt-remote-device-id",a,31536E3));for(var b=a7(),c=1,d=a;g.vb(b,d);)c++,d=a+"#"+c;return b7=d},d7=function(){var a=a7(),b=c7();
g.vb(a,b);g.Jz()&&g.Qb(a,b);a=tSa(a);if(g.wb(a))try{g.Kt("remote_sid")}catch(c){}else try{g.It("remote_sid",a.join(","),-1)}catch(c){}},vSa=function(){return g.Hz("yt-remote-session-browser-channel")},wSa=function(){return g.Hz("yt-remote-local-screens")||[]},xSa=function(){g.Gz("yt-remote-lounge-token-expiration",!0,86400)},ySa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=g.jm(wSa(),function(d){return d.loungeToken}),c=g.jm(a,function(d){return d.loungeToken});
g.km(c,function(d){return!g.vb(b,d)})&&xSa();
g.Gz("yt-remote-local-screens",a,31536E3)},zSa=function(a,b){g.Gz("yt-remote-session-browser-channel",a);
g.Gz("yt-remote-session-screen-id",b);a=a7();b=c7();g.vb(a,b)||a.push(b);uSa(a);d7()},e7=function(a){a||(g.Iz("yt-remote-session-screen-id"),g.Iz("yt-remote-session-video-id"));
d7();a=a7();g.Ab(a,c7());uSa(a)},ASa=function(){if(!f7){var a=g.Ir();
a&&(f7=new g.sr(a))}},BSa=function(){ASa();
return f7?!!f7.get("yt-remote-use-staging-server"):!1},g7=function(){var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);
return a?parseInt(a[1],10):0},CSa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},DSa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},h7=function(a){a.length?ESa(a.shift(),function(){h7(a)}):i7()},FSa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},ESa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);g.Ok(d,g.gr(a));(document.head||document.documentElement).appendChild(d)},GSa=function(){var a=g7(),b=[];
if(1<a){var c=a-1;b.push("//www.gstatic.com/eureka/clank/"+a+"/cast_sender.js");b.push("//www.gstatic.com/eureka/clank/"+c+"/cast_sender.js")}return b},i7=function(){var a=DSa();
a&&a(!1,"No cast extension found")},j7=function(){if(HSa){var a=2,b=DSa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;ESa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",i7,c)}},ISa=function(){j7();
var a=GSa();a.push("//www.gstatic.com/eureka/clank/cast_sender.js");h7(a)},KSa=function(){j7();
var a=GSa();a.push.apply(a,g.ma(JSa.map(FSa)));a.push("//www.gstatic.com/eureka/clank/cast_sender.js");h7(a)},k7=function(a,b,c){g.H.call(this);
this.I=null!=c?(0,g.D)(a,c):a;this.Tf=b;this.D=(0,g.D)(this.tQ,this);this.i=!1;this.u=0;this.B=this.Kb=null;this.C=[]},l7=function(a,b,c){g.H.call(this);
this.C=null!=c?a.bind(c):a;this.Tf=b;this.B=null;this.i=!1;this.u=0;this.Kb=null},m7=function(a){a.Kb=g.th(function(){a.Kb=null;
a.i&&!a.u&&(a.i=!1,m7(a))},a.Tf);
var b=a.B;a.B=null;a.C.apply(null,b)},n7=function(){},o7=function(a,b){if("function"!==typeof a)throw Error("Fn must not be null and must be a function");
return g.B.setTimeout(function(){a()},b)},q7=function(a){p7.dispatchEvent(new LSa(p7,a))},LSa=function(a,b){g.ye.call(this,"statevent",a);
this.stat=b},r7=function(a,b,c,d){this.i=a;
this.B=b;this.S=c;this.K=d||1;this.u=45E3;this.C=new g.Xj(this);this.I=new g.sh;this.I.setInterval(250)},NSa=function(a,b,c){a.Ft=1;
a.Qm=O6(b.clone());a.rq=c;a.D=!0;MSa(a,null)},s7=function(a,b,c,d,e){a.Ft=1;
a.Qm=O6(b.clone());a.rq=null;a.D=c;e&&(a.LN=!1);MSa(a,d)},MSa=function(a,b){a.nt=Date.now();
t7(a);a.zo=a.Qm.clone();P6(a.zo,"t",a.K);a.vB=0;a.Mf=a.i.nD(a.i.mx()?b:null);0<a.jC&&(a.IA=new l7((0,g.D)(a.PO,a,a.Mf),a.jC));a.C.Ra(a.Mf,"readystatechange",a.uQ);b=a.To?g.sc(a.To):{};a.rq?(a.sB="POST",b["Content-Type"]="application/x-www-form-urlencoded",a.Mf.send(a.zo,a.sB,a.rq,b)):(a.sB="GET",a.LN&&!g.Bg&&(b.Connection="close"),a.Mf.send(a.zo,a.sB,null,b));a.i.wj(1)},PSa=function(a,b){var c=a.vB,d=b.indexOf("\n",c);
if(-1==d)return u7;c=Number(b.substring(c,d));if(isNaN(c))return OSa;d+=1;if(d+c>b.length)return u7;b=b.substr(d,c);a.vB=d+c;return b},RSa=function(a,b){a.nt=Date.now();
t7(a);var c=b?window.location.hostname:"";a.zo=a.Qm.clone();g.Rj(a.zo,"DOMAIN",c);g.Rj(a.zo,"t",a.K);try{a.Mj=new ActiveXObject("htmlfile")}catch(m){v7(a);a.Km=7;q7(22);w7(a);return}var d="<html><body>";if(b){var e="";for(b=0;b<c.length;b++){var f=c.charAt(b);if("<"==f)f=e+"\\x3c";else if(">"==f)f=e+"\\x3e";else{if(f in x7)f=x7[f];else if(f in QSa)f=x7[f]=QSa[f];else{var h=f.charCodeAt(0);if(31<h&&127>h)var l=f;else{if(256>h){if(l="\\x",16>h||256<h)l+="0"}else l="\\u",4096>h&&(l+="0");l+=h.toString(16).toUpperCase()}f=
x7[f]=l}f=e+f}e=f}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.Rf(g.mf("b/12014412"),d);a.Mj.open();a.Mj.write(g.Nf(c));a.Mj.close();a.Mj.parentWindow.m=(0,g.D)(a.oW,a);a.Mj.parentWindow.d=(0,g.D)(a.VM,a,!0);a.Mj.parentWindow.rpcClose=(0,g.D)(a.VM,a,!1);c=a.Mj.createElement("DIV");a.Mj.parentWindow.document.body.appendChild(c);d=g.Af(a.zo.toString());d=g.hg(g.wf(d));d=g.Rf(g.mf("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Tf(c,d);a.i.wj(1)},t7=function(a){a.eH=Date.now()+
a.u;
SSa(a,a.u)},SSa=function(a,b){if(null!=a.Qt)throw Error("WatchDog timer not null");
a.Qt=o7((0,g.D)(a.vW,a),b)},y7=function(a){a.Qt&&(g.B.clearTimeout(a.Qt),a.Qt=null)},w7=function(a){a.i.qf()||a.mp||a.i.Vx(a)},v7=function(a){y7(a);
g.ve(a.IA);a.IA=null;a.I.stop();g.Zj(a.C);if(a.Mf){var b=a.Mf;a.Mf=null;b.abort();b.dispose()}a.Mj&&(a.Mj=null)},z7=function(a,b){try{a.i.OM(a,b),a.i.wj(4)}catch(c){}},USa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;TSa(a,b,function(h){h?c(!0):g.B.setTimeout(function(){USa(a,b,c,d,f)},f)})}},TSa=function(a,b,c){var d=new Image;
d.onload=function(){try{A7(d),c(!0)}catch(e){}};
d.onerror=function(){try{A7(d),c(!1)}catch(e){}};
d.onabort=function(){try{A7(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{A7(d),c(!1)}catch(e){}};
g.B.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
cSa(d,a)},A7=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},VSa=function(a){this.i=a;
this.u=new n7},WSa=function(a){var b=B7(a.i,a.Nu,"/mail/images/cleardot.gif");
O6(b);USa(b.toString(),5E3,(0,g.D)(a.lR,a),3,2E3);a.wj(1)},D7=function(a){var b=a.i.X;
if(null!=b)q7(5),b?(q7(11),C7(a.i,a,!1)):(q7(12),C7(a.i,a,!0));else if(a.lh=new r7(a,void 0,void 0,void 0),a.lh.To=a.kC,b=a.i,b=B7(b,b.mx()?a.yu:null,a.lC),q7(5),!g.Tc||g.Nc(10))P6(b,"TYPE","xmlhttp"),s7(a.lh,b,!1,a.yu,!1);else{P6(b,"TYPE","html");var c=a.lh;a=!!a.yu;c.Ft=3;c.Qm=O6(b.clone());RSa(c,a)}},E7=function(a,b,c){this.i=1;
this.u=[];this.C=[];this.D=new n7;this.S=a||null;this.X=null!=b?b:null;this.I=c||!1},XSa=function(a,b){this.i=a;
this.map=b;this.context=null},YSa=function(a,b,c,d){g.ye.call(this,"timingevent",a);
this.size=b;this.ax=d},ZSa=function(a){g.ye.call(this,"serverreachability",a)},bTa=function(a){$Sa(a);
if(3==a.i){var b=a.pw++,c=a.Py.clone();g.Rj(c,"SID",a.B);g.Rj(c,"RID",b);g.Rj(c,"TYPE","terminate");F7(a,c);b=new r7(a,a.B,b,void 0);b.Ft=2;b.Qm=O6(c.clone());cSa(new Image,b.Qm.toString());b.nt=Date.now();t7(b)}aTa(a)},cTa=function(a){a.LR(1,0);
a.Py=B7(a,null,a.mC);G7(a)},$Sa=function(a){a.Um&&(a.Um.abort(),a.Um=null);
a.Je&&(a.Je.cancel(),a.Je=null);a.Al&&(g.B.clearTimeout(a.Al),a.Al=null);H7(a);a.Ug&&(a.Ug.cancel(),a.Ug=null);a.jn&&(g.B.clearTimeout(a.jn),a.jn=null)},dTa=function(a,b){if(0==a.i)throw Error("Invalid operation: sending map when state is closed");
a.u.push(new XSa(a.qT++,b));2!=a.i&&3!=a.i||G7(a)},eTa=function(a){var b=0;
a.Je&&b++;a.Ug&&b++;return b},G7=function(a){a.Ug||a.jn||(a.jn=o7((0,g.D)(a.TM,a),0),a.Wr=0)},gTa=function(a,b){if(1==a.i){if(!b){a.pw=Math.floor(1E5*Math.random());
b=a.pw++;var c=new r7(a,"",b,void 0);c.To=a.Xj;var d=I7(a),e=a.Py.clone();g.Rj(e,"RID",b);g.Rj(e,"CVER","1");F7(a,e);NSa(c,e,d);a.Ug=c;a.i=2}}else 3==a.i&&(b?fTa(a,b):0==a.u.length||a.Ug||fTa(a))},fTa=function(a,b){if(b)if(6<a.np){a.u=a.C.concat(a.u);
a.C.length=0;var c=a.pw-1;b=I7(a)}else c=b.S,b=b.rq;else c=a.pw++,b=I7(a);var d=a.Py.clone();g.Rj(d,"SID",a.B);g.Rj(d,"RID",c);g.Rj(d,"AID",a.Js);F7(a,d);c=new r7(a,a.B,c,a.Wr+1);c.To=a.Xj;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Ug=c;NSa(c,d,b)},F7=function(a,b){a.Nf&&(a=a.Nf.jK())&&g.Zb(a,function(c,d){g.Rj(b,d,c)})},I7=function(a){var b=Math.min(a.u.length,1E3),c=["count="+b];
if(6<a.np&&0<b){var d=a.u[0].i;c.push("ofs="+d)}else d=0;for(var e={},f=0;f<b;e={Tq:e.Tq},f++){e.Tq=a.u[f].i;var h=a.u[f].map;e.Tq=6>=a.np?f:e.Tq-d;try{g.Zb(h,function(l){return function(m,n){c.push("req"+l.Tq+"_"+n+"="+encodeURIComponent(m))}}(e))}catch(l){c.push("req"+e.Tq+"_type="+encodeURIComponent("_badmap"))}}a.C=a.C.concat(a.u.splice(0,b));
return c.join("&")},hTa=function(a){a.Je||a.Al||(a.K=1,a.Al=o7((0,g.D)(a.SM,a),0),a.Gr=0)},J7=function(a){if(a.Je||a.Al||3<=a.Gr)return!1;
a.K++;a.Al=o7((0,g.D)(a.SM,a),iTa(a,a.Gr));a.Gr++;return!0},C7=function(a,b,c){a.qB=c;
a.Yj=b.jl;a.I||cTa(a)},H7=function(a){null!=a.yp&&(g.B.clearTimeout(a.yp),a.yp=null)},iTa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},K7=function(a,b){if(2==b||9==b){var c=null;
a.Nf&&(c=null);var d=(0,g.D)(a.yX,a);c||(c=new g.Jj("//www.google.com/images/cleardot.gif"),O6(c));TSa(c.toString(),1E4,d)}else q7(2);jTa(a,b)},jTa=function(a,b){a.i=0;
a.Nf&&a.Nf.xJ(b);aTa(a);$Sa(a)},aTa=function(a){a.i=0;
a.Yj=-1;if(a.Nf)if(0==a.C.length&&0==a.u.length)a.Nf.aD();else{g.Db(a.C);var b=g.Db(a.u);a.C.length=0;a.u.length=0;a.Nf.aD(b)}},B7=function(a,b,c){var d=g.Sj(c);
if(""!=d.i)b&&g.Lj(d,b+"."+d.i),g.Mj(d,d.B);else{var e=window.location;d=kSa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.vv&&g.Zb(a.vv,function(f,h){g.Rj(d,h,f)});
g.Rj(d,"VER",a.np);F7(a,d);return d},kTa=function(){},lTa=function(){this.i=[];
this.u=[]},mTa=function(a,b){this.action=a;
this.params=b||{}},L7=function(a,b){g.H.call(this);
this.i=new g.J(this.fW,0,this);g.I(this,this.i);this.Tf=5E3;this.u=0;if("function"===typeof a)b&&(a=(0,g.D)(a,b));else if(a&&"function"===typeof a.handleEvent)a=(0,g.D)(a.handleEvent,a);else throw Error("Invalid listener argument");this.B=a},M7=function(a,b,c,d,e){c=void 0===c?!1:c;
d=void 0===d?function(){return""}:d;
e=void 0===e?!1:e;this.va=a;this.I=b;this.B=new g.rr;this.u=new L7(this.cX,this);this.i=null;this.ma=!1;this.D=null;this.X="";this.S=this.C=0;this.K=[];this.Aa=c;this.Z=d;this.Ba=e},nTa=function(a){return{firstTestResults:[""],
secondTestResults:!a.i.qB,sessionId:a.i.B,arrayId:a.i.Js}},oTa=function(a,b){a.S=b||0;
a.u.stop();N7(a);a.i&&(3==a.i.getState()&&gTa(a.i),bTa(a.i));a.S=0},O7=function(a){return!!a.i&&3==a.i.getState()},N7=function(a){if(a.i){var b=a.Z(),c=a.i.Xj||{};
b?c["x-youtube-lounge-xsrf-token"]=b:delete c["x-youtube-lounge-xsrf-token"];a.i.Xj=c}},P7=function(a){this.port=this.domain="";
this.i="/api/lounge";this.u=!0;a=a||document.location.href;var b=Number(g.bi(4,a))||"";b&&(this.port=":"+b);this.domain=g.ci(a)||"";a=g.Xb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.pb(a,"10.0")&&(this.u=!1))},Q7=function(a,b){var c=a.i;
a.u&&(c="https://"+a.domain+a.port+a.i);return g.ni(c+b,{})},R7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Pa(a.C,d,!0),onError:g.Pa(a.B,e),onTimeout:g.Pa(a.D,e)};c&&(a.postParams=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.wt(b,a)},sTa=function(){var a=pTa;
qTa();S7.push(a);rTa()},T7=function(a,b){qTa();
var c=tTa(a,String(b));g.wb(S7)?uTa(c):(rTa(),g.Rb(S7,function(d){d(c)}))},qTa=function(){S7||(S7=g.Ha("yt.mdx.remote.debug.handlers_")||[],g.Ga("yt.mdx.remote.debug.handlers_",S7,void 0))},uTa=function(a){var b=(U7+1)%50;
U7=b;V7[b]=a;W7||(W7=49==b)},rTa=function(){var a=S7;
if(V7[0]){var b=W7?U7:-1;do{b=(b+1)%50;var c=V7[b];g.Rb(a,function(d){d(c)})}while(b!=U7);
V7=Array(50);U7=-1;W7=!1}},tTa=function(a,b){var c=(Date.now()-vTa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},X7=function(a){g.R.call(this);
this.I=a;this.screens=[]},wTa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c)return a=c.name,c.id=b.id||c.id,c.name=b.name,c.token=b.token,c.uuid=b.uuid||c.uuid,c.name!=a;a.screens.push(b);return!0},xTa=function(a,b){var c=a.screens.length!=b.length;
a.screens=g.Do(a.screens,function(f){return!!Z6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=wTa(a,b[d])||c;return c},yTa=function(a,b){var c=a.screens.length;
a.screens=g.Do(a.screens,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.screens.length<c},Y7=function(a,b,c,d,e){g.R.call(this);
this.B=a;this.K=b;this.C=c;this.I=d;this.D=e;this.u=0;this.i=null;this.Kb=NaN},$7=function(a){X7.call(this,"LocalScreenService");
this.u=a;this.i=NaN;Z7(this);this.info("Initializing with "+X6(this.screens))},zTa=function(a){if(a.screens.length){var b=g.jm(a.screens,function(d){return d.id}),c=Q7(a.u,"/pairing/get_lounge_token_batch");
R7(a.u,c,{screen_ids:b.join(",")},(0,g.D)(a.iS,a),(0,g.D)(a.hS,a))}},Z7=function(a){if(g.P("deprecate_pair_servlet_enabled"))return xTa(a,[]);
var b=qSa(wSa());b=g.Do(b,function(c){return!c.uuid});
return xTa(a,b)},a8=function(a,b){ySa(g.jm(a.screens,oSa));
b&&xSa()},c8=function(a,b){g.R.call(this);
this.I=b;b=(b=g.Hz("yt-remote-online-screen-ids")||"")?b.split(","):[];for(var c={},d=this.I(),e=0,f=d.length;e<f;++e){var h=d[e].id;c[h]=g.vb(b,h)}this.i=c;this.D=a;this.B=this.C=NaN;this.u=null;b8("Initialized with "+g.Rh(this.i))},d8=function(a,b,c){var d=Q7(a.D,"/pairing/get_screen_availability");
R7(a.D,d,{lounge_token:b.token},(0,g.D)(function(e){e=e.screens||[];for(var f=0,h=e.length;f<h;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.D)(function(){c(!1)},a))},e8=function(a,b){a:if(Q6(b)!=Q6(a.i))var c=!1;
else{c=g.ic(b);for(var d=0,e=c.length;d<e;++d)if(!a.i[c[d]]){c=!1;break a}c=!0}c||(b8("Updated online screens: "+g.Rh(a.i)),a.i=b,a.ea("screenChange"));ATa(a)},f8=function(a){isNaN(a.B)||g.Zs(a.B);
a.B=g.Xs((0,g.D)(a.UF,a),0<a.C&&a.C<g.Qa()?2E4:1E4)},b8=function(a){T7("OnlineScreenService",a)},BTa=function(a){var b={};
g.Rb(a.I(),function(c){c.token?b[c.token]=c.id:this.ke("Requesting availability of screen w/o lounge token.")});
return b},ATa=function(a){a=g.ic(g.$b(a.i,function(b){return b}));
g.Nb(a);a.length?g.Gz("yt-remote-online-screen-ids",a.join(","),60):g.Iz("yt-remote-online-screen-ids")},g8=function(a,b){b=void 0===b?!1:b;
X7.call(this,"ScreenService");this.C=a;this.K=b;this.i=this.u=null;this.B=[];this.D={};CTa(this)},ETa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.D[b]);var h=a.Fh(),l=c?$6(h,c):null;c&&(a.K||l)||(l=$6(h,b));if(l){l.uuid=b;var m=h8(a,l);d8(a.i,m,function(n){e(n?m:null)})}else c?DTa(a,c,(0,g.D)(function(n){var p=h8(this,new U6({name:d,
screenId:c,loungeToken:n,dialId:b||""}));d8(this.i,p,function(q){e(q?p:null)})},a),f):e(null)},FTa=function(a,b){for(var c=0,d=a.screens.length;c<d;++c)if(a.screens[c].name==b)return a.screens[c];
return null},GTa=function(a,b,c){d8(a.i,b,c)},DTa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={postParams:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,h){f=h&&h.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.wt(Q7(a.C,"/pairing/get_lounge_token_batch"),e)},HTa=function(a){a.screens=a.u.Fh();
var b=a.D,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.screens.length;b<d;++b){var e=a.screens[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+X6(a.screens))},CTa=function(a){i8(a);
a.u=new $7(a.C);a.u.subscribe("screenChange",(0,g.D)(a.rS,a));HTa(a);a.K||(a.B=qSa(g.Hz("yt-remote-automatic-screen-cache")||[]));i8(a);a.info("Initializing automatic screens: "+X6(a.B));a.i=new c8(a.C,(0,g.D)(a.Fh,a,!0));a.i.subscribe("screenChange",(0,g.D)(function(){this.ea("onlineScreenChange")},a))},h8=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=$6(a.B,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.B.push(b),a.K||ITa(a));i8(a);a.D[b.uuid]=b.id;g.Gz("yt-remote-device-id-map",a.D,31536E3);return b},ITa=function(a){a=g.Do(a.B,function(b){return"shortLived"!=b.idType});
g.Gz("yt-remote-automatic-screen-cache",g.jm(a,oSa))},i8=function(a){a.D=g.Hz("yt-remote-device-id-map")||{}},j8=function(a,b,c){g.R.call(this);
this.Ba=c;this.B=a;this.i=b;this.C=null},k8=function(a,b){a.C=b;
a.ea("sessionScreen",a.C)},JTa=function(a,b){a.C&&(a.C.token=b,h8(a.B,a.C));
a.ea("sessionScreen",a.C)},l8=function(a,b){T7(a.Ba,b)},m8=function(a,b,c){j8.call(this,a,b,"CastSession");
var d=this;this.config_=c;this.u=null;this.Z=(0,g.D)(this.zQ,this);this.Aa=(0,g.D)(this.zW,this);this.ma=g.Xs(function(){KTa(d,null)},12E4);
this.K=this.D=this.I=this.S=0;this.va=!1;this.X="unknown"},n8=function(a,b){g.Zs(a.K);
a.K=0;0==b?LTa(a):a.K=g.Xs(function(){LTa(a)},b)},LTa=function(a){MTa(a,"getLoungeToken");
g.Zs(a.D);a.D=g.Xs(function(){NTa(a,null)},3E4)},MTa=function(a,b){a.info("sendYoutubeMessage_: "+b+" "+g.Rh(void 0));
var c={};c.type=b;a.u?a.u.sendMessage("urn:x-cast:com.google.youtube.mdx",c,g.Ia,(0,g.D)(function(){l8(this,"Failed to send message: "+b+".")},a)):l8(a,"Sending yt message without session: "+g.Rh(c))},o8=function(a,b){b?(a.info("onConnectedScreenId_: Received screenId: "+b),a.getScreen()&&a.getScreen().id==b||a.xK(b,function(c){k8(a,c)},function(){return a.xg()},5)):a.xg(Error("Waiting for session status timed out."))},PTa=function(a,b,c){a.info("onConnectedScreenData_: Received screenData: "+JSON.stringify(b));
var d=new U6(b);OTa(a,d,function(e){e?(a.va=!0,h8(a.B,d),k8(a,d),a.X="unknown",n8(a,c)):(g.Cs(Error("CastSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online.")),a.xg())},5)},KTa=function(a,b){g.Zs(a.ma);
a.ma=0;b?a.config_.enableCastLoungeToken&&b.loungeToken?b.deviceId?a.getScreen()&&a.getScreen().uuid==b.deviceId||(b.loungeTokenRefreshIntervalMs?PTa(a,{name:a.i.friendlyName,screenId:b.screenId,loungeToken:b.loungeToken,dialId:b.deviceId,screenIdType:"shortLived"},b.loungeTokenRefreshIntervalMs):(g.Cs(Error("No loungeTokenRefreshIntervalMs presents in mdxSessionStatusData: "+JSON.stringify(b)+".")),o8(a,b.screenId))):(g.Cs(Error("No device id presents in mdxSessionStatusData: "+JSON.stringify(b)+
".")),o8(a,b.screenId)):o8(a,b.screenId):a.xg(Error("Waiting for session status timed out."))},NTa=function(a,b){g.Zs(a.D);
a.D=0;var c=null;if(b)if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";else c="noLoungeTokenResponse";c?(a.info("Did not receive a new lounge token in onLoungeToken_ with data: "+(JSON.stringify(b)+", error: "+c)),a.X=c,n8(a,3E4)):(JTa(a,b.loungeToken),a.va=!1,a.X="unknown",n8(a,b.loungeTokenRefreshIntervalMs))},OTa=function(a,b,c,d){g.Zs(a.I);
a.I=0;GTa(a.B,b,function(e){e||0>d?c(e):a.I=g.Xs(function(){OTa(a,b,c,d-1)},300)})},QTa=function(a){g.Zs(a.S);
a.S=0;g.Zs(a.I);a.I=0;g.Zs(a.ma);a.ma=0;g.Zs(a.D);a.D=0;g.Zs(a.K);a.K=0},p8=function(a,b,c,d){j8.call(this,a,b,"DialSession");
this.config_=d;this.u=this.S=null;this.Aa="";this.Ka=c;this.La=null;this.ma=g.Ia;this.X=NaN;this.Ja=(0,g.D)(this.AQ,this);this.D=g.Ia;this.K=this.I=0;this.Z=!1;this.va="unknown"},q8=function(a){var b;
return!!(a.config_.enableDialLoungeToken&&(null==(b=a.u)?0:b.getDialAppInfo))},RTa=function(a){a.D=a.B.gI(a.Aa,a.i.label,a.i.friendlyName,q8(a),function(b,c){a.D=g.Ia;
a.Z=!0;k8(a,b);"shortLived"==b.idType&&0<c&&r8(a,c)},function(b){a.D=g.Ia;
a.xg(b)})},STa=function(a){var b={};
b.pairingCode=a.Aa;b.theme=a.Ka;BSa()&&(b.env_useStageMdx=1);return g.li(b)},s8=function(a){return new Promise(function(b){a.Aa=Y6();
if(a.La){var c=new chrome.cast.DialLaunchResponse(!0,STa(a));b(c);RTa(a)}else a.ma=function(){g.Zs(a.X);a.ma=function(){};
a.X=NaN;var d=new chrome.cast.DialLaunchResponse(!0,STa(a));b(d);RTa(a)},a.X=g.Xs(function(){a.ma()},100)})},UTa=function(a,b,c){a.info("initOnConnectedScreenDataPromise_: Received screenData: "+JSON.stringify(b));
var d=new U6(b);return(new Promise(function(e){TTa(a,d,function(f){f?(a.Z=!0,h8(a.B,d),k8(a,d),r8(a,c)):g.Cs(Error("DialSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online."));e(f)},5)})).then(function(e){return e?new chrome.cast.DialLaunchResponse(!1):s8(a)})},VTa=function(a,b){var c=a.S.receiver.label,d=a.i.friendlyName;
return(new Promise(function(e){ETa(a.B,c,b,d,function(f){f&&f.token&&k8(a,f);e(f)},function(f){l8(a,"Failed to get DIAL screen: "+f);
e(null)})})).then(function(e){return e&&e.token?new chrome.cast.DialLaunchResponse(!1):s8(a)})},TTa=function(a,b,c,d){g.Zs(a.I);
a.I=0;GTa(a.B,b,function(e){e||0>d?c(e):a.I=g.Xs(function(){TTa(a,b,c,d-1)},300)})},r8=function(a,b){a.info("getDialAppInfoWithTimeout_ "+b);
q8(a)&&(g.Zs(a.K),a.K=0,0==b?WTa(a):a.K=g.Xs(function(){WTa(a)},b))},WTa=function(a){q8(a)&&a.u.getDialAppInfo(function(b){a.info("getDialAppInfo dialLaunchData: "+JSON.stringify(b));
b=b.extraData||{};var c=null;if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";c?(a.va=c,r8(a,3E4)):(a.Z=!1,a.va="unknown",JTa(a,b.loungeToken),r8(a,b.loungeTokenRefreshIntervalMs))},function(b){a.info("getDialAppInfo error: "+b);
a.va="noLoungeTokenResponse";r8(a,3E4)})},XTa=function(a){g.Zs(a.I);
a.I=0;g.Zs(a.K);a.K=0;a.D();a.D=function(){};
g.Zs(a.X)},t8=function(a,b){j8.call(this,a,b,"ManualSession");
this.u=g.Xs((0,g.D)(this.Ks,this,null),150)},u8=function(a,b){g.R.call(this);
this.config_=b;this.u=a;this.S=b.appId||"233637DE";this.C=b.theme||"cl";this.X=b.disableCastApi||!1;this.I=b.forceMirroring||!1;this.i=null;this.K=!1;this.B=[];this.D=(0,g.D)(this.sV,this)},YTa=function(a,b){return b?g.sb(a.B,function(c){return V6(b,c.label)},a):null},v8=function(a){T7("Controller",a)},pTa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},w8=function(a){return a.K||!!a.B.length||!!a.i},x8=function(a,b,c){b!=a.i&&(g.ve(a.i),(a.i=b)?(c?a.ea("yt-remote-cast2-receiver-resumed",
b.i):a.ea("yt-remote-cast2-receiver-selected",b.i),b.subscribe("sessionScreen",(0,g.D)(a.RM,a,b)),b.subscribe("sessionFailed",function(){return ZTa(a,b)}),b.getScreen()?a.ea("yt-remote-cast2-session-change",b.getScreen()):c&&a.i.Ks(null)):a.ea("yt-remote-cast2-session-change",null))},ZTa=function(a,b){a.i==b&&a.ea("yt-remote-cast2-session-failed")},$Ta=function(a){var b=a.u.fI(),c=a.i&&a.i.i;
a=g.jm(b,function(d){c&&V6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=YTa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},eUa=function(a,b,c,d){d.disableCastApi?y8("Cannot initialize because disabled by Mdx config."):aUa()?bUa(b,d)&&(z8(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?cUa(a,c):(window.__onGCastApiAvailable=function(e,f){e?cUa(a,c):(A8("Failed to load cast API: "+f),B8(!1),z8(!1),g.Iz("yt-remote-cast-available"),g.Iz("yt-remote-cast-receiver"),
dUa(),c(!1))},d.loadCastApiSetupScript?g.Kz("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?60<=g7()&&ISa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?i7():89<=g7()?KSa():(j7(),h7(JSa.map(FSa))))):y8("Cannot initialize because not running Chrome")},dUa=function(){y8("dispose");
var a=C8();a&&a.dispose();g.Ga("yt.mdx.remote.cloudview.instance_",null,void 0);fUa(!1);g.cv(D8);D8.length=0},E8=function(){return!!g.Hz("yt-remote-cast-installed")},gUa=function(){var a=g.Hz("yt-remote-cast-receiver");
return a?a.friendlyName:null},hUa=function(){y8("clearCurrentReceiver");
g.Iz("yt-remote-cast-receiver")},iUa=function(){return E8()?C8()?C8().getCastSession():(A8("getCastSelector: Cast is not initialized."),null):(A8("getCastSelector: Cast API is not installed!"),null)},G8=function(){E8()?C8()?F8()?(y8("Requesting cast selector."),C8().requestSession()):(y8("Wait for cast API to be ready to request the session."),D8.push(g.bv("yt-remote-cast2-api-ready",G8))):A8("requestCastSelector: Cast is not initialized."):A8("requestCastSelector: Cast API is not installed!")},H8=
function(a,b){F8()?C8().setConnectedScreenStatus(a,b):A8("setConnectedScreenStatus called before ready.")},aUa=function(){var a=0<=g.Xb.search(/ (CrMo|Chrome|CriOS)\//);
return g.Qi||a},jUa=function(a,b){C8().init(a,b)},bUa=function(a,b){var c=!1;
C8()||(a=new u8(a,b),a.subscribe("yt-remote-cast2-availability-change",function(d){g.Gz("yt-remote-cast-available",d);S6("yt-remote-cast2-availability-change",d)}),a.subscribe("yt-remote-cast2-receiver-selected",function(d){y8("onReceiverSelected: "+d.friendlyName);
g.Gz("yt-remote-cast-receiver",d);S6("yt-remote-cast2-receiver-selected",d)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(d){y8("onReceiverResumed: "+d.friendlyName);
g.Gz("yt-remote-cast-receiver",d);S6("yt-remote-cast2-receiver-resumed",d)}),a.subscribe("yt-remote-cast2-session-change",function(d){y8("onSessionChange: "+W6(d));
d||g.Iz("yt-remote-cast-receiver");S6("yt-remote-cast2-session-change",d)}),g.Ga("yt.mdx.remote.cloudview.instance_",a,void 0),c=!0);
y8("cloudview.createSingleton_: "+c);return c},C8=function(){return g.Ha("yt.mdx.remote.cloudview.instance_")},cUa=function(a,b){B8(!0);
z8(!1);jUa(a,function(c){c?(fUa(!0),g.dv("yt-remote-cast2-api-ready")):(A8("Failed to initialize cast API."),B8(!1),g.Iz("yt-remote-cast-available"),g.Iz("yt-remote-cast-receiver"),dUa());b(c)})},y8=function(a){T7("cloudview",a)},A8=function(a){T7("cloudview",a)},B8=function(a){y8("setCastInstalled_ "+a);
g.Gz("yt-remote-cast-installed",a)},F8=function(){return!!g.Ha("yt.mdx.remote.cloudview.apiReady_")},fUa=function(a){y8("setApiReady_ "+a);
g.Ga("yt.mdx.remote.cloudview.apiReady_",a,void 0)},z8=function(a){g.Ga("yt.mdx.remote.cloudview.initializing_",a,void 0)},I8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.I=this.K=0;this.trackData=null;this.hasNext=this.Ek=!1;this.S=this.D=this.i=this.C=0;this.B=NaN;this.u=!1;this.reset(a)},J8=function(a){a.audioTrackId=null;
a.trackData=null;a.playerState=-1;a.Ek=!1;a.hasNext=!1;a.K=0;a.I=g.Qa();a.C=0;a.i=0;a.D=0;a.S=0;a.B=NaN;a.u=!1},K8=function(a){return a.Dc()?(g.Qa()-a.I)/1E3:0},L8=function(a,b){a.K=b;
a.I=g.Qa()},M8=function(a){switch(a.playerState){case 1:case 1081:return(g.Qa()-a.I)/1E3+a.K;
case -1E3:return 0}return a.K},N8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&J8(a)},O8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.uc(a.trackData);b.hasPrevious=a.Ek;b.hasNext=a.hasNext;b.playerTime=a.K;b.playerTimeAt=a.I;b.seekableStart=a.C;b.seekableEnd=a.i;b.duration=a.D;b.loadedTime=a.S;b.liveIngestionTime=a.B;return b},Q8=function(a,b){g.R.call(this);
this.B=0;this.C=a;this.I=[];this.D=new lTa;this.u=this.i=null;this.X=(0,g.D)(this.bU,this);this.K=(0,g.D)(this.Aw,this);this.S=(0,g.D)(this.aU,this);this.ma=(0,g.D)(this.iU,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.lG,this),kUa(this))):c=3;0!=c&&(b?this.lG(c):g.Xs((0,g.D)(function(){this.lG(c)},this),0));
(a=iUa())&&P8(this,a);this.subscribe("yt-remote-cast2-session-change",this.ma)},R8=function(a){return new I8(a.C.getPlayerContextData())},kUa=function(a){g.Rb("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange multiStateLoopEnabled loopModeChange".split(" "),function(b){this.I.push(this.C.subscribe(b,g.Pa(this.qV,b),this))},a)},lUa=function(a){g.Rb(a.I,function(b){this.C.unsubscribeByKey(b)},a);
a.I.length=0},S8=function(a){return 1==a.getState()},T8=function(a,b){var c=a.D;
50>c.i.length+c.u.length&&a.D.u.push(b)},V8=function(a,b,c){var d=R8(a);
L8(d,c);-1E3!=d.playerState&&(d.playerState=b);U8(a,d)},W8=function(a,b,c){a.C.sendMessage(b,c)},U8=function(a,b){lUa(a);
a.C.setPlayerContextData(O8(b));kUa(a)},P8=function(a,b){a.u&&(a.u.removeUpdateListener(a.X),a.u.removeMediaListener(a.K),a.Aw(null));
a.u=b;a.u&&(T7("CP","Setting cast session: "+a.u.sessionId),a.u.addUpdateListener(a.X),a.u.addMediaListener(a.K),a.u.media.length&&a.Aw(a.u.media[0]))},mUa=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=R8(a);b.contentId!=d.videoId&&T7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;L8(d,a.i.getEstimatedTime());U8(a,d)}else T7("CP","No cast media video. Ignoring state update.")},X8=function(a,b,c){return(0,g.D)(function(d){this.ke("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.ke("Retrying "+b+" using MDx browser channel."),W8(this,b,c))},a)},Y8=function(a,b,c,d){d=void 0===d?!1:d;
g.R.call(this);this.D=NaN;this.va=!1;this.S=this.K=this.ma=this.Z=NaN;this.X=[];this.C=this.I=this.B=this.fc=this.i=null;this.Ja=a;this.Ba=d;this.X.push(g.vu(window,"beforeunload",(0,g.D)(this.dS,this)));this.u=[];this.fc=new I8;this.La=b.id;this.Aa=b.idType;this.i=nUa(this,c);this.i.subscribe("handlerOpened",this.fU,this);this.i.subscribe("handlerClosed",this.cU,this);this.i.subscribe("handlerError",this.dU,this);this.i.subscribe("handlerMessage",this.eU,this);this.i.UA(b.token);this.subscribe("remoteQueueChange",
function(){var e=this.fc.videoId;g.Jz()&&g.Gz("yt-remote-session-video-id",e)},this)},oUa=function(a){return g.sb(a.u,function(b){return"LOUNGE_SCREEN"==b.type})},Z8=function(a){T7("conn",a)},nUa=function(a,b){return new M7(Q7(a.Ja,"/bc"),b,!1,function(){return a.kI()},"shortLived"==a.Aa)},$8=function(a,b){a.ea("proxyStateChange",b)},pUa=function(a){a.D=g.Xs((0,g.D)(function(){Z8("Connecting timeout");
this.Sr(1)},a),2E4)},a9=function(a){g.Zs(a.D);
a.D=NaN},b9=function(a){g.Zs(a.Z);
a.Z=NaN},qUa=function(a){c9(a);
a.ma=g.Xs((0,g.D)(function(){d9(this,"getNowPlaying")},a),2E4)},c9=function(a){g.Zs(a.ma);
a.ma=NaN},sUa=function(a,b){var c=null;
if(b){var d=oUa(a);d&&(c={clientName:d.clientName,deviceMake:d.brand,deviceModel:d.model,osVersion:d.osVersion})}g.Ga("yt.mdx.remote.remoteClient_",c,void 0);b&&(a9(a),b9(a));c=O7(a.i)&&isNaN(a.D);b==c?b&&($8(a,1),d9(a,"getSubtitlesTrack")):b?(a.wK()&&a.fc.reset(),$8(a,1),d9(a,"getNowPlaying"),rUa(a)):a.Sr(1)},tUa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.fc.videoId&&(g.oc(b.params)?a.fc.trackData=null:a.fc.trackData=b.params,a.ea("remotePlayerChange"))},uUa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.fc.listId=b.params.listId||a.fc.listId;N8(a.fc,c,d);a.ea("remoteQueueChange")},wUa=function(a,b){b.params=b.params||{};
uUa(a,b);vUa(a,b);a.ea("autoplayDismissed")},vUa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
L8(a.fc,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.fc.playerState&&(c=-1E3);a.fc.playerState=c;c=Number(b.params.loadedTime);a.fc.S=isNaN(c)?0:c;a.fc.Hj(Number(b.params.duration));c=a.fc;var d=Number(b.params.liveIngestionTime);c.B=d;c.u=isNaN(d)?!1:!0;c=a.fc;d=Number(b.params.seekableStartTime);b=Number(b.params.seekableEndTime);c.C=isNaN(d)?0:d;c.i=isNaN(b)?0:b;1==a.fc.playerState?qUa(a):c9(a);a.ea("remotePlayerChange")},xUa=function(a,b){if(-1E3!=a.fc.playerState){var c=
1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.fc.playerState=c;b=parseInt(b.params.currentTime,10);L8(a.fc,isNaN(b)?0:b);a.ea("remotePlayerChange")}},yUa=function(a,b){var c="true"==b.params.muted;
a.fc.volume=parseInt(b.params.volume,10);a.fc.muted=c;a.ea("remotePlayerChange")},zUa=function(a,b){a.I=b.params.videoId;
a.ea("nowAutoplaying",parseInt(b.params.timeout,10))},AUa=function(a,b){var c="true"==b.params.hasNext;
a.fc.Ek="true"==b.params.hasPrevious;a.fc.hasNext=c;a.ea("previousNextChange")},rUa=function(a){g.Zs(a.S);
a.S=g.Xs((0,g.D)(a.Sr,a,1),864E5)},d9=function(a,b,c){c?Z8("Sending: action="+b+", params="+g.Rh(c)):Z8("Sending: action="+b);
a.i.sendMessage(b,c)},e9=function(a){X7.call(this,"ScreenServiceProxy");
this.Se=a;this.i=[];this.i.push(this.Se.$_s("screenChange",(0,g.D)(this.EQ,this)));this.i.push(this.Se.$_s("onlineScreenChange",(0,g.D)(this.XU,this)))},EUa=function(a,b){ASa();
if(!f7||!f7.get("yt-remote-disable-remote-module-for-dev")){b=g.O("MDX_CONFIG")||b;sSa();d7();f9||(f9=new P7(b?b.loungeApiHost:void 0),BSa()&&(f9.i="/api/loungedev"));g9||(g9=g.Ha("yt.mdx.remote.deferredProxies_")||[],g.Ga("yt.mdx.remote.deferredProxies_",g9,void 0));BUa();var c=h9();if(!c){var d=new g8(f9,b?b.disableAutomaticScreenCache||!1:!1);g.Ga("yt.mdx.remote.screenService_",d,void 0);c=h9();var e={};b&&(e={appId:b.appId,disableDial:b.disableDial,theme:b.theme,loadCastApiSetupScript:b.loadCastApiSetupScript,
disableCastApi:b.disableCastApi,enableDialLoungeToken:b.enableDialLoungeToken,enableCastLoungeToken:b.enableCastLoungeToken,forceMirroring:b.forceMirroring});g.Ga("yt.mdx.remote.enableConnectWithInitialState_",b?b.enableConnectWithInitialState||!1:!1,void 0);eUa(a,d,function(f){f?i9()&&H8(i9(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){S6("yt-remote-receiver-availability-change")})},e)}b&&!g.Ha("yt.mdx.remote.initialized_")&&(g.Ga("yt.mdx.remote.initialized_",!0,void 0),j9("Initializing: "+
g.Rh(b)),k9.push(g.bv("yt-remote-cast2-api-ready",function(){S6("yt-remote-api-ready")})),k9.push(g.bv("yt-remote-cast2-availability-change",function(){S6("yt-remote-receiver-availability-change")})),k9.push(g.bv("yt-remote-cast2-receiver-selected",function(){l9(null);
S6("yt-remote-auto-connect","cast-selector-receiver")})),k9.push(g.bv("yt-remote-cast2-receiver-resumed",function(){S6("yt-remote-receiver-resumed","cast-selector-receiver")})),k9.push(g.bv("yt-remote-cast2-session-change",CUa)),k9.push(g.bv("yt-remote-connection-change",function(f){f?H8(i9(),"YouTube TV"):m9()||(H8(null,null),hUa())})),k9.push(g.bv("yt-remote-cast2-session-failed",function(){S6("yt-remote-connection-failed")})),a=n9(),b.isAuto&&(a.id+="#dial"),e=b.capabilities||[],g.P("desktop_enable_autoplay")&&
e.push("atp"),0<e.length&&(a.capabilities=e),a.name=b.device,a.app=b.app,(b=b.theme)&&(a.theme=b),j9(" -- with channel params: "+g.Rh(a)),a?(g.Gz("yt-remote-session-app",a.app),g.Gz("yt-remote-session-name",a.name)):(g.Iz("yt-remote-session-app"),g.Iz("yt-remote-session-name")),g.Ga("yt.mdx.remote.channelParams_",a,void 0),c.start(),i9()||DUa())}},FUa=function(){var a=h9().Se.$_gos();
var b=o9();b&&p9()&&(Z6(a,b)||a.push(b));return rSa(a)},q9=function(){var a=GUa();
!a&&E8()&&gUa()&&(a={key:"cast-selector-receiver",name:gUa()});return a},GUa=function(){var a=FUa(),b=o9();
b||(b=m9());return g.sb(a,function(c){return b&&V6(b,c.key)?!0:!1})},o9=function(){var a=i9();
if(!a)return null;var b=h9().Fh();return $6(b,a)},CUa=function(a){j9("remote.onCastSessionChange_: "+W6(a));
if(a){var b=o9();if(b&&b.id==a.id){if(H8(b.id,"YouTube TV"),"shortLived"==a.idType&&(a=a.token))r9&&(r9.token=a),(b=p9())&&b.UA(a)}else b&&s9(),t9(a,1)}else p9()&&s9()},s9=function(){F8()?C8().stopSession():A8("stopSession called before API ready.");
var a=p9();a&&(a.disconnect(1),u9(null))},v9=function(){var a=p9();
return!!a&&3!=a.getProxyState()},j9=function(a){T7("remote",a)},h9=function(){if(!w9){var a=g.Ha("yt.mdx.remote.screenService_");
w9=a?new e9(a):null}return w9},i9=function(){return g.Ha("yt.mdx.remote.currentScreenId_")},HUa=function(a){g.Ga("yt.mdx.remote.currentScreenId_",a,void 0)},IUa=function(){return g.Ha("yt.mdx.remote.connectData_")},l9=function(a){g.Ga("yt.mdx.remote.connectData_",a,void 0)},p9=function(){return g.Ha("yt.mdx.remote.connection_")},u9=function(a){var b=p9();
l9(null);a||HUa("");g.Ga("yt.mdx.remote.connection_",a,void 0);g9&&(g.Rb(g9,function(c){c(a)}),g9.length=0);
b&&!a?S6("yt-remote-connection-change",!1):!b&&a&&S6("yt-remote-connection-change",!0)},m9=function(){var a=g.Jz();
if(!a)return null;var b=h9();if(!b)return null;b=b.Fh();return $6(b,a)},t9=function(a,b){i9();
o9()&&o9();if(x9)r9=a;else{HUa(a.id);var c=g.Ha("yt.mdx.remote.enableConnectWithInitialState_")||!1;a=new Y8(f9,a,n9(),c);a.connect(b,IUa());a.subscribe("beforeDisconnect",function(d){S6("yt-remote-before-disconnect",d)});
a.subscribe("beforeDispose",function(){p9()&&(p9(),u9(null))});
a.subscribe("browserChannelAuthError",function(){var d=o9();d&&"shortLived"==d.idType&&(F8()?C8().handleBrowserChannelAuthError():A8("refreshLoungeToken called before API ready."))});
u9(a)}},DUa=function(){var a=m9();
a?(j9("Resume connection to: "+W6(a)),t9(a,0)):(e7(),hUa(),j9("Skipping connecting because no session screen found."))},BUa=function(){var a=n9();
if(g.oc(a)){a=c7();var b=g.Hz("yt-remote-session-name")||"",c=g.Hz("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ga("yt.mdx.remote.channelParams_",a,void 0)}},n9=function(){return g.Ha("yt.mdx.remote.channelParams_")||{}},y9=function(a,b,c){g.H.call(this);
var d=this;this.u=a;this.J=b;this.Sb=c;this.events=new g.qD(this);this.ma=this.events.T(this.J,"onVolumeChange",function(e){JUa(d,e)});
this.D=!1;this.I=new g.QJ(64);this.i=new g.J(this.XN,500,this);this.B=new g.J(this.YN,1E3,this);this.S=new k7(this.PX,0,this);this.C={};this.X=new g.J(this.GO,1E3,this);this.K=new l7(this.seekTo,1E3,this);this.Z=g.Ia;g.I(this,this.events);this.events.T(b,"onCaptionsTrackListChanged",this.IU);this.events.T(b,"captionschanged",this.XT);this.events.T(b,"captionssettingschanged",this.eO);this.events.T(b,"videoplayerreset",this.nA);this.events.T(b,"mdxautoplaycancel",function(){d.Sb.TJ()});
a=this.Sb;a.isDisposed();a.subscribe("proxyStateChange",this.MM,this);a.subscribe("remotePlayerChange",this.Ew,this);a.subscribe("remoteQueueChange",this.nA,this);a.subscribe("previousNextChange",this.JM,this);a.subscribe("nowAutoplaying",this.DM,this);a.subscribe("autoplayDismissed",this.gM,this);g.I(this,this.i);g.I(this,this.B);g.I(this,this.S);g.I(this,this.X);g.I(this,this.K);this.eO();this.nA();this.Ew()},JUa=function(a,b){if(z9(a)){a.Sb.unsubscribe("remotePlayerChange",a.Ew,a);
var c=Math.round(b.volume);b=!!b.muted;var d=R8(a.Sb);if(c!==d.volume||b!==d.muted)a.Sb.setVolume(c,b),a.X.start();a.Sb.subscribe("remotePlayerChange",a.Ew,a)}},KUa=function(a){a.Wb(0);
a.i.stop();a.Tb(new g.QJ(64))},A9=function(a,b){if(z9(a)&&!a.D){var c=null;
b&&(c={style:a.J.getSubtitlesUserSettings()},g.wc(c,b));a.Sb.jI(a.J.getVideoData(1).videoId,c);a.C=R8(a.Sb).trackData}},B9=function(a,b){var c=a.J.getPlaylist();
if(null===c||void 0===c?0:c.listId){var d=c.index;var e=c.listId.toString()}c=a.J.getVideoData(1);a.Sb.playVideo(c.videoId,b,d,e,c.playerParams,c.fb,hSa(c));a.Tb(new g.QJ(1))},LUa=function(a,b){if(b){var c=a.J.getOption("captions","tracklist",{UK:1});
c&&c.length?(a.J.setOption("captions","track",b),a.D=!1):(a.J.loadModule("captions"),a.D=!0)}else a.J.setOption("captions","track",{})},z9=function(a){return R8(a.Sb).videoId===a.J.getVideoData(1).videoId},C9=function(){g.V.call(this,{G:"div",
L:"ytp-mdx-popup-dialog",W:{role:"dialog"},U:[{G:"div",L:"ytp-mdx-popup-dialog-inner-content",U:[{G:"div",L:"ytp-mdx-popup-title",xa:"You're signed out"},{G:"div",L:"ytp-mdx-popup-description",xa:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{G:"div",L:"ytp-mdx-privacy-popup-buttons",U:[{G:"button",Ga:["ytp-button","ytp-mdx-privacy-popup-cancel"],xa:"Cancel"},{G:"button",Ga:["ytp-button",
"ytp-mdx-privacy-popup-confirm"],xa:"Confirm"}]}]}]});this.i=new g.vL(this,250);this.cancelButton=this.Fa("ytp-mdx-privacy-popup-cancel");this.confirmButton=this.Fa("ytp-mdx-privacy-popup-confirm");g.I(this,this.i);this.T(this.cancelButton,"click",this.u);this.T(this.confirmButton,"click",this.B)},D9=function(a){g.V.call(this,{G:"div",
L:"ytp-remote",U:[{G:"div",L:"ytp-remote-display-status",U:[{G:"div",L:"ytp-remote-display-status-icon",U:[g.Usa()]},{G:"div",L:"ytp-remote-display-status-text",xa:"{{statustext}}"}]}]});this.api=a;this.i=new g.vL(this,250);g.I(this,this.i);this.T(a,"presentingplayerstatechange",this.onStateChange);MUa(this,a.xb())},MUa=function(a,b){if(3===a.api.getPresentingPlayerType()){var c={RECEIVER_NAME:a.api.getOption("remote","currentReceiver").name};
b=g.U(b,128)?g.qI("Error on $RECEIVER_NAME",c):b.Dc()||g.U(b,4)?g.qI("Playing on $RECEIVER_NAME",c):g.qI("Connected to $RECEIVER_NAME",c);a.Sa("statustext",b);a.i.show()}else a.i.hide()},E9=function(a,b){g.OP.call(this,"Play on",0,a,b);
this.J=a;this.qo={};this.T(a,"onMdxReceiversChange",this.D);this.T(a,"presentingplayerstatechange",this.D);this.D()},F9=function(a){g.ZM.call(this,a);
this.Lk={key:Y6(),name:"This computer"};this.ai=null;this.subscriptions=[];this.IF=this.Sb=null;this.qo=[this.Lk];this.Wm=this.Lk;this.ud=new g.QJ(64);this.xL=0;this.uf=-1;this.Nw=!1;this.Lw=this.Ys=null;if(!g.aF(this.player.V())&&!g.bF(this.player.V())){a=this.player;var b=g.CM(a);b&&(b=b.An())&&(b=new E9(a,b),g.I(this,b));b=new D9(a);g.I(this,b);g.MM(a,b.element,4);this.Ys=new C9;g.I(this,this.Ys);g.MM(a,this.Ys.element,4);this.Nw=!!m9()}},G9=function(a){a.Lw&&(a.player.removeEventListener("presentingplayerstatechange",
a.Lw),a.Lw=null)},NUa=function(a,b,c){a.ud=c;
a.player.ea("presentingplayerstatechange",new g.cI(c,b))},H9=function(a,b){if(b.key!==a.Wm.key)if(b.key===a.Lk.key)s9();
else{var c;(c=!a.player.V().N("mdx_enable_privacy_disclosure_ui"))||(c=((c=g.O("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.O("SESSION_INDEX")&&!g.O("LOGGED_IN")))||a.Nw||!a.Ys);(c?0:g.rF(a.player.V())||g.uF(a.player.V()))&&OUa(a);a.Wm=b;if(!a.player.V().N("disable_mdx_connection_in_mdx_module_for_music_web")||!g.bF(a.player.V())){var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(!d&&!e||(2===a.player.getAppState()||1===a.player.getAppState())&&a.player.V().N("should_clear_video_data_on_player_cued_unstarted"))a=
null;else{var f=a.player.getPlaylist();if(f){var h=[];for(var l=0;l<f.length;l++)h[l]=g.TM(f,l).videoId}else h=[e];f=a.player.getCurrentTime(1);a={videoIds:h,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.fb,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0===f?void 0:f};(c=hSa(c))&&(a.locationInfo=c)}j9("Connecting to: "+g.Rh(b));"cast-selector-receiver"==b.key?(l9(a||null),b=a||null,F8()?C8().setLaunchParams(b):A8("setLaunchParams called before ready.")):!a&&v9()&&
i9()==b.key?S6("yt-remote-connection-change",!0):(s9(),l9(a||null),a=h9().Fh(),(b=$6(a,b.key))&&t9(b,1))}}},OUa=function(a){a.player.xb().Dc()?a.player.pauseVideo():(a.Lw=function(b){!a.Nw&&g.eI(b,8)&&(a.player.pauseVideo(),G9(a))},a.player.addEventListener("presentingplayerstatechange",a.Lw));
a.Ys&&a.Ys.td();p9()||(x9=!0)},QSa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},x7={"'":"\\'"},nSa={WY:"atp",R9:"ska",D8:"que",y6:"mus",Q9:"sus",M2:"dsp",a9:"seq",b6:"mic",E1:"dpa",lZ:"cds",w6:"mlm",C1:"dsdtr"},f7,b7="",HSa=CSa("loadCastFramework")||CSa("loadCastApplicationFramework"),JSa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Ra(k7,g.H);g.k=k7.prototype;g.k.sQ=function(a){this.C=arguments;this.i=!1;this.Kb?this.B=g.Qa()+this.Tf:this.Kb=g.th(this.D,this.Tf)};
g.k.stop=function(){this.Kb&&(g.B.clearTimeout(this.Kb),this.Kb=null);this.B=null;this.i=!1;this.C=[]};
g.k.pause=function(){++this.u};
g.k.resume=function(){this.u&&(--this.u,!this.u&&this.i&&(this.i=!1,this.I.apply(null,this.C)))};
g.k.ya=function(){this.stop();k7.je.ya.call(this)};
g.k.tQ=function(){this.Kb&&(g.B.clearTimeout(this.Kb),this.Kb=null);this.B?(this.Kb=g.th(this.D,this.B-g.Qa()),this.B=null):this.u?this.i=!0:(this.i=!1,this.I.apply(null,this.C))};g.v(l7,g.H);g.k=l7.prototype;g.k.eI=function(a){this.B=arguments;this.Kb||this.u?this.i=!0:m7(this)};
g.k.stop=function(){this.Kb&&(g.B.clearTimeout(this.Kb),this.Kb=null,this.i=!1,this.B=null)};
g.k.pause=function(){this.u++};
g.k.resume=function(){this.u--;this.u||!this.i||this.Kb||(this.i=!1,m7(this))};
g.k.ya=function(){g.H.prototype.ya.call(this);this.stop()};n7.prototype.stringify=function(a){return g.B.JSON.stringify(a,void 0)};
n7.prototype.parse=function(a){return g.B.JSON.parse(a,void 0)};var p7=new g.We;g.v(LSa,g.ye);g.k=r7.prototype;g.k.To=null;g.k.Cm=!1;g.k.Qt=null;g.k.eH=null;g.k.nt=null;g.k.Ft=null;g.k.Qm=null;g.k.zo=null;g.k.rq=null;g.k.Mf=null;g.k.vB=0;g.k.Mj=null;g.k.sB=null;g.k.Km=null;g.k.xu=-1;g.k.LN=!0;g.k.mp=!1;g.k.jC=0;g.k.IA=null;var OSa={},u7={};g.k=r7.prototype;g.k.setTimeout=function(a){this.u=a};
g.k.uQ=function(a){a=a.target;var b=this.IA;b&&3==g.Ai(a)?b.eI():this.PO(a)};
g.k.PO=function(a){try{if(a==this.Mf)a:{var b=g.Ai(this.Mf),c=this.Mf.u,d=this.Mf.getStatus();if(g.Tc&&!g.Nc(10)||g.Bg&&!g.Mc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Fi(this.Mf))break a;this.mp||4!=b||7==c||(8==c||0>=d?this.i.wj(3):this.i.wj(2));y7(this);var e=this.Mf.getStatus();this.xu=e;var f=g.Fi(this.Mf);if(this.Cm=200==e){4==b&&v7(this);if(this.D){for(a=!0;!this.mp&&this.vB<f.length;){var h=PSa(this,f);if(h==u7){4==b&&(this.Km=4,q7(15),a=!1);break}else if(h==OSa){this.Km=4;q7(16);a=!1;
break}else z7(this,h)}4==b&&0==f.length&&(this.Km=1,q7(17),a=!1);this.Cm=this.Cm&&a;a||(v7(this),w7(this))}else z7(this,f);this.Cm&&!this.mp&&(4==b?this.i.Vx(this):(this.Cm=!1,t7(this)))}else 400==e&&0<f.indexOf("Unknown SID")?(this.Km=3,q7(13)):(this.Km=0,q7(14)),v7(this),w7(this)}}catch(l){this.Mf&&g.Fi(this.Mf)}finally{}};
g.k.oW=function(a){o7((0,g.D)(this.nW,this,a),0)};
g.k.nW=function(a){this.mp||(y7(this),z7(this,a),t7(this))};
g.k.VM=function(a){o7((0,g.D)(this.mW,this,a),0)};
g.k.mW=function(a){this.mp||(v7(this),this.Cm=a,this.i.Vx(this),this.i.wj(4))};
g.k.cancel=function(){this.mp=!0;v7(this)};
g.k.vW=function(){this.Qt=null;var a=Date.now();0<=a-this.eH?(2!=this.Ft&&this.i.wj(3),v7(this),this.Km=2,q7(18),w7(this)):SSa(this,this.eH-a)};
g.k.getLastError=function(){return this.Km};g.k=VSa.prototype;g.k.kC=null;g.k.lh=null;g.k.JA=!1;g.k.ZN=null;g.k.Oy=null;g.k.FE=null;g.k.lC=null;g.k.Xh=null;g.k.jl=-1;g.k.yu=null;g.k.Nu=null;g.k.connect=function(a){this.lC=a;a=B7(this.i,null,this.lC);q7(3);this.ZN=Date.now();var b=this.i.S;null!=b?(this.yu=b[0],(this.Nu=b[1])?(this.Xh=1,WSa(this)):(this.Xh=2,D7(this))):(P6(a,"MODE","init"),this.lh=new r7(this,void 0,void 0,void 0),this.lh.To=this.kC,s7(this.lh,a,!1,null,!0),this.Xh=0)};
g.k.lR=function(a){if(a)this.Xh=2,D7(this);else{q7(4);var b=this.i;b.Yj=b.Um.jl;K7(b,9)}a&&this.wj(2)};
g.k.nD=function(a){return this.i.nD(a)};
g.k.abort=function(){this.lh&&(this.lh.cancel(),this.lh=null);this.jl=-1};
g.k.qf=function(){return!1};
g.k.OM=function(a,b){this.jl=a.xu;if(0==this.Xh)if(b){try{var c=this.u.parse(b)}catch(d){a=this.i;a.Yj=this.jl;K7(a,2);return}this.yu=c[0];this.Nu=c[1]}else a=this.i,a.Yj=this.jl,K7(a,2);else if(2==this.Xh)if(this.JA)q7(7),this.FE=Date.now();else if("11111"==b){if(q7(6),this.JA=!0,this.Oy=Date.now(),a=this.Oy-this.ZN,!g.Tc||g.Nc(10)||500>a)this.jl=200,this.lh.cancel(),q7(12),C7(this.i,this,!0)}else q7(8),this.Oy=this.FE=Date.now(),this.JA=!1};
g.k.Vx=function(){this.jl=this.lh.xu;if(this.lh.Cm)0==this.Xh?this.Nu?(this.Xh=1,WSa(this)):(this.Xh=2,D7(this)):2==this.Xh&&((!g.Tc||g.Nc(10)?!this.JA:200>this.FE-this.Oy)?(q7(11),C7(this.i,this,!1)):(q7(12),C7(this.i,this,!0)));else{0==this.Xh?q7(9):2==this.Xh&&q7(10);var a=this.i;this.lh.getLastError();a.Yj=this.jl;K7(a,2)}};
g.k.mx=function(){return this.i.mx()};
g.k.isActive=function(){return this.i.isActive()};
g.k.wj=function(a){this.i.wj(a)};g.k=E7.prototype;g.k.Xj=null;g.k.vv=null;g.k.Ug=null;g.k.Je=null;g.k.mC=null;g.k.Py=null;g.k.hJ=null;g.k.Wx=null;g.k.pw=0;g.k.qT=0;g.k.Nf=null;g.k.jn=null;g.k.Al=null;g.k.yp=null;g.k.Um=null;g.k.qB=null;g.k.Js=-1;g.k.wL=-1;g.k.Yj=-1;g.k.Wr=0;g.k.Gr=0;g.k.np=8;g.Ra(YSa,g.ye);g.Ra(ZSa,g.ye);g.k=E7.prototype;g.k.connect=function(a,b,c,d,e){q7(0);this.mC=b;this.vv=c||{};d&&void 0!==e&&(this.vv.OSID=d,this.vv.OAID=e);this.I?(o7((0,g.D)(this.DJ,this,a),100),cTa(this)):this.DJ(a)};
g.k.DJ=function(a){this.Um=new VSa(this);this.Um.kC=this.Xj;this.Um.u=this.D;this.Um.connect(a)};
g.k.qf=function(){return 0==this.i};
g.k.getState=function(){return this.i};
g.k.TM=function(a){this.jn=null;gTa(this,a)};
g.k.SM=function(){this.Al=null;this.Je=new r7(this,this.B,"rpc",this.K);this.Je.To=this.Xj;this.Je.jC=0;var a=this.hJ.clone();g.Rj(a,"RID","rpc");g.Rj(a,"SID",this.B);g.Rj(a,"CI",this.qB?"0":"1");g.Rj(a,"AID",this.Js);F7(this,a);if(!g.Tc||g.Nc(10))g.Rj(a,"TYPE","xmlhttp"),s7(this.Je,a,!0,this.Wx,!1);else{g.Rj(a,"TYPE","html");var b=this.Je,c=!!this.Wx;b.Ft=3;b.Qm=O6(a.clone());RSa(b,c)}};
g.k.OM=function(a,b){if(0!=this.i&&(this.Je==a||this.Ug==a))if(this.Yj=a.xu,this.Ug==a&&3==this.i)if(7<this.np){try{var c=this.D.parse(b)}catch(d){c=null}if(Array.isArray(c)&&3==c.length)if(a=c,0==a[0])a:{if(!this.Al){if(this.Je)if(this.Je.nt+3E3<this.Ug.nt)H7(this),this.Je.cancel(),this.Je=null;else break a;J7(this);q7(19)}}else this.wL=a[1],0<this.wL-this.Js&&37500>a[2]&&this.qB&&0==this.Gr&&!this.yp&&(this.yp=o7((0,g.D)(this.TT,this),6E3));else K7(this,11)}else null!=b&&K7(this,11);else if(this.Je==
a&&H7(this),!g.cb(b))for(a=this.D.parse(b),b=0;b<a.length;b++)c=a[b],this.Js=c[0],c=c[1],2==this.i?"c"==c[0]?(this.B=c[1],this.Wx=c[2],c=c[3],null!=c?this.np=c:this.np=6,this.i=3,this.Nf&&this.Nf.zJ(),this.hJ=B7(this,this.mx()?this.Wx:null,this.mC),hTa(this)):"stop"==c[0]&&K7(this,7):3==this.i&&("stop"==c[0]?K7(this,7):"noop"!=c[0]&&this.Nf&&this.Nf.yJ(c),this.Gr=0)};
g.k.TT=function(){null!=this.yp&&(this.yp=null,this.Je.cancel(),this.Je=null,J7(this),q7(20))};
g.k.Vx=function(a){if(this.Je==a){H7(this);this.Je=null;var b=2}else if(this.Ug==a)this.Ug=null,b=1;else return;this.Yj=a.xu;if(0!=this.i)if(a.Cm)if(1==b){b=Date.now()-a.nt;var c=p7;c.dispatchEvent(new YSa(c,a.rq?a.rq.length:0,b,this.Wr));G7(this);this.C.length=0}else hTa(this);else{c=a.getLastError();var d;if(!(d=3==c||7==c||0==c&&0<this.Yj)){if(d=1==b)this.Ug||this.jn||1==this.i||2<=this.Wr?d=!1:(this.jn=o7((0,g.D)(this.TM,this,a),iTa(this,this.Wr)),this.Wr++,d=!0);d=!(d||2==b&&J7(this))}if(d)switch(c){case 1:K7(this,
5);break;case 4:K7(this,10);break;case 3:K7(this,6);break;case 7:K7(this,12);break;default:K7(this,2)}}};
g.k.LR=function(a){if(!g.vb(arguments,this.i))throw Error("Unexpected channel state: "+this.i);};
g.k.yX=function(a){a?q7(2):(q7(1),jTa(this,8))};
g.k.nD=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.ui;a.S=!1;return a};
g.k.isActive=function(){return!!this.Nf&&this.Nf.isActive(this)};
g.k.wj=function(a){var b=p7;b.dispatchEvent(new ZSa(b,a))};
g.k.mx=function(){return!(!g.Tc||g.Nc(10))};
g.k=kTa.prototype;g.k.zJ=function(){};
g.k.yJ=function(){};
g.k.xJ=function(){};
g.k.aD=function(){};
g.k.jK=function(){return{}};
g.k.isActive=function(){return!0};g.k=lTa.prototype;g.k.isEmpty=function(){return 0===this.i.length&&0===this.u.length};
g.k.clear=function(){this.i=[];this.u=[]};
g.k.contains=function(a){return g.vb(this.i,a)||g.vb(this.u,a)};
g.k.remove=function(a){var b=this.i;var c=(0,g.mMa)(b,a);0<=c?(g.yb(b,c),b=!0):b=!1;return b||g.Ab(this.u,a)};
g.k.Lp=function(){for(var a=[],b=this.i.length-1;0<=b;--b)a.push(this.i[b]);var c=this.u.length;for(b=0;b<c;++b)a.push(this.u[b]);return a};g.Ra(L7,g.H);g.k=L7.prototype;g.k.fW=function(){this.Tf=Math.min(3E5,2*this.Tf);this.B();this.u&&this.start()};
g.k.start=function(){var a=this.Tf+15E3*Math.random();g.Hq(this.i,a);this.u=Date.now()+a};
g.k.stop=function(){this.i.stop();this.u=0};
g.k.isActive=function(){return this.i.isActive()};
g.k.reset=function(){this.i.stop();this.Tf=5E3};g.Ra(M7,kTa);g.k=M7.prototype;g.k.subscribe=function(a,b,c){return this.B.subscribe(a,b,c)};
g.k.unsubscribe=function(a,b,c){return this.B.unsubscribe(a,b,c)};
g.k.cg=function(a){return this.B.cg(a)};
g.k.ea=function(a,b){return this.B.ea.apply(this.B,arguments)};
g.k.dispose=function(){this.ma||(this.ma=!0,g.ve(this.B),oTa(this),g.ve(this.u),this.u=null,this.Z=function(){return""})};
g.k.isDisposed=function(){return this.ma};
g.k.connect=function(a,b,c){if(!this.i||2!=this.i.getState()){this.X="";this.u.stop();this.D=a||null;this.C=b||0;a=this.va+"/test";b=this.va+"/bind";var d=new E7(c?c.firstTestResults:null,c?c.secondTestResults:null,this.Aa),e=this.i;e&&(e.Nf=null);d.Nf=this;this.i=d;N7(this);if(this.i){d=g.O("ID_TOKEN");var f=this.i.Xj||{};d?f["x-youtube-identity-token"]=d:delete f["x-youtube-identity-token"];this.i.Xj=f}e?(3!=e.getState()&&0==eTa(e)||e.getState(),this.i.connect(a,b,this.I,e.B,e.Js)):c?this.i.connect(a,
b,this.I,c.sessionId,c.arrayId):this.i.connect(a,b,this.I)}};
g.k.sendMessage=function(a,b){a={_sc:a};b&&g.wc(a,b);this.u.isActive()||2==(this.i?this.i.getState():0)?this.K.push(a):O7(this)&&(N7(this),dTa(this.i,a))};
g.k.zJ=function(){this.u.reset();this.D=null;this.C=0;if(this.K.length){var a=this.K;this.K=[];for(var b=0,c=a.length;b<c;++b)dTa(this.i,a[b])}this.ea("handlerOpened")};
g.k.xJ=function(a){var b=2==a&&401==this.i.Yj;4==a||b||this.u.start();this.ea("handlerError",a,b)};
g.k.aD=function(a){if(!this.u.isActive())this.ea("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.K.push(d)}};
g.k.jK=function(){var a={v:2};this.X&&(a.gsessionid=this.X);0!=this.C&&(a.ui=""+this.C);0!=this.S&&(a.ui=""+this.S);this.D&&g.wc(a,this.D);return a};
g.k.yJ=function(a){"S"==a[0]?this.X=a[1]:"gracefulReconnect"==a[0]?(this.u.start(),bTa(this.i)):this.ea("handlerMessage",new mTa(a[0],a[1]))};
g.k.UA=function(a){(this.I.loungeIdToken=a)||this.u.stop();if(this.Ba&&this.i){var b=this.i.Xj||{};a?b["X-YouTube-LoungeId-Token"]=a:delete b["X-YouTube-LoungeId-Token"];this.i.Xj=b}};
g.k.cX=function(){this.u.isActive();0==eTa(this.i)&&this.connect(this.D,this.C)};P7.prototype.C=function(a,b,c,d){b?a(d):a({text:c.responseText})};
P7.prototype.B=function(a,b){a(Error("Request error: "+b.status))};
P7.prototype.D=function(a){a(Error("request timed out"))};var vTa=Date.now(),S7=null,V7=Array(50),U7=-1,W7=!1;g.Ra(X7,g.R);X7.prototype.Fh=function(){return this.screens};
X7.prototype.contains=function(a){return!!Z6(this.screens,a)};
X7.prototype.get=function(a){return a?$6(this.screens,a):null};
X7.prototype.info=function(a){T7(this.I,a)};g.v(Y7,g.R);g.k=Y7.prototype;g.k.start=function(){!this.i&&isNaN(this.Kb)&&this.fN()};
g.k.stop=function(){this.i&&(this.i.abort(),this.i=null);isNaN(this.Kb)||(g.Zs(this.Kb),this.Kb=NaN)};
g.k.ya=function(){this.stop();g.R.prototype.ya.call(this)};
g.k.fN=function(){this.Kb=NaN;this.i=g.wt(Q7(this.B,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:this.K},timeout:5E3,onSuccess:(0,g.D)(this.wQ,this),onError:(0,g.D)(this.vQ,this),onTimeout:(0,g.D)(this.xQ,this)})};
g.k.wQ=function(a,b){this.i=null;a=b.screen||{};a.dialId=this.C;a.name=this.I;b=-1;this.D&&a.shortLivedLoungeToken&&a.shortLivedLoungeToken.value&&a.shortLivedLoungeToken.refreshIntervalMs&&(a.screenIdType="shortLived",a.loungeToken=a.shortLivedLoungeToken.value,b=a.shortLivedLoungeToken.refreshIntervalMs);this.ea("pairingComplete",new U6(a),b)};
g.k.vQ=function(a){this.i=null;a.status&&404==a.status?this.u>=PUa.length?this.ea("pairingFailed",Error("DIAL polling timed out")):(a=PUa[this.u],this.Kb=g.Xs((0,g.D)(this.fN,this),a),this.u++):this.ea("pairingFailed",Error("Server error "+a.status))};
g.k.xQ=function(){this.i=null;this.ea("pairingFailed",Error("Server not responding"))};
var PUa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Ra($7,X7);g.k=$7.prototype;g.k.start=function(){Z7(this)&&this.ea("screenChange");!g.Hz("yt-remote-lounge-token-expiration")&&zTa(this);g.Zs(this.i);this.i=g.Xs((0,g.D)(this.start,this),1E4)};
g.k.add=function(a,b){Z7(this);wTa(this,a);a8(this,!1);this.ea("screenChange");b(a);a.token||zTa(this)};
g.k.remove=function(a,b){var c=Z7(this);yTa(this,a)&&(a8(this,!1),c=!0);b(a);c&&this.ea("screenChange")};
g.k.oB=function(a,b,c,d){var e=Z7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,a8(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.ea("screenChange")};
g.k.ya=function(){g.Zs(this.i);$7.je.ya.call(this)};
g.k.iS=function(a){Z7(this);var b=this.screens.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}a8(this,!b);b&&T7(this.I,"Missed "+b+" lounge tokens.")};
g.k.hS=function(a){T7(this.I,"Requesting lounge tokens failed: "+a)};g.v(c8,g.R);g.k=c8.prototype;g.k.start=function(){var a=parseInt(g.Hz("yt-remote-fast-check-period")||"0",10);(this.C=g.Qa()-144E5<a?0:a)?f8(this):(this.C=g.Qa()+3E5,g.Gz("yt-remote-fast-check-period",this.C),this.UF())};
g.k.isEmpty=function(){return g.oc(this.i)};
g.k.update=function(){b8("Updating availability on schedule.");var a=this.I(),b=g.$b(this.i,function(c,d){return c&&!!$6(a,d)},this);
e8(this,b)};
g.k.ya=function(){g.Zs(this.B);this.B=NaN;this.u&&(this.u.abort(),this.u=null);g.R.prototype.ya.call(this)};
g.k.UF=function(){g.Zs(this.B);this.B=NaN;this.u&&this.u.abort();var a=BTa(this);if(Q6(a)){var b=Q7(this.D,"/pairing/get_screen_availability");this.u=R7(this.D,b,{lounge_token:g.ic(a).join(",")},(0,g.D)(this.MV,this,a),(0,g.D)(this.LV,this))}else e8(this,{}),f8(this)};
g.k.MV=function(a,b){this.u=null;var c=g.ic(BTa(this));if(g.Pb(c,g.ic(a))){b=b.screens||[];c={};for(var d=0,e=b.length;d<e;++d)c[a[b[d].loungeToken]]="online"==b[d].status;e8(this,c);f8(this)}else this.ke("Changing Screen set during request."),this.UF()};
g.k.LV=function(a){this.ke("Screen availability failed: "+a);this.u=null;f8(this)};
g.k.ke=function(a){T7("OnlineScreenService",a)};g.Ra(g8,X7);g.k=g8.prototype;g.k.start=function(){this.u.start();this.i.start();this.screens.length&&(this.ea("screenChange"),this.i.isEmpty()||this.ea("onlineScreenChange"))};
g.k.add=function(a,b,c){this.u.add(a,b,c)};
g.k.remove=function(a,b,c){this.u.remove(a,b,c);this.i.update()};
g.k.oB=function(a,b,c,d){this.u.contains(a)?this.u.oB(a,b,c,d):(a="Updating name of unknown screen: "+a.name,T7(this.I,a),d(Error(a)))};
g.k.Fh=function(a){return a?this.screens:g.Cb(this.screens,g.Do(this.B,function(b){return!this.contains(b)},this))};
g.k.fI=function(){return g.Do(this.Fh(!0),function(a){return!!this.i.i[a.id]},this)};
g.k.gI=function(a,b,c,d,e,f){var h=this;this.info("getDialScreenByPairingCode "+a+" / "+b);var l=new Y7(this.C,a,b,c,d);l.subscribe("pairingComplete",function(m,n){g.ve(l);e(h8(h,m),n)});
l.subscribe("pairingFailed",function(m){g.ve(l);f(m)});
l.start();return(0,g.D)(l.stop,l)};
g.k.yQ=function(a,b,c,d){g.wt(Q7(this.C,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:a},timeout:5E3,onSuccess:(0,g.D)(function(e,f){e=new U6(f.screen||{});if(!e.name||FTa(this,e.name)){a:{f=e.name;for(var h=2,l=b(f,h);FTa(this,l);){h++;if(20<h)break a;l=b(f,h)}f=l}e.name=f}c(h8(this,e))},this),
onError:(0,g.D)(function(e){d(Error("pairing request failed: "+e.status))},this),
onTimeout:(0,g.D)(function(){d(Error("pairing request timed out."))},this)})};
g.k.ya=function(){g.ve(this.u);g.ve(this.i);g8.je.ya.call(this)};
g.k.rS=function(){HTa(this);this.ea("screenChange");this.i.update()};
g8.prototype.dispose=g8.prototype.dispose;g.Ra(j8,g.R);g.k=j8.prototype;g.k.getScreen=function(){return this.C};
g.k.xg=function(a){this.isDisposed()||(a&&(l8(this,""+a),this.ea("sessionFailed")),this.C=null,this.ea("sessionScreen",null))};
g.k.info=function(a){T7(this.Ba,a)};
g.k.hI=function(){return null};
g.k.kG=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.D)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.D)(function(){l8(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.k.ya=function(){this.kG("");j8.je.ya.call(this)};g.v(m8,j8);g.k=m8.prototype;g.k.jG=function(a){if(this.u){if(this.u==a)return;l8(this,"Overriding cast session with new session object");QTa(this);this.va=!1;this.X="unknown";this.u.removeUpdateListener(this.Z);this.u.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.Aa)}this.u=a;this.u.addUpdateListener(this.Z);this.u.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.Aa);MTa(this,"getMdxSessionStatus")};
g.k.Ks=function(a){this.info("launchWithParams no-op for Cast: "+g.Rh(a))};
g.k.stop=function(){this.u?this.u.stop((0,g.D)(function(){this.xg()},this),(0,g.D)(function(){this.xg(Error("Failed to stop receiver app."))},this)):this.xg(Error("Stopping cast device without session."))};
g.k.kG=function(){};
g.k.ya=function(){this.info("disposeInternal");QTa(this);this.u&&(this.u.removeUpdateListener(this.Z),this.u.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.Aa));this.u=null;j8.prototype.ya.call(this)};
g.k.zW=function(a,b){if(!this.isDisposed())if(b)if(b=R6(b),g.Ma(b))switch(a=""+b.type,b=b.data||{},this.info("onYoutubeMessage_: "+a+" "+g.Rh(b)),a){case "mdxSessionStatus":KTa(this,b);break;case "loungeToken":NTa(this,b);break;default:l8(this,"Unknown youtube message: "+a)}else l8(this,"Unable to parse message.");else l8(this,"No data in message.")};
g.k.xK=function(a,b,c,d){g.Zs(this.S);this.S=0;ETa(this.B,this.i.label,a,this.i.friendlyName,(0,g.D)(function(e){e?b(e):0<=d?(l8(this,"Screen "+a+" appears to be offline. "+d+" retries left."),this.S=g.Xs((0,g.D)(this.xK,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.k.hI=function(){return this.u};
g.k.zQ=function(a){this.isDisposed()||a||(l8(this,"Cast session died."),this.xg())};g.v(p8,j8);g.k=p8.prototype;g.k.jG=function(a){this.u=a;this.u.addUpdateListener(this.Ja)};
g.k.Ks=function(a){this.La=a;this.ma()};
g.k.stop=function(){XTa(this);this.u?this.u.stop((0,g.D)(this.xg,this,null),(0,g.D)(this.xg,this,"Failed to stop DIAL device.")):this.xg()};
g.k.ya=function(){XTa(this);this.u&&this.u.removeUpdateListener(this.Ja);this.u=null;j8.prototype.ya.call(this)};
g.k.AQ=function(a){this.isDisposed()||a||(l8(this,"DIAL session died."),this.D(),this.D=g.Ia,this.xg())};g.v(t8,j8);t8.prototype.stop=function(){this.xg()};
t8.prototype.jG=function(){};
t8.prototype.Ks=function(){g.Zs(this.u);this.u=NaN;var a=$6(this.B.Fh(),this.i.label);a?k8(this,a):this.xg(Error("No such screen"))};
t8.prototype.ya=function(){g.Zs(this.u);this.u=NaN;j8.prototype.ya.call(this)};g.v(u8,g.R);g.k=u8.prototype;
g.k.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.S,[chrome.cast.Capability.AUDIO_OUT]);this.X||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED;a=a||this.I?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION;var e=(0,g.D)(this.vV,this);c=new chrome.cast.ApiConfig(c,(0,g.D)(this.PM,this),e,d,a);c.customDialLaunchCallback=(0,g.D)(this.qU,this);
chrome.cast.initialize(c,(0,g.D)(function(){this.isDisposed()||(chrome.cast.addReceiverActionListener(this.D),sTa(),this.u.subscribe("onlineScreenChange",(0,g.D)(this.iI,this)),this.B=$Ta(this),chrome.cast.setCustomReceivers(this.B,g.Ia,(0,g.D)(function(f){this.ke("Failed to set initial custom receivers: "+g.Rh(f))},this)),this.ea("yt-remote-cast2-availability-change",w8(this)),b(!0))},this),(0,g.D)(function(f){this.ke("Failed to initialize API: "+g.Rh(f));
b(!1)},this))};
g.k.hX=function(a,b){v8("Setting connected screen ID: "+a+" -> "+b);if(this.i){var c=this.i.getScreen();if(!a||c&&c.id!=a)v8("Unsetting old screen status: "+this.i.i.friendlyName),x8(this,null)}if(a&&b){if(!this.i){c=$6(this.u.Fh(),a);if(!c){v8("setConnectedScreenStatus: Unknown screen.");return}if("shortLived"==c.idType){v8("setConnectedScreenStatus: Screen with id type to be short lived.");return}a=YTa(this,c);a||(v8("setConnectedScreenStatus: Connected receiver not custom..."),a=new chrome.cast.Receiver(c.uuid?
c.uuid:c.id,c.name),a.receiverType=chrome.cast.ReceiverType.CUSTOM,this.B.push(a),chrome.cast.setCustomReceivers(this.B,g.Ia,(0,g.D)(function(d){this.ke("Failed to set initial custom receivers: "+g.Rh(d))},this)));
v8("setConnectedScreenStatus: new active receiver: "+a.friendlyName);x8(this,new t8(this.u,a),!0)}this.i.kG(b)}else v8("setConnectedScreenStatus: no screen.")};
g.k.iX=function(a){this.isDisposed()?this.ke("Setting connection data on disposed cast v2"):this.i?this.i.Ks(a):this.ke("Setting connection data without a session")};
g.k.CQ=function(){this.isDisposed()?this.ke("Stopping session on disposed cast v2"):this.i?(this.i.stop(),x8(this,null)):v8("Stopping non-existing session")};
g.k.requestSession=function(){chrome.cast.requestSession((0,g.D)(this.PM,this),(0,g.D)(this.PV,this))};
g.k.ya=function(){this.u.unsubscribe("onlineScreenChange",(0,g.D)(this.iI,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.D);var a=pTa,b=g.Ha("yt.mdx.remote.debug.handlers_");g.Ab(b||[],a);g.ve(this.i);g.R.prototype.ya.call(this)};
g.k.ke=function(a){T7("Controller",a)};
g.k.RM=function(a,b){this.i==a&&(b||x8(this,null),this.ea("yt-remote-cast2-session-change",b))};
g.k.sV=function(a,b){if(!this.isDisposed())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),v8("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.i)if(this.i.i.label!=a.label)v8("onReceiverAction_: Stopping active receiver: "+this.i.i.friendlyName),this.i.stop();else{v8("onReceiverAction_: Casting to active receiver.");this.i.getScreen()&&this.ea("yt-remote-cast2-session-change",this.i.getScreen());break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:x8(this,
new t8(this.u,a));break;case chrome.cast.ReceiverType.DIAL:x8(this,new p8(this.u,a,this.C,this.config_));break;case chrome.cast.ReceiverType.CAST:x8(this,new m8(this.u,a,this.config_));break;default:this.ke("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.i&&this.i.i.label==a.label?this.i.stop():this.ke("Stopping receiver w/o session: "+a.friendlyName)}else this.ke("onReceiverAction_ called without receiver.")};
g.k.qU=function(a){if(this.isDisposed())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.ke("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.i?this.i.i:null;if(!c||c.label!=b.label)return this.ke("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.i.getScreen())return v8("Reselecting dial screen."),
this.ea("yt-remote-cast2-session-change",this.i.getScreen()),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.ke('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);x8(this,new p8(this.u,b,this.C,this.config_))}b=this.i;b.S=a;b.S.appState==chrome.cast.DialAppState.RUNNING?(a=b.S.extraData||{},c=a.screenId||null,q8(b)&&a.loungeToken?a.loungeTokenRefreshIntervalMs?a=UTa(b,{name:b.i.friendlyName,screenId:a.screenId,loungeToken:a.loungeToken,dialId:b.S.receiver.label,
screenIdType:"shortLived"},a.loungeTokenRefreshIntervalMs):(g.Cs(Error("No loungeTokenRefreshIntervalMs presents in additionalData: "+JSON.stringify(a)+".")),a=VTa(b,c)):a=VTa(b,c)):a=s8(b);return a};
g.k.PM=function(a){var b=this;if(!this.isDisposed()&&!this.I){v8("New cast session ID: "+a.sessionId);var c=a.receiver;if(c.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.i)if(c.receiverType==chrome.cast.ReceiverType.CAST)v8("Got resumed cast session before resumed mdx connection."),c.friendlyName=chrome.cast.unescape(c.friendlyName),x8(this,new m8(this.u,c,this.config_),!0);else{this.ke("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var d=this.i.i,e=$6(this.u.Fh(),
d.label);e&&V6(e,c.label)&&d.receiverType!=chrome.cast.ReceiverType.CAST&&c.receiverType==chrome.cast.ReceiverType.CAST&&(v8("onSessionEstablished_: manual to cast session change "+c.friendlyName),g.ve(this.i),this.i=new m8(this.u,c,this.config_),this.i.subscribe("sessionScreen",(0,g.D)(this.RM,this,this.i)),this.i.subscribe("sessionFailed",function(){return ZTa(b,b.i)}),this.i.Ks(null));
this.i.jG(a)}}};
g.k.BQ=function(){return this.i?this.i.hI():null};
g.k.PV=function(a){this.isDisposed()||(this.ke("Failed to estabilish a session: "+g.Rh(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&x8(this,null),this.ea("yt-remote-cast2-session-failed"))};
g.k.vV=function(a){v8("Receiver availability updated: "+a);if(!this.isDisposed()){var b=w8(this);this.K=a==chrome.cast.ReceiverAvailability.AVAILABLE;w8(this)!=b&&this.ea("yt-remote-cast2-availability-change",w8(this))}};
g.k.iI=function(){this.isDisposed()||(this.B=$Ta(this),v8("Updating custom receivers: "+g.Rh(this.B)),chrome.cast.setCustomReceivers(this.B,g.Ia,(0,g.D)(function(){this.ke("Failed to set custom receivers.")},this)),this.ea("yt-remote-cast2-availability-change",w8(this)))};
u8.prototype.setLaunchParams=u8.prototype.iX;u8.prototype.setConnectedScreenStatus=u8.prototype.hX;u8.prototype.stopSession=u8.prototype.CQ;u8.prototype.getCastSession=u8.prototype.BQ;u8.prototype.requestSession=u8.prototype.requestSession;u8.prototype.init=u8.prototype.init;u8.prototype.dispose=u8.prototype.dispose;var D8=[];g.k=I8.prototype;
g.k.reset=function(a){this.listId="";this.index=-1;this.videoId="";J8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.trackData=a.trackData,this.Ek=a.hasPrevious,this.hasNext=a.hasNext,this.K=a.playerTime,this.I=a.playerTimeAt,this.C=a.seekableStart,this.i=a.seekableEnd,this.D=a.duration,this.S=a.loadedTime,this.B=a.liveIngestionTime,this.u=
!isNaN(this.B))};
g.k.Dc=function(){return 1==this.playerState};
g.k.isAdPlaying=function(){return 1081==this.playerState};
g.k.Hj=function(a){this.D=isNaN(a)?0:a};
g.k.getDuration=function(){return this.u?this.D+K8(this):this.D};
g.k.clone=function(){return new I8(O8(this))};g.v(Q8,g.R);g.k=Q8.prototype;g.k.getState=function(){return this.B};
g.k.play=function(){S8(this)?(this.i?this.i.play(null,g.Ia,X8(this,"play")):W8(this,"play"),V8(this,1,M8(R8(this))),this.ea("remotePlayerChange")):T8(this,this.play)};
g.k.pause=function(){S8(this)?(this.i?this.i.pause(null,g.Ia,X8(this,"pause")):W8(this,"pause"),V8(this,2,M8(R8(this))),this.ea("remotePlayerChange")):T8(this,this.pause)};
g.k.seekTo=function(a){if(S8(this)){if(this.i){var b=R8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.Dc()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ia,X8(this,"seekTo",{newTime:a}))}else W8(this,"seekTo",{newTime:a});V8(this,3,a);this.ea("remotePlayerChange")}else T8(this,g.Pa(this.seekTo,a))};
g.k.stop=function(){if(S8(this)){this.i?this.i.stop(null,g.Ia,X8(this,"stopVideo")):W8(this,"stopVideo");var a=R8(this);a.index=-1;a.videoId="";J8(a);U8(this,a);this.ea("remotePlayerChange")}else T8(this,this.stop)};
g.k.setVolume=function(a,b){if(S8(this)){var c=R8(this);if(this.u){if(c.volume!=a){var d=Math.round(a)/100;this.u.setReceiverVolumeLevel(d,(0,g.D)(function(){T7("CP","set receiver volume: "+d)},this),(0,g.D)(function(){this.ke("failed to set receiver volume.")},this))}c.muted!=b&&this.u.setReceiverMuted(b,(0,g.D)(function(){T7("CP","set receiver muted: "+b)},this),(0,g.D)(function(){this.ke("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);W8(this,"setVolume",e)}c.muted=b;c.volume=a;U8(this,c)}else T8(this,g.Pa(this.setVolume,a,b))};
g.k.jI=function(a,b){if(S8(this)){var c=R8(this);a={videoId:a};b&&(c.trackData={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},a.style=g.Rh(b.style),g.wc(a,c.trackData));W8(this,"setSubtitlesTrack",a);U8(this,c)}else T8(this,g.Pa(this.jI,a,b))};
g.k.setAudioTrack=function(a,b){S8(this)?(b=b.getLanguageInfo().getId(),W8(this,"setAudioTrack",{videoId:a,audioTrackId:b}),a=R8(this),a.audioTrackId=b,U8(this,a)):T8(this,g.Pa(this.setAudioTrack,a,b))};
g.k.playVideo=function(a,b,c,d,e,f,h){d=void 0===d?null:d;e=void 0===e?null:e;f=void 0===f?null:f;h=void 0===h?null:h;var l=R8(this),m={videoId:a};void 0!==c&&(m.currentIndex=c);N8(l,a,c||0);void 0!==b&&(L8(l,b),m.currentTime=b);d&&(m.listId=d);e&&(m.playerParams=e);f&&(m.clickTrackingParams=f);h&&(m.locationInfo=g.Rh(h));W8(this,"setPlaylist",m);d||U8(this,l)};
g.k.BA=function(a,b){if(S8(this)){if(a&&b){var c=R8(this);N8(c,a,b);U8(this,c)}W8(this,"previous")}else T8(this,g.Pa(this.BA,a,b))};
g.k.nextVideo=function(a,b){if(S8(this)){if(a&&b){var c=R8(this);N8(c,a,b);U8(this,c)}W8(this,"next")}else T8(this,g.Pa(this.nextVideo,a,b))};
g.k.Jr=function(){if(S8(this)){W8(this,"clearPlaylist");var a=R8(this);a.reset();U8(this,a);this.ea("remotePlayerChange")}else T8(this,this.Jr)};
g.k.TJ=function(){S8(this)?W8(this,"dismissAutoplay"):T8(this,this.TJ)};
g.k.dispose=function(){if(3!=this.B){var a=this.B;this.B=3;this.ea("proxyStateChange",a,this.B)}g.R.prototype.dispose.call(this)};
g.k.ya=function(){lUa(this);this.C=null;this.D.clear();P8(this,null);g.R.prototype.ya.call(this)};
g.k.lG=function(a){if((a!=this.B||2==a)&&3!=this.B&&0!=a){var b=this.B;this.B=a;this.ea("proxyStateChange",b,a);if(1==a)for(;!this.D.isEmpty();)b=a=this.D,0===b.i.length&&(b.i=b.u,b.i.reverse(),b.u=[]),a.i.pop().apply(this);else 3==a&&this.dispose()}};
g.k.qV=function(a,b){this.ea(a,b)};
g.k.bU=function(a){if(!a)this.Aw(null),P8(this,null);else if(this.u.receiver.volume){a=this.u.receiver.volume;var b=R8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)T7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,U8(this,b)}};
g.k.Aw=function(a){T7("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.S);if(this.i=a)this.i.addUpdateListener(this.S),mUa(this),this.ea("remotePlayerChange")};
g.k.aU=function(a){a?(mUa(this),this.ea("remotePlayerChange")):this.Aw(null)};
g.k.GG=function(){W8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.k.iU=function(){var a=iUa();a&&P8(this,a)};
g.k.ke=function(a){T7("CP",a)};g.v(Y8,g.R);g.k=Y8.prototype;
g.k.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.videoIds,f=b.playerParams,h=b.clickTrackingParams,l=b.index,m={videoId:d},n=b.currentTime,p=b.locationInfo;b=b.loopMode;void 0!==n&&(m.currentTime=5>=n?0:n);f&&(m.playerParams=f);p&&(m.locationInfo=p);h&&(m.clickTrackingParams=h);c&&(m.listId=c);e&&0<e.length&&(m.videoIds=e.join(","));void 0!==l&&(m.currentIndex=l);this.Ba&&(m.loopMode=b||"LOOP_MODE_OFF");c&&(this.fc.listId=c);this.fc.videoId=d;this.fc.index=l||0;this.fc.state=3;L8(this.fc,
n);this.C="UNSUPPORTED";c=this.Ba?"setInitialState":"setPlaylist";Z8("Connecting with "+c+" and params: "+g.Rh(m));this.i.connect({method:c,params:g.Rh(m)},a,vSa())}else Z8("Connecting without params"),this.i.connect({},a,vSa());pUa(this)};
g.k.UA=function(a){this.i.UA(a)};
g.k.dispose=function(){this.isDisposed()||(g.Ga("yt.mdx.remote.remoteClient_",null,void 0),this.ea("beforeDispose"),$8(this,3));g.R.prototype.dispose.call(this)};
g.k.ya=function(){a9(this);c9(this);b9(this);g.Zs(this.K);this.K=NaN;g.Zs(this.S);this.S=NaN;this.B=null;g.wu(this.X);this.X.length=0;this.i.dispose();g.R.prototype.ya.call(this);this.C=this.I=this.u=this.fc=this.i=null};
g.k.dS=function(){this.Sr(2)};
g.k.fU=function(){Z8("Channel opened");this.va&&(this.va=!1,b9(this),this.Z=g.Xs((0,g.D)(function(){Z8("Timing out waiting for a screen.");this.Sr(1)},this),15E3));
zSa(nTa(this.i),this.La)};
g.k.cU=function(){Z8("Channel closed");isNaN(this.D)?e7(!0):e7();this.dispose()};
g.k.dU=function(a,b){e7();isNaN(this.Mv())?(b&&"shortLived"==this.Aa&&this.ea("browserChannelAuthError",a),Z8("Channel error: "+a+" without reconnection"),this.dispose()):(this.va=!0,Z8("Channel error: "+a+" with reconnection in "+this.Mv()+" ms"),$8(this,2))};
g.k.hL=function(a){if(!this.u||0===this.u.length)return!1;for(var b=g.r(this.u),c=b.next();!c.done;c=b.next())if(!c.value.capabilities.has(a))return!1;return!0};
g.k.eU=function(a){a.params?Z8("Received: action="+a.action+", params="+g.Rh(a.params)):Z8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=R6(a.params.devices);this.u=g.jm(a,function(c){return new T6(c)});
a=!!g.sb(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
sUa(this,a);a=this.hL("mlm");this.ea("multiStateLoopEnabled",a);break;case "loungeScreenDisconnected":g.Bb(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
sUa(this,!1);break;case "remoteConnected":var b=new T6(R6(a.params.device));g.sb(this.u,function(c){return b?c.id==b.id:!1})||iSa(this.u,b);
break;case "remoteDisconnected":b=new T6(R6(a.params.device));g.Bb(this.u,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":uUa(this,a);break;case "nowPlaying":wUa(this,a);break;case "onStateChange":vUa(this,a);break;case "onAdStateChange":xUa(this,a);break;case "onVolumeChanged":yUa(this,a);break;case "onSubtitlesTrackChanged":tUa(this,a);break;case "nowAutoplaying":zUa(this,a);break;case "autoplayDismissed":this.ea("autoplayDismissed");break;case "autoplayUpNext":this.I=a.params.videoId||null;this.ea("autoplayUpNext",this.I);break;case "onAutoplayModeChanged":this.C=
a.params.autoplayMode;this.ea("autoplayModeChange",this.C);"DISABLED"==this.C&&this.ea("autoplayDismissed");break;case "onHasPreviousNextChanged":AUa(this,a);break;case "requestAssistedSignIn":this.ea("assistedSignInRequested",a.params.authCode);break;case "onLoopModeChanged":this.ea("loopModeChange",a.params.loopMode);break;default:Z8("Unrecognized action: "+a.action)}};
g.k.VW=function(){if(this.B){var a=this.B;this.B=null;this.fc.videoId!=a&&d9(this,"getNowPlaying")}};
g.k.ZR=function(){var a=3;this.isDisposed()||(a=0,isNaN(this.Mv())?O7(this.i)&&isNaN(this.D)&&(a=1):a=2);return a};
g.k.Sr=function(a){Z8("Disconnecting with "+a);g.Ga("yt.mdx.remote.remoteClient_",null,void 0);a9(this);this.ea("beforeDisconnect",a);1==a&&e7();oTa(this.i,a);this.dispose()};
g.k.XR=function(){var a=this.fc;this.B&&(a=this.fc.clone(),N8(a,this.B,a.index));return O8(a)};
g.k.jX=function(a){var b=new I8(a);b.videoId&&b.videoId!=this.fc.videoId&&(this.B=b.videoId,g.Zs(this.K),this.K=g.Xs((0,g.D)(this.VW,this),5E3));var c=[];this.fc.listId==b.listId&&this.fc.videoId==b.videoId&&this.fc.index==b.index||c.push("remoteQueueChange");this.fc.playerState==b.playerState&&this.fc.volume==b.volume&&this.fc.muted==b.muted&&M8(this.fc)==M8(b)&&g.Rh(this.fc.trackData)==g.Rh(b.trackData)||c.push("remotePlayerChange");this.fc.reset(a);g.Rb(c,function(d){this.ea(d)},this)};
g.k.wK=function(){var a=this.i.I.id,b=g.sb(this.u,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.k.Mv=function(){var a=this.i;return a.u.isActive()?a.u.u-Date.now():NaN};
g.k.UR=function(){return this.C||"UNSUPPORTED"};
g.k.VR=function(){return this.I||""};
g.k.DQ=function(){if(!isNaN(this.Mv())){var a=this.i.u;g.Iq(a.i);a.start()}};
g.k.gX=function(a,b){d9(this,a,b);rUa(this)};
g.k.kI=function(){var a=g.Jt("SID","")||"",b=g.Jt("SAPISID","")||"",c=g.Jt("__Secure-3PAPISID","")||"";if(!a&&!b&&!c)return"";a=g.Qc(g.Za(a),2);b=g.Qc(g.Za(b),2);c=g.Qc(g.Za(c),2);return g.Qc(g.Za(a+","+b+","+c),2)};
Y8.prototype.subscribe=Y8.prototype.subscribe;Y8.prototype.unsubscribeByKey=Y8.prototype.cg;Y8.prototype.getProxyState=Y8.prototype.ZR;Y8.prototype.disconnect=Y8.prototype.Sr;Y8.prototype.getPlayerContextData=Y8.prototype.XR;Y8.prototype.setPlayerContextData=Y8.prototype.jX;Y8.prototype.getOtherConnectedRemoteId=Y8.prototype.wK;Y8.prototype.getReconnectTimeout=Y8.prototype.Mv;Y8.prototype.getAutoplayMode=Y8.prototype.UR;Y8.prototype.getAutoplayVideoId=Y8.prototype.VR;Y8.prototype.reconnect=Y8.prototype.DQ;
Y8.prototype.sendMessage=Y8.prototype.gX;Y8.prototype.getXsrfToken=Y8.prototype.kI;Y8.prototype.isCapabilitySupportedOnConnectedDevices=Y8.prototype.hL;g.v(e9,X7);g.k=e9.prototype;g.k.Fh=function(a){return this.Se.$_gs(a)};
g.k.contains=function(a){return!!this.Se.$_c(a)};
g.k.get=function(a){return this.Se.$_g(a)};
g.k.start=function(){this.Se.$_st()};
g.k.add=function(a,b,c){this.Se.$_a(a,b,c)};
g.k.remove=function(a,b,c){this.Se.$_r(a,b,c)};
g.k.oB=function(a,b,c,d){this.Se.$_un(a,b,c,d)};
g.k.ya=function(){for(var a=0,b=this.i.length;a<b;++a)this.Se.$_ubk(this.i[a]);this.i.length=0;this.Se=null;X7.prototype.ya.call(this)};
g.k.EQ=function(){this.ea("screenChange")};
g.k.XU=function(){this.ea("onlineScreenChange")};
g8.prototype.$_st=g8.prototype.start;g8.prototype.$_gspc=g8.prototype.yQ;g8.prototype.$_gsppc=g8.prototype.gI;g8.prototype.$_c=g8.prototype.contains;g8.prototype.$_g=g8.prototype.get;g8.prototype.$_a=g8.prototype.add;g8.prototype.$_un=g8.prototype.oB;g8.prototype.$_r=g8.prototype.remove;g8.prototype.$_gs=g8.prototype.Fh;g8.prototype.$_gos=g8.prototype.fI;g8.prototype.$_s=g8.prototype.subscribe;g8.prototype.$_ubk=g8.prototype.cg;var r9=null,x9=!1,f9=null,g9=null,w9=null,k9=[];g.v(y9,g.H);g.k=y9.prototype;g.k.ya=function(){g.H.prototype.ya.call(this);this.i.stop();this.B.stop();this.S.stop();this.Z();var a=this.Sb;a.unsubscribe("proxyStateChange",this.MM,this);a.unsubscribe("remotePlayerChange",this.Ew,this);a.unsubscribe("remoteQueueChange",this.nA,this);a.unsubscribe("previousNextChange",this.JM,this);a.unsubscribe("nowAutoplaying",this.DM,this);a.unsubscribe("autoplayDismissed",this.gM,this);this.Sb=this.u=null};
g.k.mj=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.Sb.B)if(z9(this)){if(!R8(this.Sb).isAdPlaying()||"control_seek"!==a)switch(a){case "control_toggle_play_pause":R8(this.Sb).Dc()?this.Sb.pause():this.Sb.play();break;case "control_play":this.Sb.play();break;case "control_pause":this.Sb.pause();break;case "control_seek":this.K.eI(c[0],c[1]);break;case "control_subtitles_set_track":A9(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=
this.J.getCurrentTime();B9(this,0===c?void 0:c);break;case "control_seek":B9(this,c[0]);break;case "control_subtitles_set_track":A9(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}};
g.k.XT=function(a){this.S.sQ(a)};
g.k.PX=function(a){this.mj("control_subtitles_set_track",g.oc(a)?null:a)};
g.k.eO=function(){var a=this.J.getOption("captions","track");g.oc(a)||A9(this,a)};
g.k.Wb=function(a){this.u.Wb(a,this.J.getVideoData().lengthSeconds)};
g.k.IU=function(){g.oc(this.C)||LUa(this,this.C);this.D=!1};
g.k.MM=function(a,b){this.B.stop();2===b&&this.YN()};
g.k.Ew=function(){if(z9(this)){this.i.stop();var a=R8(this.Sb);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.u.uf=1;break;case 1082:case 1083:this.u.uf=0;break;default:this.u.uf=-1}switch(a.playerState){case 1081:case 1:this.Tb(new g.QJ(8));this.XN();break;case 1085:case 3:this.Tb(new g.QJ(9));break;case 1083:case 0:this.Tb(new g.QJ(2));this.K.stop();this.Wb(this.J.getVideoData().lengthSeconds);break;case 1084:this.Tb(new g.QJ(4));break;case 2:this.Tb(new g.QJ(4));this.Wb(M8(a));
break;case -1:this.Tb(new g.QJ(64));break;case -1E3:this.Tb(new g.QJ(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=R8(this.Sb).trackData;var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.C=a,LUa(this,a));a=R8(this.Sb);-1===a.volume||Math.round(this.J.getVolume())===a.volume&&this.J.isMuted()===a.muted||this.X.isActive()||this.GO()}else KUa(this)};
g.k.JM=function(){this.J.ea("mdxpreviousnextchange")};
g.k.nA=function(){z9(this)||KUa(this)};
g.k.DM=function(a){isNaN(a)||this.J.ea("mdxnowautoplaying",a)};
g.k.gM=function(){this.J.ea("mdxautoplaycanceled")};
g.k.setAudioTrack=function(a){z9(this)&&this.Sb.setAudioTrack(this.J.getVideoData(1).videoId,a)};
g.k.seekTo=function(a,b){-1===R8(this.Sb).playerState?B9(this,a):b&&this.Sb.seekTo(a)};
g.k.GO=function(){var a=this;if(z9(this)){var b=R8(this.Sb);this.events.hc(this.ma);b.muted?this.J.mute():this.J.unMute();this.J.setVolume(b.volume);this.ma=this.events.T(this.J,"onVolumeChange",function(c){JUa(a,c)})}};
g.k.XN=function(){this.i.stop();if(!this.Sb.isDisposed()){var a=R8(this.Sb);a.Dc()&&this.Tb(new g.QJ(8));this.Wb(M8(a));this.i.start()}};
g.k.YN=function(){this.B.stop();this.i.stop();var a=this.Sb.C.getReconnectTimeout();2==this.Sb.B&&!isNaN(a)&&this.B.start()};
g.k.Tb=function(a){this.B.stop();var b=this.I;if(!g.VJ(b,a)){var c=g.U(a,2);c!==g.U(this.I,2)&&this.J.wt(c);this.I=a;NUa(this.u,b,a)}};g.v(C9,g.V);C9.prototype.td=function(){this.i.show()};
C9.prototype.Db=function(){this.i.hide()};
C9.prototype.u=function(){S6("mdx-privacy-popup-cancel");this.Db()};
C9.prototype.B=function(){S6("mdx-privacy-popup-confirm");this.Db()};g.v(D9,g.V);D9.prototype.onStateChange=function(a){MUa(this,a.state)};g.v(E9,g.OP);E9.prototype.D=function(){var a=this.J.getOption("remote","receivers");a&&1<a.length&&!this.J.getOption("remote","quickCast")?(this.qo=g.Ub(a,this.i,this),g.PP(this,g.jm(a,this.i)),a=this.J.getOption("remote","currentReceiver"),a=this.i(a),this.options[a]&&this.Wh(a),this.enable(!0)):this.enable(!1)};
E9.prototype.i=function(a){return a.key};
E9.prototype.cj=function(a){return"cast-selector-receiver"===a?"Cast...":this.qo[a].name};
E9.prototype.Bf=function(a){g.OP.prototype.Bf.call(this,a);this.J.setOption("remote","currentReceiver",this.qo[a]);this.Ab.Db()};g.v(F9,g.ZM);g.k=F9.prototype;
g.k.create=function(){var a=this.player.V(),b=g.ZE(a);a={device:"Desktop",app:"youtube-desktop",loadCastApiSetupScript:a.N("mdx_load_cast_api_bootstrap_script"),enableDialLoungeToken:a.N("enable_dial_short_lived_lounge_token"),enableCastLoungeToken:a.N("enable_cast_short_lived_lounge_token")};EUa(b,a);this.subscriptions.push(g.bv("yt-remote-before-disconnect",this.VT,this));this.subscriptions.push(g.bv("yt-remote-connection-change",this.wV,this));this.subscriptions.push(g.bv("yt-remote-receiver-availability-change",this.LM,
this));this.subscriptions.push(g.bv("yt-remote-auto-connect",this.uV,this));this.subscriptions.push(g.bv("yt-remote-receiver-resumed",this.tV,this));this.subscriptions.push(g.bv("mdx-privacy-popup-confirm",this.KW,this));this.subscriptions.push(g.bv("mdx-privacy-popup-cancel",this.JW,this));this.LM()};
g.k.load=function(){this.player.cancelPlayback();g.ZM.prototype.load.call(this);this.ai=new y9(this,this.player,this.Sb);var a=(a=IUa())?a.currentTime:0;var b=v9()?new Q8(p9(),void 0):null;0==a&&b&&(a=M8(R8(b)));0!==a&&this.Wb(a);NUa(this,this.ud,this.ud);this.player.Vk(6)};
g.k.unload=function(){this.player.ea("mdxautoplaycanceled");this.Wm=this.Lk;(0,g.we)(this.ai,this.Sb);this.Sb=this.ai=null;g.ZM.prototype.unload.call(this);this.player.Vk(5);G9(this)};
g.k.ya=function(){g.cv(this.subscriptions);g.ZM.prototype.ya.call(this)};
g.k.Nk=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.ai.mj.apply(this.ai,[a].concat(g.ma(c)))};
g.k.getAdState=function(){return this.uf};
g.k.Ek=function(){return this.Sb?R8(this.Sb).Ek:!1};
g.k.hasNext=function(){return this.Sb?R8(this.Sb).hasNext:!1};
g.k.Wb=function(a,b){this.xL=a||0;this.player.ea("progresssync",a,b);this.player.Na("onVideoProgress",a||0)};
g.k.getCurrentTime=function(){return this.xL};
g.k.getProgressState=function(){var a=R8(this.Sb),b=this.player.getVideoData();return{airingStart:0,airingEnd:0,allowSeeking:this.player.V().N("web_player_mdx_allow_seeking_change_killswitch")?this.player.rf():!a.isAdPlaying()&&this.player.rf(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.u?a.B+K8(a):a.B,isAtLiveHead:1>=(a.u?a.i+K8(a):a.i)-this.getCurrentTime(),loaded:a.S,seekableEnd:a.u?a.i+K8(a):a.i,seekableStart:0<
a.C?a.C+K8(a):a.C}};
g.k.nextVideo=function(){this.Sb&&this.Sb.nextVideo()};
g.k.BA=function(){this.Sb&&this.Sb.BA()};
g.k.VT=function(a){1===a&&(this.IF=this.Sb?R8(this.Sb):null)};
g.k.wV=function(){var a=v9()?new Q8(p9(),void 0):null;if(a){var b=this.Wm;this.loaded&&this.unload();this.Sb=a;this.IF=null;b.key!==this.Lk.key&&(this.Wm=b,this.load())}else(0,g.ve)(this.Sb),this.Sb=null,this.loaded&&(this.unload(),(a=this.IF)&&a.videoId===this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,M8(a)));this.player.ea("videodatachange","newdata",this.player.getVideoData(),3)};
g.k.LM=function(){var a=[this.Lk],b=a.concat,c=FUa();E8()&&g.Hz("yt-remote-cast-available")&&c.push({key:"cast-selector-receiver",name:"Cast..."});this.qo=b.call(a,c);a=q9()||this.Lk;H9(this,a);this.player.Na("onMdxReceiversChange")};
g.k.uV=function(){var a=q9();H9(this,a)};
g.k.tV=function(){this.Wm=q9()};
g.k.KW=function(){this.Nw=!0;G9(this);x9=!1;r9&&t9(r9,1);r9=null};
g.k.JW=function(){this.Nw=!1;G9(this);H9(this,this.Lk);this.Wm=this.Lk;x9=!1;r9=null;this.player.playVideo()};
g.k.jf=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.qo;case "currentReceiver":return b&&("cast-selector-receiver"===b.key?G8():H9(this,b)),this.loaded?this.Wm:this.Lk;case "quickCast":return 2===this.qo.length&&"cast-selector-receiver"===this.qo[1].key?(b&&G8(),!0):!1}};
g.k.GG=function(){this.Sb.GG()};
g.k.Ji=function(){return!1};
g.k.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.YM("remote",F9);})(_yt_player);
